insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('A', 'Award', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('AF', 'Faculty Award', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('AFR', 'Faculty Award With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('AR', 'Award With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('AS', 'Student Award', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('ASR', 'Student Award With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('C', 'Construction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('CI', 'Capital Improvement', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('CID', 'Capital Improvement With Restriction to Department, School or Program', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('CIR', 'Capital Improvement With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('CR', 'Construction With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('D', 'Curatorship', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('D3', 'Curatorship - Presidents Match Participant', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('DR', 'Curatorship - With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('DR3', 'Curatorship - With Some Restriction - Presidents Match Participant', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('E', 'Internships', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('ER', 'Internships With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('F', 'Graduate Fellowship', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('F3', 'Graduate Fellowship - Presidents Match Participant', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('FF', 'Faculty Fellowship', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('FF3', 'Faculty Fellowship - Presidents Match Participant', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('FFR', 'Faculty Fellowship With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('FR', 'Graduate Fellowship With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('FR3', 'Graduate Fellowship With Some Restriction - Presidents Match Participant', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('I', 'Internal IUF Accounts', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('IR', 'Internal IUF Accounts With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('L', 'Lectureship', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('LR', 'Lectureship With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('M', 'General Endowment - Multi Use Account', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('M3', 'General Endowment - Multi Use Account - Presidents Match Participant', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('MD', 'General Endowment - Multi Use Account With Restriction to Department, School or Program', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('MD3', 'General Endowment - Multi Use Account With Restriction to Department', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('MPP', 'General Endowment - Multi Use Account - Medical School Practice Plan Account', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('MR', 'General Endowment - Multi Use Account With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('MR3', 'General Endowment - Multi Use Account With Some Restriction - Presidents Match Participant', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('N', 'Loan', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('NR', 'Loan With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('O', 'Operating Account', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('OD', 'Operating Account With Restriction to Department, School or Program', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('OD3', 'Operating Account With Restriction to Department, School or Program - Presidents Match Participant', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('OPP', 'Operating Account - Medical School Practice Plan Account', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('OR', 'Operating Account With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('OR3', 'Operating Account With Restriction - Presidents Match Participant', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('P', 'Professorship', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('P3', 'Professorship - Presidents Match Participant', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('PR', 'Professorship With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('PR3', 'Professorship With Some Restriction - Presidents Match Participant', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('Q', 'Chair', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('Q3', 'Chair - Presidents Match Participant', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('QR', 'Chair With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('QR3', 'Chair With Some Restriction - Presidents Match Participant', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('R', 'Research', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('RD', 'Research With  Restriction to Department, School or Program', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('RD3', 'Research With  Restriction to Department, School or Program - Presidents Match Participant', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('RR', 'Research With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('RR3', 'Research With Some Restriction - Presidents Match Participant', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('SB', 'Scholarship - Undergraduate or Graduate', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('SB3', 'Scholarship - Undergraduate or Graduate - Presidents Match Participant', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('SBR', 'Scholarship - Undergraduate or Graduate With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('SG', 'Scholarship - Graduate', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('SG3', 'Scholarship - Graduate - Presidents Match Participant', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('SGR', 'Scholarship - Graduate With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('SH', 'Scholarship - Undergraduate - Honors Division', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('SHR', 'Scholarship - Undergraduate - Honors Division With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('SU', 'Scholarship - Undergraduate', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('SU3', 'Scholarship - Undergraduate - Presidents Match Participant', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('SUR', 'Scholarship - Undergraduate With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('TCA', 'Trust - Annuity', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('TCU', 'Trust - Unitrust', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('U', 'Undesignated', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('XA', 'Art Acquisition', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('XA3', 'Art Acquisition - Presidents Match Participant', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('XAR', 'Art Acquisition With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('XL', 'Library Acquisition', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('XL3', 'Library Acquisition - Presidents Match Participant', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('XLR', 'Library Acquisition With Some Restriction', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('Z', 'Agency', 'Y',sys_guid());
insert into END_PRPS_CD_T columns (PRPS_CD, PRPS_DESC, ROW_ACTV_IND, OBJ_ID) values ('ZR', 'Agency With Some Restriction', 'Y',sys_guid());
