insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('01P', 'PEF RE', 'N',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0AI', 'ACM (Pooled Short Term Fund)', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0AP', 'ACM (Pooled Short Term Fund)', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0BI', 'Brokers/General', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0BP', 'Brokers/General', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0CI', 'Pooled Funds (Equity, Fixed, Long Term)', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0CP', 'Pooled Funds (Equity, Fixed, Long Term)', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0DI', 'BONY - William Blair', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0DP', 'BONY - William Blair', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0EI', 'BONY - Equity Trust Investment Pool', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0EP', 'BONY - Equity Trust Investment Pool', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0FI', 'BONY - Champlain Investment Partners', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0FP', 'BONY - Champlain Investment Partners', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0GI', 'BONY - Grayson Fund', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0GP', 'BONY - Grayson Fund', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0HI', 'Howard County - Key Bank', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0HP', 'Howard County - Key Bank', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0IP', 'Jump', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0KI', 'BONY - Cramer Rosenthal McGlynn', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0KP', 'BONY - Cramer Rosenthal McGlynn', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0LI', 'Lowengreen', 'N',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0MI', 'Madison', 'N',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0NI', 'BONY - Separately Held Account', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0NP', 'BONY - Separately Held Account', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0OI', 'BONY - PEF/Other Account', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0OP', 'BONY - PEF/Other Account', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0QI', 'BONY - Templeton Instutional Funds - International', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0QP', 'BONY - Templeton Instutional Funds - International', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0RI', 'Reese Fund', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0RP', 'Reese Fund', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0SI', 'BONY - Snyder Capital Management', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0SP', 'BONY - Snyder Capital Management', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0TI', 'BONY - Bond Trust Investment Pool', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0TP', 'BONY - Bond Trust Investment Pool', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0VI', 'National Bank of Indianapolis - Val Nolan Fund', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0VP', 'National Bank of Indianapolis - Val Nolan Fund', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0WI', 'BONY - Loomis Sayles', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0WP', 'BONY - Loomis Sayles', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0XI', 'no longer in use', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0YI', 'BONY - PIMCO', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0YP', 'BONY - PIMCO', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0ZI', 'Mutual Funds (BGI, Common Fund, Alt Mgrs, etc.)', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('0ZP', 'Mutual Funds (BGI, Common Fund, Alt Mgrs, etc.)', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('CDI', 'Certificate of Deposit', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('CDP', 'Certificate of Deposit', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('MAI', 'Miscellaneous Assets', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('MAP', 'Miscellaneous Assets', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('MLI', 'Miscellaneous Liability', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('MLP', 'Miscellaneous Liabilities', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('REI', 'Real Estate', 'Y',sys_guid());
insert into END_REGIS_CD_T columns (REGIS_CD, REGIS_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('REP', 'Real Estate', 'Y',sys_guid());
