insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('1', 'Grant Agreement', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('A', 'Account Agreement', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('B', 'Fund Description', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('C', 'Account Form', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('D', 'Account Administration Agreement', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('E', 'Agreement', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('F', 'Fund Administration Agreement', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('G', 'Gift Agreement', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('H', 'Last Will and Testament', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('I', 'Instructions for the Administration of', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('J', 'Letter of Agreement', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('K', 'Pledge Agreement', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('L', 'Letter', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('M', 'Memo of Understanding', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('N', 'Construction Agreement', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('O', 'Donor Intent Memo', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('P', 'Proposal', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('Q', 'Procedures', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('R', 'Resolution', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('S', 'Solicitation', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('T', 'Trust Agreement', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('U', 'Court Order', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('V', 'Donor Advised Fund Agreement', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('W', 'Warranty Deed', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('X', 'None', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('Y', 'Agency Agreement', 'Y',sys_guid());
insert into END_AGRMNT_TYP_CD_T columns (AGRMNT_TYP_CD, AGRMNT_TYP_CD_DESC, ROW_ACTV_IND, OBJ_ID) values ('Z', 'Not Applicable', 'Y',sys_guid());
