create table END_TRAN_SUB_TYP_T (
	TRAN_SUB_TYP_CD VARCHAR2(1),
	TRAN_SUB_TYP_DESC VARCHAR2(40),
	OBJ_ID VARCHAR2(36) NOT NULL,
	VER_NBR NUMBER(8, 0) DEFAULT 1 NOT NULL,
	PRIMARY KEY (TRAN_SUB_TYP_CD)
);

insert into END_TRAN_SUB_TYP_T columns (TRAN_SUB_TYP_CD, TRAN_SUB_TYP_DESC, OBJ_ID) values ('C','Cash', sys_guid());
insert into END_TRAN_SUB_TYP_T columns (TRAN_SUB_TYP_CD, TRAN_SUB_TYP_DESC, OBJ_ID) values ('N','Non-Cash', sys_guid());


create table END_TRAN_SRC_TYP_T (
	TRAN_SRC_TYP_CD VARCHAR2(1),
	TRAN_SRC_TYP_DESC VARCHAR2(40),
	OBJ_ID VARCHAR2(36) NOT NULL,
	VER_NBR NUMBER(8, 0) DEFAULT 1 NOT NULL,
	PRIMARY KEY (TRAN_SRC_TYP_CD)
);

insert into END_TRAN_SRC_TYP_T columns (TRAN_SRC_TYP_CD, TRAN_SRC_TYP_DESC, OBJ_ID) values ('A','Automated Entry', sys_guid());
insert into END_TRAN_SRC_TYP_T columns (TRAN_SRC_TYP_CD, TRAN_SRC_TYP_DESC, OBJ_ID) values ('M','Manual Entry', sys_guid());
insert into END_TRAN_SRC_TYP_T columns (TRAN_SRC_TYP_CD, TRAN_SRC_TYP_DESC, OBJ_ID) values ('R','Recurring Entry', sys_guid());

create table END_TRAN_DOC_T (
    	FDOC_NBR VARCHAR2(14) NOT NULL,
	TRAN_SUB_TYP_CD VARCHAR2(1) NOT NULL,
	TRAN_SRC_TYP_CD VARCHAR2(1) NOT NULL,
	TRAN_PSTD VARCHAR2(1) DEFAULT 'N' NOT NULL,
	OBJ_ID VARCHAR2(36) NOT NULL,
	VER_NBR NUMBER(8, 0) DEFAULT 1 NOT NULL,
	PRIMARY KEY (FDOC_NBR)
);


ALTER TABLE END_TRAN_DOC_T ADD CONSTRAINT END_TRAN_DOC_TR1 FOREIGN KEY (FDOC_NBR)
	REFERENCES KRNS_DOC_HDR_T (DOC_HDR_ID);

ALTER TABLE END_TRAN_DOC_T ADD CONSTRAINT END_TRAN_DOC_TR2 FOREIGN KEY (TRAN_SUB_TYP_CD)
	REFERENCES END_TRAN_SUB_TYP_T (TRAN_SUB_TYP_CD);
	
ALTER TABLE END_TRAN_DOC_T ADD CONSTRAINT END_TRAN_DOC_TR3 FOREIGN KEY (TRAN_SRC_TYP_CD)
	REFERENCES END_TRAN_SRC_TYP_T (TRAN_SRC_TYP_CD);
	
create table END_TRAN_LN_T (
    	FDOC_NBR VARCHAR2(14) NOT NULL ,
	FDOC_LN_TYP_CD VARCHAR2(1) NOT NULL,
	FDOC_LN_NBR NUMBER(7) NOT NULL,
	KEMID VARCHAR2(10) NOT NULL,
	ETRAN_CD VARCHAR2(9) NOT NULL,
	TRAN_LN_DESC VARCHAR2(40),
	TRAN_IP_IND_CD VARCHAR2(1) NOT NULL,
	TRAN_AMT NUMBER(19,2) NOT NULL,
	CORPUS_IND VARCHAR2(1) DEFAULT 'N' NOT NULL,
	TRAN_UNITS NUMBER(16,4), 
	LN_PSTD VARCHAR2(1) DEFAULT 'N' NOT NULL,
	OBJ_ID VARCHAR2(36) NOT NULL,
	VER_NBR NUMBER(8, 0) DEFAULT 1 NOT NULL,
	PRIMARY KEY (FDOC_NBR, FDOC_LN_TYP_CD, FDOC_LN_NBR)
);


ALTER TABLE END_TRAN_LN_T ADD CONSTRAINT END_TRAN_LN_TR1 FOREIGN KEY (FDOC_NBR)
	REFERENCES END_TRAN_DOC_T (FDOC_NBR);

ALTER TABLE END_TRAN_LN_T ADD CONSTRAINT END_TRAN_LN_TR2 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);
	
ALTER TABLE END_TRAN_LN_T ADD CONSTRAINT END_TRAN_LN_TR3 FOREIGN KEY (ETRAN_CD)
	REFERENCES END_ETRAN_CD_T (ETRAN_CD);

ALTER TABLE END_TRAN_LN_T ADD CONSTRAINT END_TRAN_LN_TR4 FOREIGN KEY (TRAN_IP_IND_CD)
	REFERENCES END_IP_IND_T (IP_IND_CD);
	
	
create table END_TRAN_SEC_T (
    	FDOC_NBR VARCHAR2(14) NOT NULL,
	SEC_LN_TYP_CD VARCHAR2(1) NOT NULL,
	SEC_ID VARCHAR2(9) NOT NULL,
	SEC_REGIS_CD VARCHAR2(4) NOT NULL,
	OBJ_ID VARCHAR2(36) NOT NULL,
	VER_NBR NUMBER(8, 0) DEFAULT 1 NOT NULL,
	PRIMARY KEY (FDOC_NBR, SEC_LN_TYP_CD)
);

ALTER TABLE END_TRAN_SEC_T ADD CONSTRAINT END_TRAN_SEC_TR1 FOREIGN KEY (FDOC_NBR)
	REFERENCES END_TRAN_DOC_T (FDOC_NBR);

ALTER TABLE END_TRAN_SEC_T ADD CONSTRAINT END_TRAN_SEC_TR2 FOREIGN KEY (SEC_ID)
	REFERENCES END_SEC_T (SEC_ID);

ALTER TABLE END_TRAN_SEC_T ADD CONSTRAINT END_TRAN_SEC_TR3 FOREIGN KEY (SEC_REGIS_CD)
	REFERENCES END_REGIS_CD_T (REGIS_CD);


create table END_TRAN_HLDG_LOT_T (
    	FDOC_NBR VARCHAR2(14) NOT NULL,
	FDOC_LN_NBR NUMBER(7) NOT NULL,
	FDOC_LN_TYP_CD VARCHAR2(1) NOT NULL,
	TRAN_HLDG_LT_NBR NUMBER(4) NOT NULL,
	LOT_UNITS NUMBER(16,4) NOT NULL,
	LOT_HLDG_COST NUMBER(19,2),
	LOT_LT_GAIN_LOSS NUMBER(19,2),
	LOT_ST_GAIN_LOSS NUMBER(19,2),
	OBJ_ID VARCHAR2(36) NOT NULL,
	VER_NBR NUMBER(8, 0) DEFAULT 1 NOT NULL,
	PRIMARY KEY (FDOC_NBR, FDOC_LN_NBR, FDOC_LN_TYP_CD, TRAN_HLDG_LT_NBR)
);

ALTER TABLE END_TRAN_HLDG_LOT_T ADD CONSTRAINT END_TRAN_HLDG_LOT_TR1 FOREIGN KEY (FDOC_NBR,FDOC_LN_NBR,FDOC_LN_TYP_CD)
	REFERENCES END_TRAN_LN_T (FDOC_NBR,FDOC_LN_NBR,FDOC_LN_TYP_CD);


	
