create table CA_ACCT_AUTO_CREATE_DFLT_T (
    FIN_COA_CD VARCHAR2(2) NOT NULL,
    ACCOUNT_NBR VARCHAR2(7) NOT NULL,
    ACCOUNT_NM VARCHAR2(40), 
    KC_UNIT VARCHAR2(1), 
	KC_UNIT_NAME VARCHAR2(1), 
	ACCT_PSTL_CD VARCHAR2(20), 
	ACCT_CITY_NM VARCHAR2(25), 
    ACCT_STATE_CD VARCHAR2(2),
    ACCT_STREET_ADDR VARCHAR2(30), 
    ACCT_OFF_CMP_IND VARCHAR2(1),
   	ACCT_TYP_CD VARCHAR2(2), 
   	ACCT_PHYS_CMP_CD(2),
   	SUB_FUND_GRP_CD VARCHAR2(5), 
   	ACCT_FRNG_BNFT_CD VARCHAR2(1),
    RPTS_TO_FIN_COA_CD VARCHAR2(2), 
   	FRNG_BNFT_ACCT_NMBR VARCHAR2(7),
 	FIN_HGH_ED_FUNC_CD VARCHAR2(4), 
    ACCT_FSC_OFC_UID VARCHAR2(40), 
    ACCT_SPVSR_UNVL_ID VARCHAR2(40), 
    ACCT_MGR_UNVL_ID VARCHAR2(40), 
    ORG_CD VARCHAR2(4), 
    CONT_FIN_COA_CD VARCHAR2(2), 
    CONT_ACCOUNT_NBR VARCHAR2(7), 
    INCOME_FIN_COA_CD VARCHAR2(2), 
    INCOME_ACCOUNT_NBR VARCHAR2(7), 
    BDGT_REC_LVL_CD VARCHAR2(1), 
    ACCT_SF_CD VARCHAR2(1), 
    ACCT_PND_SF_CD VARCHAR2(1),
    FIN_EXT_ENC_SF_CD VARCHAR2(1),
    FIN_INT_ENC_SF_CD VARCHAR2(1),
    FIN_PRE_ENC_SF_CD VARCHAR2(1),
    FIN_OBJ_PRSCTRL_CD VARCHAR2(1),
    ICR_FIN_COA_CD VARCHAR2(2), 
    ICR_ACCOUNT_NBR VARCHAR2(7), 
    CG_ACCT_RESP_ID NUMBER(2,0),
    ACCT_ICR_TYP_CD VARCHAR2(2),
    ACCT_CLOSED_IND VARCHAR2(1),
    OBJ_ID VARCHAR2(36) default 'Y' NOT NULL,
    VER_NBR NUMBER(8,0) NOT NULL,
);

ALTER TABLE CA_ACCT_AUTO_CREATE_DFLT_T ADD CONSTRAINT CA_ACCT_AUTO_CREATE_DFLT_PK (FIN_COA_CD,ACCOUNT_NBR);

ALTER TABLE CA_CHART_T add Constraint CA_ACCT_AUTO_CREATE_DFLT_TR1 FOREIGN KEY (reportsToChartOfAccountsCode)
	REFERENCES (fringeBenefitsChartOfAccount);
ALTER TABLE CA_CHART_T add Constraint CA_ACCT_AUTO_CREATE_DFLT_TR2 FOREIGN KEY (chartOfAccountsCode)
	REFERENCES (chartOfAccounts);
ALTER TABLE CA_ORG_T add Constraint CA_ACCT_AUTO_CREATE_DFLT_TR3 FOREIGN KEY (chartOfAccountsCode,organizationCode)
	REFERENCES (organization);
ALTER TABLE CA_ACCOUNT_TYPE_T add Constraint CA_ACCT_AUTO_CREATE_DFLT_TR4 FOREIGN KEY (accountTypeCode)
	REFERENCES (accountType);
ALTER TABLE CA_SUB_FUND_GRP_T add Constraint CA_ACCT_AUTO_CREATE_DFLT_TR5 FOREIGN KEY (subFundGroupCode)
	REFERENCES (subFundGroup);
ALTER TABLE CA_HIGHR_ED_FUNC_T add Constraint CA_ACCT_AUTO_CREATE_DFLT_TR6 FOREIGN KEY (financialHigherEdFunctionCd)
	REFERENCES (financialHigherEdFunction);
ALTER TABLE CA_CHART_T add Constraint CA_ACCT_AUTO_CREATE_DFLT_TR7 FOREIGN KEY (continuationFinChrtOfAcctCd)
	REFERENCES (continuationChartOfAccount);
ALTER TABLE CA_ACCOUNT_T add Constraint CA_ACCT_AUTO_CREATE_DFLT_TR8 FOREIGN KEY (continuationFinChrtOfAcctCd,continuationAccountNumber)
	REFERENCES (continuationAccount);
ALTER TABLE CA_CHART_T add Constraint CA_ACCT_AUTO_CREATE_DFLT_TR9 FOREIGN KEY (incomeStreamFinancialCoaCode)
	REFERENCES (incomeStreamChartOfAccounts);
ALTER TABLE CA_ACCOUNT_T add Constraint CA_ACCT_AUTO_CREATE_DFLT_TR10 FOREIGN KEY (incomeStreamFinancialCoaCode,incomeStreamAccountNumber)
	REFERENCES (incomeStreamAccount);
ALTER TABLE CA_ICR_TYPE_T add Constraint CA_ACCT_AUTO_CREATE_DFLT_TR11 FOREIGN KEY (acctIndirectCostRcvyTypeCd)
	REFERENCES (acctIndirectCostRcvyType);
ALTER TABLE CA_CHART_T add Constraint CA_ACCT_AUTO_CREATE_DFLT_TR12 FOREIGN KEY (indirectCostRcvyFinCoaCode)
	REFERENCES (indirectCostRcvyChartOfAccounts);
ALTER TABLE CA_ACCOUNT_T add Constraint CA_ACCT_AUTO_CREATE_DFLT_TR13 FOREIGN KEY (indirectCostRcvyFinCoaCode,indirectCostRecoveryAcctNbr)
	REFERENCES (indirectCostRecoveryAcct);
ALTER TABLE CA_ACCT_SF_T add Constraint CA_ACCT_AUTO_CREATE_DFLT_TR14 FOREIGN KEY (accountSufficientFundsCode)
	REFERENCES (sufficientFundsCode);
ALTER TABLE CA_ACCT_DESC_T add Constraint CA_ACCT_AUTO_CREATE_DFLT_TR15 FOREIGN KEY (chartOfAccountsCode,accountNumber)
	REFERENCES (accountDescription);
