UPDATE END_KEMID_FND_SRC_T SET FND_SRC_ADTNL_DTA=NULL;

SELECT count(*) FROM END_HLDG_HIST_T WHERE EXISTS (SELECT END_SEC_T.SEC_ID FROM END_SEC_T WHERE END_SEC_T.SEC_ID=END_HLDG_HIST_T.SEC_ID AND END_SEC_T.SEC_CLS_CD='580');

DELETE FROM END_HLDG_HIST_T WHERE EXISTS (SELECT END_SEC_T.SEC_ID FROM END_SEC_T WHERE END_SEC_T.SEC_ID=END_HLDG_HIST_T.SEC_ID AND END_SEC_T.SEC_CLS_CD='580');

SELECT count(*) FROM END_HLDG_TAX_LOT_T WHERE EXISTS (SELECT END_SEC_T.SEC_ID FROM END_SEC_T WHERE END_SEC_T.SEC_ID=END_HLDG_TAX_LOT_T.SEC_ID AND END_SEC_T.SEC_CLS_CD='580');

DELETE FROM END_HLDG_TAX_LOT_T WHERE EXISTS (SELECT END_SEC_T.SEC_ID FROM END_SEC_T WHERE END_SEC_T.SEC_ID=END_HLDG_TAX_LOT_T.SEC_ID AND END_SEC_T.SEC_CLS_CD='580');

SELECT count(*) FROM END_CRNT_TAX_LOT_BAL_T WHERE EXISTS (SELECT END_SEC_T.SEC_ID FROM END_SEC_T WHERE END_SEC_T.SEC_ID=END_CRNT_TAX_LOT_BAL_T.SEC_ID AND END_SEC_T.SEC_CLS_CD='580');

DELETE FROM END_CRNT_TAX_LOT_BAL_T WHERE EXISTS (SELECT END_SEC_T.SEC_ID FROM END_SEC_T WHERE END_SEC_T.SEC_ID=END_CRNT_TAX_LOT_BAL_T.SEC_ID AND END_SEC_T.SEC_CLS_CD='580');

DELETE FROM END_SEC_T WHERE END_SEC_T.SEC_CLS_CD='580';
