-- 1

CREATE TABLE END_ENDOW_ACCT_LINES_T (
FDOC_NBR VARCHAR2(14) NOT NULL,
FDOC_LINE_NBR NUMBER(7 , 0) NOT NULL,
FDOC_LN_TYP_CD VARCHAR2(1) NOT NULL,
OBJ_ID VARCHAR2(36) NOT NULL,
VER_NBR NUMBER(8 , 0) DEFAULT 1 NOT NULL,
FIN_COA_CD VARCHAR2(2),
ACCOUNT_NBR VARCHAR2(7),
FDOC_POST_YR NUMBER(4 , 0),
FIN_OBJECT_CD VARCHAR2(4),
FDOC_LINE_AMT NUMBER(19 , 2),
SUB_ACCT_NBR VARCHAR2(5),
FIN_SUB_OBJ_CD VARCHAR2(3),
PROJECT_CD VARCHAR2(10),
ORG_REFERENCE_ID VARCHAR2(8)
);

ALTER TABLE END_ENDOW_ACCT_LINES_T ADD CONSTRAINT ENDOW_ACCT_LINES_TP1 PRIMARY KEY (FDOC_NBR, FDOC_LINE_NBR, FDOC_LN_TYP_CD);

ALTER TABLE END_ENDOW_ACCT_LINES_T ADD CONSTRAINT ENDOW_ACCT_LINES_TR2 FOREIGN KEY (PROJECT_CD)
REFERENCES CA_PROJECT_T (PROJECT_CD);

ALTER TABLE END_ENDOW_ACCT_LINES_T ADD CONSTRAINT ENDOW_ACCT_LINES_TR4 FOREIGN KEY (FDOC_POST_YR, FIN_COA_CD, FIN_OBJECT_CD)
REFERENCES CA_OBJECT_CODE_T (UNIV_FISCAL_YR, FIN_COA_CD, FIN_OBJECT_CD);

ALTER TABLE END_ENDOW_ACCT_LINES_T ADD CONSTRAINT ENDOW_ACCT_LINES_TR3 FOREIGN KEY (FDOC_POST_YR, FIN_COA_CD, ACCOUNT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD)
REFERENCES CA_SUB_OBJECT_CD_T (UNIV_FISCAL_YR, FIN_COA_CD, ACCOUNT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD);

ALTER TABLE END_ENDOW_ACCT_LINES_T ADD CONSTRAINT ENDOW_ACCT_LINES_TR6 FOREIGN KEY (FIN_COA_CD)
REFERENCES CA_CHART_T (FIN_COA_CD);

ALTER TABLE END_ENDOW_ACCT_LINES_T ADD CONSTRAINT ENDOW_ACCT_LINES_TR7 FOREIGN KEY (FIN_COA_CD, ACCOUNT_NBR)
REFERENCES CA_ACCOUNT_T (FIN_COA_CD, ACCOUNT_NBR);

ALTER TABLE END_ENDOW_ACCT_LINES_T ADD CONSTRAINT ENDOW_ACCT_LINES_TR5 FOREIGN KEY (FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR)
REFERENCES CA_SUB_ACCT_T (FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR);

--2

ALTER TABLE END_TRAN_DOC_T ADD FDOC_NXT_SRC_ACCT_LN_NBR NUMBER(7,0);
ALTER TABLE END_TRAN_DOC_T ADD FDOC_NXT_TAR_ACCT_LN_NBR NUMBER(7,0);
