alter table END_ENDOW_ACCT_LINES_T drop constraint ENDOW_ACCT_LINES_TR3;
alter table END_ENDOW_ACCT_LINES_T drop constraint ENDOW_ACCT_LINES_TR4;
alter table END_ENDOW_ACCT_LINES_T rename constraint ENDOW_ACCT_LINES_TR6 to ENDOW_ACCT_LINES_TR3;
alter table END_ENDOW_ACCT_LINES_T rename constraint ENDOW_ACCT_LINES_TR7 to ENDOW_ACCT_LINES_TR4;

alter table END_ENDOW_ACCT_LINES_T drop column FDOC_POST_YR;


create table END_REC_CSH_XFT_T (
      XFR_NBR VARCHAR2(14) NOT NULL,
      SRC_KEMID VARCHAR2(10) NOT NULL,
      TRAN_DOC_TYP_CD VARCHAR2(5) NOT NULL,
      SRC_ETRAN_CD VARCHAR2(9) NOT NULL,
      SRC_LN_DESC VARCHAR2(40),
      SRC_IP_IND_CD VARCHAR2(1) NOT NULL,
      FREQ_CD     VARCHAR2(4) NOT NULL,
      NXT_PROC_DT DATE NOT NULL,
      LST_PROC_DT DATE,
      ROW_ACTV_IND VARCHAR2(1) NOT NULL,
      OBJ_ID VARCHAR2(36) NOT NULL,
      VER_NBR NUMBER(8, 0) DEFAULT 1 NOT NULL,
      PRIMARY KEY (XFR_NBR, SRC_KEMID)
);

ALTER TABLE END_REC_CSH_XFT_T ADD CONSTRAINT END_REC_CSH_XFT_TR1 FOREIGN KEY (SRC_KEMID) REFERENCES END_KEMID_T (KEMID);
ALTER TABLE END_REC_CSH_XFT_T ADD CONSTRAINT END_REC_CSH_XFT_TR2 FOREIGN KEY (SRC_ETRAN_CD) REFERENCES END_ETRAN_CD_T (ETRAN_CD);
ALTER TABLE END_REC_CSH_XFT_T ADD CONSTRAINT END_REC_CSH_XFT_TR3 FOREIGN KEY (SRC_IP_IND_CD) REFERENCES END_IP_IND_T (IP_IND_CD);
ALTER TABLE END_REC_CSH_XFT_T ADD CONSTRAINT END_REC_CSH_XFT_TR4 FOREIGN KEY (FREQ_CD) REFERENCES END_FREQ_CD_T (FREQ_CD);

create table END_REC_CSH_XFT_KEMID_TGT_T (
      XFR_NBR VARCHAR2(14) NOT NULL,
      SRC_KEMID VARCHAR2(10) NOT NULL,
      TGT_SEQ_NBR VARCHAR2(14) NOT NULL,
      TGT_KEMID VARCHAR2(10) NOT NULL,
      TGT_ETRAN_CD VARCHAR2(9) NOT NULL,
      TGT_LN_DESC VARCHAR2(40),
      TGT_IP_IND_CD VARCHAR2(1) NOT NULL,
      TGT_AMT NUMBER(19,2) DEFAULT 0.00,
      TGT_PCT NUMBER(3,2) DEFAULT 0.00,
      TGT_USE_ETRAN_CD VARCHAR2(9),
      ROW_ACTV_IND VARCHAR2(1) NOT NULL,
      OBJ_ID VARCHAR2(36) NOT NULL,
      VER_NBR NUMBER(8, 0) DEFAULT 1 NOT NULL,
      PRIMARY KEY (XFR_NBR, SRC_KEMID, TGT_SEQ_NBR)
);

ALTER TABLE END_REC_CSH_XFT_KEMID_TGT_T ADD CONSTRAINT END_REC_CSH_XFT_KEMID_TGT_TR1 FOREIGN KEY (XFR_NBR, SRC_KEMID) REFERENCES END_REC_CSH_XFT_T (XFR_NBR, SRC_KEMID);
ALTER TABLE END_REC_CSH_XFT_KEMID_TGT_T ADD CONSTRAINT END_REC_CSH_XFT_KEMID_TGT_TR2 FOREIGN KEY (TGT_KEMID) REFERENCES END_KEMID_T (KEMID);
ALTER TABLE END_REC_CSH_XFT_KEMID_TGT_T ADD CONSTRAINT END_REC_CSH_XFT_KEMID_TGT_TR3 FOREIGN KEY (TGT_ETRAN_CD) REFERENCES END_ETRAN_CD_T (ETRAN_CD);
ALTER TABLE END_REC_CSH_XFT_KEMID_TGT_T ADD CONSTRAINT END_REC_CSH_XFT_KEMID_TGT_TR4 FOREIGN KEY (TGT_IP_IND_CD) REFERENCES END_IP_IND_T (IP_IND_CD);
ALTER TABLE END_REC_CSH_XFT_KEMID_TGT_T ADD CONSTRAINT END_REC_CSH_XFT_KEMID_TGT_TR5 FOREIGN KEY (TGT_USE_ETRAN_CD) REFERENCES END_ETRAN_CD_T (ETRAN_CD);

create table END_REC_CSH_XFT_GL_TGT_T (
      XFR_NBR VARCHAR2(14) NOT NULL,
      SRC_KEMID VARCHAR2(10) NOT NULL,
      TGT_SEQ_NBR VARCHAR2(14) NOT NULL,
      TGT_FIN_COA_CD VARCHAR2(2) NOT NULL,
      TGT_ACCT_NBR VARCHAR2(7) NOT NULL,
      TGT_SUB_ACCT_NBR VARCHAR2(5),
      TGT_FIN_OBJ_CD VARCHAR2(4) NOT NULL,
      TGT_SUB_OBJ_CD VARCHAR2(10),
      TGT_PROJECT_CD VARCHAR2(10),
      TGT_FDOC_LN_AMT NUMBER(19,2) DEFAULT 0.00,
      TGT_PCT NUMBER(3,2) DEFAULT 0.00,
      TGT_USE_ETRAN_CD VARCHAR2(9),
      ROW_ACTV_IND VARCHAR2(1) NOT NULL,
      OBJ_ID VARCHAR2(36) NOT NULL,
      VER_NBR NUMBER(8, 0) DEFAULT 1 NOT NULL,
      PRIMARY KEY (XFR_NBR, SRC_KEMID, TGT_SEQ_NBR)
);

ALTER TABLE END_REC_CSH_XFT_GL_TGT_T ADD CONSTRAINT END_REC_CSH_XFT_GL_TGT_TR1 FOREIGN KEY (XFR_NBR, SRC_KEMID) REFERENCES END_REC_CSH_XFT_T (XFR_NBR, SRC_KEMID);
ALTER TABLE END_REC_CSH_XFT_GL_TGT_T ADD CONSTRAINT END_REC_CSH_XFT_GL_TGT_TR2 FOREIGN KEY (TGT_FIN_COA_CD) REFERENCES CA_CHART_T (FIN_COA_CD);
ALTER TABLE END_REC_CSH_XFT_GL_TGT_T ADD CONSTRAINT END_REC_CSH_XFT_GL_TGT_TR3 FOREIGN KEY (TGT_FIN_COA_CD, TGT_ACCT_NBR) REFERENCES CA_ACCOUNT_T (FIN_COA_CD, ACCOUNT_NBR); 
ALTER TABLE END_REC_CSH_XFT_GL_TGT_T ADD CONSTRAINT END_REC_CSH_XFT_GL_TGT_TR4 FOREIGN KEY (TGT_FIN_COA_CD, TGT_ACCT_NBR, TGT_SUB_ACCT_NBR) REFERENCES CA_SUB_ACCT_T (FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR); 
ALTER TABLE END_REC_CSH_XFT_GL_TGT_T ADD CONSTRAINT END_REC_CSH_XFT_GL_TGT_TR5 FOREIGN KEY (TGT_PROJECT_CD) REFERENCES CA_PROJECT_T (PROJECT_CD); 
ALTER TABLE END_REC_CSH_XFT_GL_TGT_T ADD CONSTRAINT END_REC_CSH_XFT_GL_TGT_TR6 FOREIGN KEY (TGT_USE_ETRAN_CD) REFERENCES END_ETRAN_CD_T (ETRAN_CD);

CREATE TABLE END_PENDING_TRAN_DOC_T (
FDOC_NBR VARCHAR2(14) NOT NULL,
   DOC_TYP_NM VARCHAR2(64) NOT NULL,
APPROVED_DT DATE NOT NULL,
   VER_NBR NUMBER(8,0) DEFAULT 1 NOT NULL,
OBJ_ID VARCHAR2(36) NOT NULL,
PRIMARY KEY (FDOC_NBR)
);

ALTER TABLE END_PENDING_TRAN_DOC_T ADD CONSTRAINT END_PENDING_TRAN_DOC_TR1 FOREIGN KEY (FDOC_NBR)
REFERENCES KRNS_DOC_HDR_T (DOC_HDR_ID); 

alter table END_TRAN_HLDG_LOT_T drop constraint END_TRAN_HLDG_LOT_TR2; 

