ALTER TABLE FP_DV_NRA_TAX_T ADD ( SPCL_W4_INC_AMT decimal(19,2) ); 
ALTER TABLE FP_DV_NRA_TAX_T ADD ( USAID_DIEM_IND varchar2(1) ); 
ALTER TABLE FP_DV_NRA_TAX_T ADD ( INC_TAX_EXMPT_CD_OTHR_IND varchar2(1) ); 
ALTER TABLE FP_DV_NRA_TAX_T ADD ( NQI_CUST_TAX_ID varchar2(50) );