ALTER TABLE END_TRAN_ARCHV_T MODIFY TRAN_ETRAN_CD VARCHAR2(9) NULL;
ALTER TABLE END_TRAN_ARCHV_T MODIFY TRAN_INC_CSH_AMT NUMBER(19,2) NULL;
ALTER TABLE END_TRAN_ARCHV_T MODIFY TRAN_PRIN_CSH_AMT NUMBER(19,2) NULL;
ALTER TABLE END_TRAN_ARCHV_SEC_T MODIFY TRAN_SEC_REGIS_CD VARCHAR2(4) NULL; 