ALTER TABLE END_FEE_MTHD_T RENAME COLUMN FEE_BY_TRAN_TYP TO FEE_BY_TRAN_DOC_TYP;

ALTER TABLE END_FEE_MTHD_T ADD (FEE_MIN_THRSHLD NUMBER(4,2)) ;

CREATE TABLE END_FEE_TRAN_DOC_TYP_T (
FEE_MTHD VARCHAR2(12) NOT NULL,
DOC_TYP_NM VARCHAR2(64) NOT NULL,
INCL VARCHAR2(1) DEFAULT 'Y' NOT NULL,
OBJ_ID VARCHAR2(36) NOT NULL,
VER_NBR NUMBER(8 , 0) DEFAULT 1 NOT NULL
);

ALTER TABLE END_FEE_TRAN_DOC_TYP_T ADD CONSTRAINT END_FEE_TRAN_DOC_TYP_PK PRIMARY KEY (FEE_MTHD, DOC_TYP_NM); 

ALTER TABLE END_FEE_TRAN_DOC_TYP_T ADD CONSTRAINT END_FEE_TRAN_DOC_TYP_TR1 FOREIGN KEY (FEE_MTHD)
REFERENCES END_FEE_MTHD_T (FEE_MTHD);


DROP TABLE END_FEE_TRAN_TYP_T; 