-- This script should be run against the Rice schema before exporting it to the KFS master datasource.

DROP TABLE ACCT_DD_ATTR_DOC
/
DROP TABLE BK_ADDRESS_T
/
DROP TABLE BK_ADDRESS_TYP_T
/
DROP TABLE BK_AUTHOR_ACCOUNT_T
/
DROP TABLE BK_AUTHOR_T
/
DROP TABLE BK_BOOK_AUTHOR_T
/
DROP TABLE BK_BOOK_T
/
DROP TABLE BK_BOOK_TYP_T
/
DROP TABLE BK_ORDER_DOC_T
/
DROP TABLE BK_ORDER_ENTRY_T
/
DROP TABLE KR_KIM_TEST_BO
/
DROP TABLE TRAV_DOC_2_ACCOUNTS
/
DROP TABLE TRV_ACCT
/
DROP TABLE TRV_ACCT_EXT
/
DROP TABLE TRV_ACCT_FO
/
DROP TABLE TRV_ACCT_TYPE
/
DROP TABLE TRV_ACCT_USE_RT_T
/
DROP TABLE TRV_ATT_SAMPLE
/
DROP TABLE TRV_DOC_2
/
DROP TABLE TRV_DOC_ACCT
/
DROP TABLE TRV_MULTI_ATT_SAMPLE
/
DROP TABLE TST_SEARCH_ATTR_INDX_TST_DOC_T
/
DROP SEQUENCE BK_ADDRESS_ID_S
/
DROP SEQUENCE BK_AUTHOR_ID_S
/
DROP SEQUENCE BK_BOOK_ID_S
/
DROP SEQUENCE BK_ORDER_ENTRY_S
/
DROP SEQUENCE TRV_FO_ID_S
/
DROP TABLE KREW_HLP_T
/
DROP SEQUENCE KREW_HLP_S
/
UPDATE krim_perm_t SET nm = REPLACE( nm, 'Apprive', 'Approve' ) WHERE nm LIKE '%Apprive%'
/
DELETE FROM krcr_nmspc_t WHERE nm IN ( 'KR-RULE-TEST', 'KR-SAP' )
/
DELETE FROM krcr_cmpnt_set_t
/
DELETE FROM krcr_drvd_cmpnt_t
/
DELETE FROM krew_attr_defn_t WHERE nmspc_cd = 'KR-SAP'
COMMIT
/

