insert into KREW_RTE_NODE_INSTN_T (RTE_NODE_INSTN_ID, DOC_HDR_ID, RTE_NODE_ID, BRCH_ID, PROC_RTE_NODE_INSTN_ID, ACTV_IND, CMPLT_IND, INIT_IND, VER_NBR)
values (21, 21, 21, 21, null, 0, 1, 0, 2);

insert into KREW_RTE_NODE_INSTN_T (RTE_NODE_INSTN_ID, DOC_HDR_ID, RTE_NODE_ID, BRCH_ID, PROC_RTE_NODE_INSTN_ID, ACTV_IND, CMPLT_IND, INIT_IND, VER_NBR)
values (22, 22, 22, 22, null, 0, 1, 0, 2);

insert into KREW_RTE_NODE_INSTN_T (RTE_NODE_INSTN_ID, DOC_HDR_ID, RTE_NODE_ID, BRCH_ID, PROC_RTE_NODE_INSTN_ID, ACTV_IND, CMPLT_IND, INIT_IND, VER_NBR)
values (23, 23, 23, 23, null, 0, 1, 0, 2);
