insert into pur_po_cptl_ast_loc_t (CPTL_AST_LOC_ID, OBJ_ID, VER_NBR, CPTL_AST_SYS_ID, CPTL_AST_ITM_QTY, CAMPUS_CD, CPTL_AST_OFF_CMP_IND, BLDG_CD, BLDG_ROOM_NBR, CPTL_AST_LN1_ADDR, CPTL_AST_CTY_NM, CPTL_AST_ST_CD, CPTL_AST_PSTL_CD, CPTL_AST_CNTRY_CD)
values ('1300', 'ED15F1F6-6B7B-D459-BCD8-6590FDAD3EB1', 2, '1102', 3, 'BL', 'N', 'BL001', '009', null, null, null, null, null);

insert into pur_po_cptl_ast_loc_t (CPTL_AST_LOC_ID, OBJ_ID, VER_NBR, CPTL_AST_SYS_ID, CPTL_AST_ITM_QTY, CAMPUS_CD, CPTL_AST_OFF_CMP_IND, BLDG_CD, BLDG_ROOM_NBR, CPTL_AST_LN1_ADDR, CPTL_AST_CTY_NM, CPTL_AST_ST_CD, CPTL_AST_PSTL_CD, CPTL_AST_CNTRY_CD)
values ('1301', 'ED15F1F6-6B7B-D459-BCD8-6590FDAD3EB2', 1, '1103', 2, 'BL', 'Y', null, null, '2700 Broadway', 'Lansing','MI','44555', null);
