insert into pur_po_cptl_ast_sys_t (CPTL_AST_SYS_ID, OBJ_ID, VER_NBR, FDOC_NBR, CPTL_AST_SYS_DESC, CPTLAST_NOTRCVD_CUR_FSCLYR_IND, CPTLAST_TYP_CD, CPTL_AST_MFR_NM, CPTL_AST_MDL_DESC, CPTL_AST_NTE_TXT, CPTL_AST_CNT_AST_NBR)
values ('1100', 'ED15F1F6-6B7B-D459-BCD8-6390FDAD3EA1', 2, null, null,'N', null, null, null, null,null);

insert into pur_po_cptl_ast_sys_t (CPTL_AST_SYS_ID, OBJ_ID, VER_NBR, FDOC_NBR, CPTL_AST_SYS_DESC, CPTLAST_NOTRCVD_CUR_FSCLYR_IND, CPTLAST_TYP_CD, CPTL_AST_MFR_NM, CPTL_AST_MDL_DESC, CPTL_AST_NTE_TXT, CPTL_AST_CNT_AST_NBR)
values ('1101', 'ED15F1F6-6B7B-D459-BCD8-6490FDAD3EB1', 2, null, null, 'N', null, null, null, null, null);

insert into pur_po_cptl_ast_sys_t (CPTL_AST_SYS_ID, OBJ_ID, VER_NBR, FDOC_NBR, CPTL_AST_SYS_DESC, CPTLAST_NOTRCVD_CUR_FSCLYR_IND, CPTLAST_TYP_CD, CPTL_AST_MFR_NM, CPTL_AST_MDL_DESC, CPTL_AST_NTE_TXT, CPTL_AST_CNT_AST_NBR)
values ('1102', 'ED15F1F6-6B7B-D459-BCD8-6490FDAD3EC1', 2, null, null, 'N', null, null, null, null, null);

insert into pur_po_cptl_ast_sys_t (CPTL_AST_SYS_ID, OBJ_ID, VER_NBR, FDOC_NBR, CPTL_AST_SYS_DESC, CPTLAST_NOTRCVD_CUR_FSCLYR_IND, CPTLAST_TYP_CD, CPTL_AST_MFR_NM, CPTL_AST_MDL_DESC, CPTL_AST_NTE_TXT, CPTL_AST_CNT_AST_NBR)
values ('1103', 'ED15F1F6-6B7B-D459-BCD8-6490FDAD3ED1', 2, null, null, 'N', null, null, null, null, null);