insert into pur_po_itm_t (FDOC_NBR, PO_ITM_ID, OBJ_ID, VER_NBR, ITM_LN_NBR, ITM_TYP_CD, ITM_UOM_CD, ITM_ORD_QTY, ITM_INV_TOT_QTY, ITM_INV_TOT_AMT, ITM_CATLG_NBR, ITM_RCVD_TOT_QTY, ITM_DESC, ITM_UNIT_PRC, ITM_OSTND_ENC_QTY, ITM_OSTND_ENC_AMT, ITM_AUX_PART_ID, ITM_ACTV_IND, PUR_COMM_CD, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, ITM_DMGED_TOT_QTY)
values ('21', 211, 'D7DE33EA-1269-BA06-0DD2-CC5210AC92A1', 8, 1, 'ITEM','UN', 3.00, 0.00, 0.00, null, 0.00, 'Laptop', 6000.0000, 3.00, 18000.00,null, 'Y', null, null, null, 'N', 0.00);

insert into pur_po_itm_t (FDOC_NBR, PO_ITM_ID, OBJ_ID, VER_NBR, ITM_LN_NBR, ITM_TYP_CD, ITM_UOM_CD, ITM_ORD_QTY, ITM_INV_TOT_QTY, ITM_INV_TOT_AMT, ITM_CATLG_NBR, ITM_RCVD_TOT_QTY, ITM_DESC, ITM_UNIT_PRC, ITM_OSTND_ENC_QTY, ITM_OSTND_ENC_AMT, ITM_AUX_PART_ID, ITM_ACTV_IND, PUR_COMM_CD, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, ITM_DMGED_TOT_QTY)
values ('21', 212, '799AEA08-2613-24C2-D8D5-8A96E9E0D0A2', 8, 2, 'ITEM', 'PR', 2.00, 0.00, 0.00, null, 0.00, 'Desk & Chair', 7000.0000, 2.00, 14000.00,null, 'Y', null, null, null, 'N', 0.00);

insert into pur_po_itm_t (FDOC_NBR, PO_ITM_ID, OBJ_ID, VER_NBR, ITM_LN_NBR, ITM_TYP_CD, ITM_UOM_CD, ITM_ORD_QTY, ITM_INV_TOT_QTY, ITM_INV_TOT_AMT, ITM_CATLG_NBR, ITM_RCVD_TOT_QTY, ITM_DESC, ITM_UNIT_PRC, ITM_OSTND_ENC_QTY, ITM_OSTND_ENC_AMT, ITM_AUX_PART_ID, ITM_ACTV_IND, PUR_COMM_CD, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, ITM_DMGED_TOT_QTY)
values ('21', 213, '190EBBC0-C3BB-56D2-D44B-B84AABEEA3A3', 8, null, 'FRHT',null, null, 0.00, 0.00, null, 0.00, 'USPS', 750.0000, null, 750.00, null, 'Y', null, null, null, 'N', null);

insert into pur_po_itm_t (FDOC_NBR, PO_ITM_ID, OBJ_ID, VER_NBR, ITM_LN_NBR, ITM_TYP_CD, ITM_UOM_CD, ITM_ORD_QTY, ITM_INV_TOT_QTY, ITM_INV_TOT_AMT, ITM_CATLG_NBR, ITM_RCVD_TOT_QTY, ITM_DESC, ITM_UNIT_PRC, ITM_OSTND_ENC_QTY, ITM_OSTND_ENC_AMT, ITM_AUX_PART_ID, ITM_ACTV_IND, PUR_COMM_CD, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, ITM_DMGED_TOT_QTY)
values ('21', 214, '39FF6B74-9D58-E88D-5152-7A169C6CD3A4', 8, null, 'SPHD', null, null, 0.00, 0.00, null, 0.00, 'USPS', 250.0000, null, 250.00, null, 'Y', null, null, null, 'N', null);
------------------------------------------------------

insert into pur_po_itm_t (FDOC_NBR, PO_ITM_ID, OBJ_ID, VER_NBR, ITM_LN_NBR, ITM_TYP_CD, ITM_UOM_CD, ITM_ORD_QTY, ITM_INV_TOT_QTY, ITM_INV_TOT_AMT, ITM_CATLG_NBR, ITM_RCVD_TOT_QTY, ITM_DESC, ITM_UNIT_PRC, ITM_OSTND_ENC_QTY, ITM_OSTND_ENC_AMT, ITM_AUX_PART_ID, ITM_ACTV_IND, PUR_COMM_CD, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, ITM_DMGED_TOT_QTY)
values ('22', 221, 'D7DE33EA-1269-BA06-0DD2-CC5210AC92B1', 8, 1, 'ITEM', 'UN', 3.00, 0.00, 0.00, null, 0.00, 'Laptop', 6000.0000, 3.00, 18000.00, null, 'Y', null, null, null, 'N', 0.00);

insert into pur_po_itm_t (FDOC_NBR, PO_ITM_ID, OBJ_ID, VER_NBR, ITM_LN_NBR, ITM_TYP_CD, ITM_UOM_CD, ITM_ORD_QTY, ITM_INV_TOT_QTY, ITM_INV_TOT_AMT, ITM_CATLG_NBR, ITM_RCVD_TOT_QTY, ITM_DESC, ITM_UNIT_PRC, ITM_OSTND_ENC_QTY, ITM_OSTND_ENC_AMT, ITM_AUX_PART_ID, ITM_ACTV_IND, PUR_COMM_CD, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, ITM_DMGED_TOT_QTY)
values ('22', 222, '799AEA08-2613-24C2-D8D5-8A96E9E0D0B2', 8, 2, 'ITEM', 'PR', 2.00, 0.00, 0.00, null, 0.00, 'Desk & Chair', 7000.0000, 2.00, 14000.00, null, 'Y', null, null, null, 'N', 0.00);

insert into pur_po_itm_t (FDOC_NBR, PO_ITM_ID, OBJ_ID, VER_NBR, ITM_LN_NBR, ITM_TYP_CD, ITM_UOM_CD, ITM_ORD_QTY, ITM_INV_TOT_QTY, ITM_INV_TOT_AMT, ITM_CATLG_NBR, ITM_RCVD_TOT_QTY, ITM_DESC, ITM_UNIT_PRC, ITM_OSTND_ENC_QTY, ITM_OSTND_ENC_AMT, ITM_AUX_PART_ID, ITM_ACTV_IND, PUR_COMM_CD, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, ITM_DMGED_TOT_QTY)
values ('22', 223, '190EBBC0-C3BB-56D2-D44B-B84AABEEA3B3', 8, null, 'FRHT', null, null, 0.00, 0.00, null, 0.00, 'USPS', 750.0000, null, 750.00, null, 'Y', null, null, null, 'N', null);

insert into pur_po_itm_t (FDOC_NBR, PO_ITM_ID, OBJ_ID, VER_NBR, ITM_LN_NBR, ITM_TYP_CD, ITM_UOM_CD, ITM_ORD_QTY, ITM_INV_TOT_QTY, ITM_INV_TOT_AMT, ITM_CATLG_NBR, ITM_RCVD_TOT_QTY, ITM_DESC, ITM_UNIT_PRC, ITM_OSTND_ENC_QTY, ITM_OSTND_ENC_AMT, ITM_AUX_PART_ID, ITM_ACTV_IND, PUR_COMM_CD, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, ITM_DMGED_TOT_QTY)
values ('22', 224, '39FF6B74-9D58-E88D-5152-7A169C6CD3B4', 8, null, 'SPHD', null, null, 0.00, 0.00, null, 0.00, 'USPS', 250.0000, null, 250.00, null, 'Y', null, null, null, 'N', null);
------------------------------------------------------

insert into pur_po_itm_t (FDOC_NBR, PO_ITM_ID, OBJ_ID, VER_NBR, ITM_LN_NBR, ITM_TYP_CD, ITM_UOM_CD, ITM_ORD_QTY, ITM_INV_TOT_QTY, ITM_INV_TOT_AMT, ITM_CATLG_NBR, ITM_RCVD_TOT_QTY, ITM_DESC, ITM_UNIT_PRC, ITM_OSTND_ENC_QTY, ITM_OSTND_ENC_AMT, ITM_AUX_PART_ID, ITM_ACTV_IND, PUR_COMM_CD, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, ITM_DMGED_TOT_QTY)
values ('23', 231, 'D7DE33EA-1269-BA06-0DD2-CC5210AC92C1', 8, 1, 'ITEM', 'UN', 3.00, 0.00, 0.00, null, 0.00, 'Laptop', 6000.0000, 3.00, 18000.00, null, 'Y', null, null, null, 'N', 0.00);

insert into pur_po_itm_t (FDOC_NBR, PO_ITM_ID, OBJ_ID, VER_NBR, ITM_LN_NBR, ITM_TYP_CD, ITM_UOM_CD, ITM_ORD_QTY, ITM_INV_TOT_QTY, ITM_INV_TOT_AMT, ITM_CATLG_NBR, ITM_RCVD_TOT_QTY, ITM_DESC, ITM_UNIT_PRC, ITM_OSTND_ENC_QTY, ITM_OSTND_ENC_AMT, ITM_AUX_PART_ID, ITM_ACTV_IND, PUR_COMM_CD, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, ITM_DMGED_TOT_QTY)
values ('23', 232, '799AEA08-2613-24C2-D8D5-8A96E9E0D0C2', 8, 2, 'ITEM', 'PR', 2.00, 0.00, 0.00, null, 0.00, 'Desk & Chair', 7000.0000, 2.00, 14000.00, null, 'Y', null, null, null, 'N', 0.00);

insert into pur_po_itm_t (FDOC_NBR, PO_ITM_ID, OBJ_ID, VER_NBR, ITM_LN_NBR, ITM_TYP_CD, ITM_UOM_CD, ITM_ORD_QTY, ITM_INV_TOT_QTY, ITM_INV_TOT_AMT, ITM_CATLG_NBR, ITM_RCVD_TOT_QTY, ITM_DESC,  ITM_UNIT_PRC, ITM_OSTND_ENC_QTY, ITM_OSTND_ENC_AMT, ITM_AUX_PART_ID, ITM_ACTV_IND, PUR_COMM_CD, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, ITM_DMGED_TOT_QTY)
values ('23', 233, '190EBBC0-C3BB-56D2-D44B-B84AABEEA3C3', 8, null, 'FRHT', null, null, 0.00, 0.00, null, 0.00, 'USPS', 750.0000, null, 750.00, null, 'Y', null, null, null, 'N', null);

insert into pur_po_itm_t (FDOC_NBR, PO_ITM_ID, OBJ_ID, VER_NBR, ITM_LN_NBR, ITM_TYP_CD, ITM_UOM_CD, ITM_ORD_QTY, ITM_INV_TOT_QTY, ITM_INV_TOT_AMT, ITM_CATLG_NBR, ITM_RCVD_TOT_QTY, ITM_DESC, ITM_UNIT_PRC, ITM_OSTND_ENC_QTY, ITM_OSTND_ENC_AMT, ITM_AUX_PART_ID, ITM_ACTV_IND, PUR_COMM_CD, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, ITM_DMGED_TOT_QTY)
values ('23', 234, '39FF6B74-9D58-E88D-5152-7A169C6CD3C4', 8, null, 'SPHD', null, null, 0.00, 0.00, null, 0.00, 'USPS', 250.0000, null, 250.00, null, 'Y', null, null, null, 'N', null);
------------------------------------------------------
