CREATE TABLE gl_acct_balances_hist_t (
    UNIV_FISCAL_YR decimal(4,0) NOT NULL,
    FIN_COA_CD varchar(2) NOT NULL,
    ACCOUNT_NBR varchar(7) NOT NULL,
    SUB_ACCT_NBR varchar(5) NOT NULL,
    FIN_OBJECT_CD varchar(4) NOT NULL,
    FIN_SUB_OBJ_CD varchar(3) NOT NULL,
    CURR_BDLN_BAL_AMT decimal(19,2),
    ACLN_ACTLS_BAL_AMT decimal(19,2),
    ACLN_ENCUM_BAL_AMT decimal(19,2),
    PRIMARY KEY(UNIV_FISCAL_YR,FIN_COA_CD,ACCOUNT_NBR,SUB_ACCT_NBR,FIN_OBJECT_CD,FIN_SUB_OBJ_CD)
)
/
ALTER TABLE gl_acct_balances_hist_t
    ADD CONSTRAINT GL_ACCT_BALANCES_HIST_TR4
FOREIGN KEY(UNIV_FISCAL_YR)
REFERENCES fs_option_t(UNIV_FISCAL_YR)
/
ALTER TABLE gl_acct_balances_hist_t
    ADD CONSTRAINT GL_ACCT_BALANCES_HIST_TR3
FOREIGN KEY(FIN_COA_CD)
REFERENCES ca_chart_t(FIN_COA_CD)
/
ALTER TABLE gl_acct_balances_hist_t
    ADD CONSTRAINT GL_ACCT_BALANCES_HIST_TR2
FOREIGN KEY(FIN_COA_CD, ACCOUNT_NBR)
REFERENCES ca_account_t(FIN_COA_CD, ACCOUNT_NBR)
/
ALTER TABLE gl_acct_balances_hist_t
    ADD CONSTRAINT GL_ACCT_BALANCES_HIST_TR1
FOREIGN KEY(UNIV_FISCAL_YR, FIN_COA_CD, FIN_OBJECT_CD)
REFERENCES ca_object_code_t(UNIV_FISCAL_YR, FIN_COA_CD, FIN_OBJECT_CD)
/

drop table FS_UNIVERSAL_USR_T
/