update krew_doc_typ_t set lbl='Role' where doc_typ_nm='IdentityManagementRoleDocument'
/

CREATE TABLE KRIM_PND_DLGN_T ( 
    FDOC_NBR        VARCHAR2(14)  NOT NULL,
    DLGN_ID     	VARCHAR2(40) NOT NULL,
    ROLE_ID     	VARCHAR2(40) NOT NULL,
    OBJ_ID      	VARCHAR2(36) NOT NULL,
    VER_NBR     	NUMBER(8,0) DEFAULT 1 NOT NULL,
    KIM_TYP_ID  	VARCHAR2(40) NULL,
    DLGN_TYP_CD    	VARCHAR2(100) NOT NULL,
    ACTV_IND    	VARCHAR2(1) DEFAULT 'Y' NULL,
    PRIMARY KEY(DLGN_ID,FDOC_NBR)
)
/
CREATE TABLE KRIM_PND_DLGN_MBR_T
(
    FDOC_NBR        VARCHAR2(14) NOT NULL,
    DLGN_MBR_ID  	VARCHAR2(40) NOT NULL,
    OBJ_ID      	VARCHAR2(36) NOT NULL,
    VER_NBR     	NUMBER(8,0)  DEFAULT 1 NOT NULL,
    DLGN_ID      	VARCHAR2(40) NOT NULL,
    MBR_ID   		VARCHAR2(40),
    MBR_NM			VARCHAR2(40),
    MBR_TYP_CD		VARCHAR2(40) NOT NULL,
    ACTV_IND    	VARCHAR2(1)  DEFAULT 'Y' NULL,
    ACTV_FRM_DT  	DATE NULL,
    ACTV_TO_DT  	DATE NULL,
    PRIMARY KEY(DLGN_MBR_ID,FDOC_NBR)
)
/
CREATE TABLE KRIM_PND_DLGN_MBR_ATTR_DATA_T ( 
    FDOC_NBR          VARCHAR2(14)  NOT NULL,
    ATTR_DATA_ID      	VARCHAR2(40) NOT NULL,
    OBJ_ID            	VARCHAR2(36) NOT NULL,
    VER_NBR           	NUMBER(8,0) DEFAULT 1 NOT NULL,
    TARGET_PRIMARY_KEY	VARCHAR2(40) NULL,
    KIM_TYP_ID        	VARCHAR2(40) NULL,
    KIM_ATTR_DEFN_ID  	VARCHAR2(40) NULL,
    ATTR_VAL          	VARCHAR2(400) NULL,
    ACTV_IND    	VARCHAR2(1) DEFAULT 'Y' NULL,
    EDIT_FLAG    	VARCHAR2(1) DEFAULT 'N' NULL,
    PRIMARY KEY(ATTR_DATA_ID,FDOC_NBR)
)
/
