alter table KREN_CHNL_T DROP COLUMN OBJ_ID
/
alter table KREN_CNTNT_TYP_T DROP COLUMN OBJ_ID
/
alter table KREN_PRODCR_T DROP COLUMN OBJ_ID
/
alter table KREN_PRIO_T DROP COLUMN OBJ_ID
/
alter table KREN_RVWER_T DROP COLUMN OBJ_ID
/
