ALTER TABLE krns_sesn_doc_t ADD (OBJ_ID VARCHAR2(36));
ALTER TABLE krns_sesn_doc_t ADD (VER_NBR NUMBER(8) DEFAULT 0);
ALTER TABLE KRSB_MSG_QUE_T RENAME COLUMN SVC_NMSPC TO APPL_ID;
ALTER TABLE KRNS_DOC_HDR_T MODIFY (FDOC_DESC varchar2(255));
