-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: ./updates/update.xml
-- Ran at: 6/15/10 10:50 AM
-- Against: kuldemo@jdbc:mysql://localhost:3306/kuldemo
-- LiquiBase version: 1.9.5
-- *********************************************************************



-- Changeset updates/2010-06-15-5759-1-KRNS_PARM_T.xml::5759-1-1::Muddu::(MD5Sum: 1a46df5ce1addd1872ed61894e5191a9)
-- Need to add system parameter to the master source for Kuali Coeus Integration for Account create process
INSERT INTO `KRNS_PARM_T` (`VER_NBR`, `PARM_DESC_TXT`, `OBJ_ID`, `PARM_NM`, `PARM_DTL_TYP_CD`, `CONS_CD`, `APPL_NMSPC_CD`, `TXT`, `PARM_TYP_CD`, `NMSPC_CD`) VALUES (1, 'This parameter defines the workflow action that will be taken on an account document automatically generated by an integrated research admin system The possible parameter values are save, submit, and blanketApprove', uuid(), 'RESEARCH_ADMIN_AUTO_CREATE_ACCOUNT_WORKFLOW_ACTION', 'Account', 'A', 'KFS', 'save', 'CONFG', 'KFS-COA');


-- Release Database Lock

-- Release Database Lock

