/*
 * Copyright 2008 The Kuali Foundation.
 * 
 * Licensed under the Educational Community License, Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.opensource.org/licenses/ecl1.php
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.kuali.workflow.attribute;

import java.util.Set;

/**
 * This is a marker interface. It is used to flag the document as having used a
 * Set of <RoutingData> for routing. Routing is driven
 * by the field names. THESE METHODS MUST GET AND SET THE SET NAMED routingInfo 
 * IN THE IMPLEMENTING CLASS. 
 * 
 * Less verbose, and more
 * readable, XML will usually be generated by the document if each RoutingData 
 * element has a unique RoutingTypes within the document.
 * This is not a requirement and the RoutingData object has features that insure
 * that duplicate (@ link RoutingType} information
 * doesn't cause routing problems.
 */

public interface GenericRoutingInfo {
   
    public Set getRoutingInfo();

    public void setRoutingInfo(Set <RoutingData> routingInfo);
    
    public void populateRoutingInfo();

}

