update krns_parm_t set parm_typ_cd = 'CONFG' where parm_typ_cd = 'AUTH'
/
delete from krns_parm_typ_t where parm_typ_cd in ('AUTH', 'HELP')
/

DELETE FROM KREW_DOC_TYP_PLCY_RELN_T where DOC_PLCY_NM='PRE_APPROVE'
/

RENAME SEQ_DOCUMENT_TYPE_ATTRIBUTE TO KREW_DOC_TYP_ATTR_S
/
RENAME SEQ_ROUTE_QUEUE TO KRSB_MSG_QUE_S
/
drop sequence SEQ_TRANSACTION_TST
/
RENAME SEQ_RULE_EXPR TO KREW_RULE_EXPR_S
/

delete from krim_ext_id_typ_t where ext_id_typ_cd <> 'TAX'
/

update krim_typ_t set nm = 'Organization: Optionally Hierarchical' where kim_typ_id = '28'
/
update krim_typ_t set nm = 'Account Organization Hierarchy', SRVC_NM = 'budgetConstructionAccountOrganizationHierarchyRoleTypeService' where kim_typ_id = '6'
/

INSERT INTO KRIM_ROLE_PERM_T(ROLE_PERM_ID, OBJ_ID, VER_NBR, ROLE_ID, PERM_ID, ACTV_IND) 
    VALUES('555', sys_guid(), 1, '62', '136', 'Y')
/

update krim_role_t set role_nm = 'System User' where role_id = '62'
/
update krim_role_t set role_nm = 'System User' where role_id = '90'
/

delete from krim_role_mbr_t where role_id = '22' and mbr_typ_cd = 'P' and mbr_id = '6162502038'
/

INSERT INTO KRIM_PERM_T(PERM_ID, OBJ_ID, VER_NBR, PERM_TMPL_ID, NM, DESC_TXT, ACTV_IND, NMSPC_CD) 
    VALUES('292', sys_guid(), 1, '33', null, null, 'Y', 'KFS-PURAP')
/
INSERT INTO KRIM_PERM_ATTR_DATA_T(ATTR_DATA_ID, OBJ_ID, VER_NBR, TARGET_PRIMARY_KEY, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL) 
    VALUES('421', sys_guid(), 1, '292', '15', '1', 'electronicInvoiceInputFileType')
/
INSERT INTO KRIM_ROLE_PERM_T(ROLE_PERM_ID, OBJ_ID, VER_NBR, ROLE_ID, PERM_ID, ACTV_IND) 
    VALUES('556', sys_guid(), 1, '22', '292', 'Y')
/

update krim_role_mbr_t set mbr_id = '35' where role_id = '44' and mbr_id = '34'
/

INSERT INTO KRIM_RSP_T(RSP_ID, OBJ_ID, VER_NBR, RSP_TMPL_ID, NM, DESC_TXT, ACTV_IND, NMSPC_CD)
    VALUES('109', sys_guid(), 1, '1', null, null, 'Y', 'KFS-PURAP')
/ 
INSERT INTO KRIM_RSP_ATTR_DATA_T(ATTR_DATA_ID, OBJ_ID, VER_NBR, TARGET_PRIMARY_KEY, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL)
    VALUES('400', sys_guid(), 1, '109', '7', '16', 'Management')
/
INSERT INTO KRIM_RSP_ATTR_DATA_T(ATTR_DATA_ID, OBJ_ID, VER_NBR, TARGET_PRIMARY_KEY, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL)
    VALUES('401', sys_guid(), 1, '109', '7', '13', 'ElectronicInvoiceRejectDocument')
/
INSERT INTO KRIM_RSP_ATTR_DATA_T(ATTR_DATA_ID, OBJ_ID, VER_NBR, TARGET_PRIMARY_KEY, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL)
    VALUES('402', sys_guid(), 1, '109', '7', '41', 'false')
/
INSERT INTO KRIM_RSP_ATTR_DATA_T(ATTR_DATA_ID, OBJ_ID, VER_NBR, TARGET_PRIMARY_KEY, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL)
    VALUES('403', sys_guid(), 1, '109', '7', '40', 'true')
/
INSERT INTO KRIM_ROLE_RSP_T(ROLE_RSP_ID, OBJ_ID, VER_NBR, ROLE_ID, RSP_ID, ACTV_IND)
    VALUES('1109', sys_guid(), 1, '22', '109', 'Y')
/
INSERT INTO KRIM_ROLE_RSP_ACTN_T(ROLE_RSP_ACTN_ID, OBJ_ID, VER_NBR, ACTN_TYP_CD, PRIORITY_NBR, ACTN_PLCY_CD, ROLE_MBR_ID, ROLE_RSP_ID, IGNORE_PREV_IND)
    VALUES('134', sys_guid(), 1, 'A', null, 'F', '*', '1109', 'Y')
/

update krim_role_rsp_t set role_id = '26' where role_rsp_id = '1088'
/
delete from krim_role_t where role_id = '78'
/

INSERT INTO KRIM_PERM_T(PERM_ID, OBJ_ID, VER_NBR, PERM_TMPL_ID, NM, DESC_TXT, ACTV_IND, NMSPC_CD) 
    VALUES('293', sys_guid(), 1, '31', null, null, 'Y', 'KFS-PURAP')
/
INSERT INTO KRIM_PERM_ATTR_DATA_T(ATTR_DATA_ID, OBJ_ID, VER_NBR, TARGET_PRIMARY_KEY, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL) 
    VALUES('422', sys_guid(), 1, '293', '14', '10', 'requestVendorCreditMemoHold')
/
INSERT INTO KRIM_ROLE_PERM_T(ROLE_PERM_ID, OBJ_ID, VER_NBR, ROLE_ID, PERM_ID, ACTV_IND) 
    VALUES('557', sys_guid(), 1, '22', '293', 'Y')
/
INSERT INTO KRIM_PERM_T(PERM_ID, OBJ_ID, VER_NBR, PERM_TMPL_ID, NM, DESC_TXT, ACTV_IND, NMSPC_CD) 
    VALUES('294', sys_guid(), 1, '31', null, null, 'Y', 'KFS-PURAP')
/
INSERT INTO KRIM_PERM_ATTR_DATA_T(ATTR_DATA_ID, OBJ_ID, VER_NBR, TARGET_PRIMARY_KEY, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL) 
    VALUES('423', sys_guid(), 1, '294', '14', '10', 'vendorCreditMemoHoldRemoval')
/
INSERT INTO KRIM_ROLE_PERM_T(ROLE_PERM_ID, OBJ_ID, VER_NBR, ROLE_ID, PERM_ID, ACTV_IND) 
    VALUES('558', sys_guid(), 1, '29', '294', 'Y')
/
INSERT INTO KRIM_ROLE_PERM_T(ROLE_PERM_ID, OBJ_ID, VER_NBR, ROLE_ID, PERM_ID, ACTV_IND) 
    VALUES('559', sys_guid(), 1, '86', '294', 'Y')
/

INSERT INTO KRIM_PERM_T(PERM_ID, OBJ_ID, VER_NBR, PERM_TMPL_ID, NM, DESC_TXT, ACTV_IND, NMSPC_CD) 
    VALUES('295', sys_guid(), 1, '1', 'Use Organization Salary Setting', null, 'Y', 'KFS-BC')
/
INSERT INTO KRIM_ROLE_PERM_T(ROLE_PERM_ID, OBJ_ID, VER_NBR, ROLE_ID, PERM_ID, ACTV_IND) 
    VALUES('562', sys_guid(), 1, '81', '295', 'Y')
/
INSERT INTO KRIM_PERM_T(PERM_ID, OBJ_ID, VER_NBR, PERM_TMPL_ID, NM, DESC_TXT, ACTV_IND, NMSPC_CD) 
    VALUES('296', sys_guid(), 1, '1', 'Edit Account Funding', null, 'Y', 'KFS-BC')
/
INSERT INTO KRIM_PERM_RQRD_ATTR_T(PERM_RQRD_ATTR_ID, OBJ_ID, VER_NBR, PERM_ID, KIM_ATTR_DEFN_ID, ACTV_IND) 
    VALUES('120', sys_guid(), 1, '296', '22', 'Y')
/
INSERT INTO KRIM_PERM_RQRD_ATTR_T(PERM_RQRD_ATTR_ID, OBJ_ID, VER_NBR, PERM_ID, KIM_ATTR_DEFN_ID, ACTV_IND) 
    VALUES('121', sys_guid(), 1, '296', '23', 'Y')
/
INSERT INTO KRIM_ROLE_PERM_T(ROLE_PERM_ID, OBJ_ID, VER_NBR, ROLE_ID, PERM_ID, ACTV_IND) 
    VALUES('560', sys_guid(), 1, '75', '296', 'Y')
/
INSERT INTO KRIM_PERM_T(PERM_ID, OBJ_ID, VER_NBR, PERM_TMPL_ID, NM, DESC_TXT, ACTV_IND, NMSPC_CD) 
    VALUES('297', sys_guid(), 1, '1', 'View Account Funding Amounts', null, 'Y', 'KFS-BC')
/
INSERT INTO KRIM_ROLE_PERM_T(ROLE_PERM_ID, OBJ_ID, VER_NBR, ROLE_ID, PERM_ID, ACTV_IND) 
    VALUES('561', sys_guid(), 1, '80', '297', 'Y')
/

update krew_doc_typ_t set lbl = 'Line Item Receiving Status' where DOC_TYP_NM = 'LineItemReceivingStatusMaintenanceDocument'
/
update krew_doc_typ_t set lbl = 'Payee ACH Account' where DOC_TYP_NM = 'PayeeACHAccountMaintenanceDocument'
/
update krew_doc_typ_t set HELP_DEF_URL = (select help_def_url from krew_doc_typ_t where doc_typ_nm = 'PaymentRequestDocument' and CUR_IND = 0) where doc_typ_nm = 'PaymentRequestDocument' and cur_ind = 1
/

update krew_doc_typ_t set lbl = 'Routing Rule' where doc_typ_nm = 'RoutingRuleDocument'
/
update krew_doc_typ_t set lbl = 'Document Type' where doc_typ_nm = 'DocumentTypeDocument'
/
update krew_doc_typ_t set lbl = 'Person' where doc_typ_nm = 'IdentityManagementPersonDocument'
/

CREATE TABLE FS_DOC_TYP_CD_T ( 
    FS_DOC_TYP_CD               	VARCHAR2(4) NOT NULL,
    OBJ_ID                     	VARCHAR2(36) NOT NULL,
    VER_NBR                    	NUMBER(8,0) NOT NULL,
    DOC_TYP_NM                 	VARCHAR2(255) NULL,
    ACTIVE_IND                 	VARCHAR2(1) NULL,
    TRNSCTN_SCRBR_OFFST_GEN_IND	VARCHAR2(1) NULL, 
    CONSTRAINT FS_DOC_TYP_CD_TP1 PRIMARY KEY(FS_DOC_TYP_CD)
)
/
ALTER TABLE FS_DOC_TYP_CD_T
    ADD ( CONSTRAINT FS_DOC_TYP_CD_TC0 UNIQUE (OBJ_ID))
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('BFNC', '61AD9AB218C20FCCE0404F8189D8515D', 1, 'FunctionControlCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('BFYC', '61AD9AB218C30FCCE0404F8189D8515D', 1, 'FiscalYearFunctionControlMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMQS', '61AD9AB218C40FCCE0404F8189D8515D', 1, 'PurchaseOrderQuoteStatusMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('OFAC', '61AD9AB218C50FCCE0404F8189D8515D', 1, 'OffsetAccountMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMRF', '61AD9AB218C60FCCE0404F8189D8515D', 1, 'RecurringPaymentFrequencyMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMFS', '61AD9AB218C70FCCE0404F8189D8515D', 1, 'FundingSourceMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('FSDT', '61B5BAB1F437EDCFE0404F8189D84C47', 1, 'GeneralLedgerInputTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMLI', '61CF0F3EA193FCC1E0404F8189D81CE1', 1, 'LineItemReceivingStatusMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('UFUN', '61AD9AB2186C0FCCE0404F8189D8515D', 1, 'UniversityBudgetOfficeFunctionMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('CATY', '61AD9AB2186D0FCCE0404F8189D8515D', 1, 'CustomerAddressTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMST', '61AD9AB2186E0FCCE0404F8189D8515D', 1, 'ShippingTitleMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ASTA', '61AD9AB2186F0FCCE0404F8189D8515D', 1, 'AssetStatusMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('YEBT', '61AD9AB218700FCCE0404F8189D8515D', 1, 'YearEndBenefitExpenseTransferDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ACTC', '61AD9AB218710FCCE0404F8189D8515D', 1, 'AccountingChangeCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('CTRL', '61AD9AB218720FCCE0404F8189D8515D', 1, 'CashControlDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('DVET', '61AD9AB218730FCCE0404F8189D8515D', 1, 'TravelExpenseTypeCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMCL', '61AD9AB218740FCCE0404F8189D8515D', 1, 'PurchaseOrderContractLanguageMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('OADF', '61AD9AB218760FCCE0404F8189D8515D', 1, 'OrganizationAccountingDefaultMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('OBJC', '61AD9AB218770FCCE0404F8189D8515D', 1, 'ObjectConsolidationMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('NPC', '61AD9AB218780FCCE0404F8189D8515D', 1, 'NonPersonnelCategoryMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('CLOS', '61AD9AB218790FCCE0404F8189D8515D', 1, 'CFDACloseDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('BTYP', '61AD9AB2187A0FCCE0404F8189D8515D', 1, 'BalanceTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('GDLG', '61AD9AB2187B0FCCE0404F8189D8515D', 1, 'AccountDelegateGlobalMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMTC', '61AD9AB2187C0FCCE0404F8189D8515D', 1, 'PaymentChangeCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('CDS', '61AD9AB2187D0FCCE0404F8189D8515D', 1, 'CashDrawerMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMPT', '61AD9AB2187E0FCCE0404F8189D8515D', 1, 'PhoneTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('SB', '61AD9AB2187F0FCCE0404F8189D8515D', 1, 'ServiceBillingDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('DPRM', '61AD9AB218800FCCE0404F8189D8515D', 1, 'AssetDepreciationMethodMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('SOBJ', '61AD9AB218810FCCE0404F8189D8515D', 1, 'SubObjectCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('APP', '61AD9AB218820FCCE0404F8189D8515D', 1, 'PaymentApplicationDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMPA', '61AD9AB218830FCCE0404F8189D8515D', 1, 'PaymentTermTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ARPS', '61AD9AB218840FCCE0404F8189D8515D', 1, 'EffortCertificationPeriodStatusCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMED', '61AD9AB218850FCCE0404F8189D8515D', 1, 'PaymentMediumMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ARPG', '61AD9AB218860FCCE0404F8189D8515D', 1, 'EffortCertificationReportEarnPaygroupMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMUM', '61AD9AB218870FCCE0404F8189D8515D', 1, 'UnitOfMeasureMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ORGC', '61AD9AB218880FCCE0404F8189D8515D', 1, 'OrganizationReversionCategoryMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('CASM', '61AD9AB218890FCCE0404F8189D8515D', 1, 'AssetMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('DI', '61AD9AB2188A0FCCE0404F8189D8515D', 1, 'DistributionOfIncomeAndExpenseDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('KBD', '61AD9AB2188B0FCCE0404F8189D8515D', 1, 'BudgetDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('AGCY', '61AD9AB2188C0FCCE0404F8189D8515D', 1, 'AgencyMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('IRAD', '61AD9AB2188D0FCCE0404F8189D8515D', 1, 'ItemReasonAddedMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('OTYP', '61AD9AB2188E0FCCE0404F8189D8515D', 1, 'ObjectTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('AFUN', '61AD9AB2188F0FCCE0404F8189D8515D', 1, 'AICPAFunctionMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('COBJ', '61AD9AB218900FCCE0404F8189D8515D', 1, 'AssetObjectCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMSD', '61AD9AB218910FCCE0404F8189D8515D', 1, 'SupplierDiversityMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ARTY', '61AD9AB218920FCCE0404F8189D8515D', 1, 'EffortCertificationReportTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('MOTD', '61AD9AB218930FCCE0404F8189D8515D', 1, 'MessageOfTheDayMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PO', '61AD9AB218940FCCE0404F8189D8515D', 1, 'PurchaseOrderDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('COAT', '61AD9AB218950FCCE0404F8189D8515D', 1, 'ChartMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PRST', '61AD9AB218960FCCE0404F8189D8515D', 1, 'ProposalStatusMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('DVIC', '61AD9AB218970FCCE0404F8189D8515D', 1, 'TaxIncomeClassCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ABNK', '61AD9AB218990FCCE0404F8189D8515D', 1, 'ACHBankMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('INVR', '61AD9AB2189A0FCCE0404F8189D8515D', 1, 'InvoiceRecurrenceMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMCT', '61AD9AB2189C0FCCE0404F8189D8515D', 1, 'ContactTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ACON', '61AD9AB2189D0FCCE0404F8189D8515D', 1, 'AssetConditionMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('DVOT', '61AD9AB2189E0FCCE0404F8189D8515D', 1, 'OwnershipTypeCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('DVPR', '61AD9AB2189F0FCCE0404F8189D8515D', 1, 'PaymentReasonCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ROOM', '61AD9AB218A00FCCE0404F8189D8515D', 1, 'RoomMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMVT', '61AD9AB218A10FCCE0404F8189D8515D', 1, 'VendorTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('GORV', '61AD9AB218A20FCCE0404F8189D8515D', 1, 'OrganizationReversionGlobalMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('TRTP', '61AD9AB218A30FCCE0404F8189D8515D', 1, 'TaxRegionTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('SOPT', '61AD9AB218A40FCCE0404F8189D8515D', 1, 'SystemOptionsMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('AD', '61AD9AB218A50FCCE0404F8189D8515D', 1, 'AdvanceDepositDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('RCEN', '61AD9AB218A60FCCE0404F8189D8515D', 1, 'ResponsibilityCenterMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('GDES', '61AD9AB218A70FCCE0404F8189D8515D', 1, 'GrantDescriptionMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('OFSD', '61AD9AB218A80FCCE0404F8189D8515D', 1, 'OffsetDefinitionMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMQT', '61AD9AB218A90FCCE0404F8189D8515D', 1, 'PurchaseOrderQuoteListMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('FFC', '61AD9AB218AA0FCCE0404F8189D8515D', 1, 'FederalFundedCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMTM', '61AD9AB218AB0FCCE0404F8189D8515D', 1, 'PurchaseOrderTransmissionMethodMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMCO', '61AD9AB218AC0FCCE0404F8189D8515D', 1, 'ContractManagerMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMOP', '61AD9AB218AD0FCCE0404F8189D8515D', 1, 'OrganizationParameterMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('DVCC', '61AD9AB218AE0FCCE0404F8189D8515D', 1, 'TaxControlCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('CSFO', '61AD9AB218AF0FCCE0404F8189D8515D', 1, 'CalculatedSalaryFoundationTrackerOverrideMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMCP', '61AD9AB218B00FCCE0404F8189D8515D', 1, 'CampusParameterMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('RRT', '61AD9AB218B10FCCE0404F8189D8515D', 1, 'ResearchRiskTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('QNT', '61AD9AB218B20FCCE0404F8189D8515D', 1, 'QuestionTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('DEPR', '61AD9AB218B30FCCE0404F8189D8515D', 1, 'AssetDepreciationDocument', 'N', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('POC', '61AD9AB218B40FCCE0404F8189D8515D', 1, 'PurchaseOrderCloseDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ASST', '61AD9AB218B50FCCE0404F8189D8515D', 1, 'AssetTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PTAG', '61AD9AB218B60FCCE0404F8189D8515D', 1, 'PretagMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMPR', '61AD9AB218B70FCCE0404F8189D8515D', 1, 'PaymentRequestStatusMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('KEYW', '61AD9AB218B80FCCE0404F8189D8515D', 1, 'KeywordMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMCA', '61AD9AB218B90FCCE0404F8189D8515D', 1, 'CarrierMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('NPSC', '61AD9AB218BA0FCCE0404F8189D8515D', 1, 'NonPersonnelSubCategoryMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ARPT', '61AD9AB218BB0FCCE0404F8189D8515D', 1, 'EffortCertificationReportDefinitionMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PRJT', '61AD9AB218BE0FCCE0404F8189D8515D', 1, 'ProjectTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ADEL', '61AD9AB218BF0FCCE0404F8189D8515D', 1, 'AccountDelegateMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PAAT', '61AD9AB218C00FCCE0404F8189D8515D', 1, 'PayeeACHAccountMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('CCTY', '61AD9AB218C10FCCE0404F8189D8515D', 1, 'CreditCardTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('DPRC', '61AD9AB218160FCCE0404F8189D8515D', 1, 'AssetDepreciationConventionMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ORGR', '61AD9AB218170FCCE0404F8189D8515D', 1, 'OrganizationReversionMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('AWRD', '61AD9AB218180FCCE0404F8189D8515D', 1, 'AwardMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('POA', '61AD9AB218190FCCE0404F8189D8515D', 1, 'PurchaseOrderAmendmentDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ATYP', '61AD9AB2181A0FCCE0404F8189D8515D', 1, 'AccountTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('SFC', '61AD9AB2181B0FCCE0404F8189D8515D', 1, 'SufficientFundsCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ARSI', '61AD9AB2181C0FCCE0404F8189D8515D', 1, 'SystemInformationMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('BCAL', '61AD9AB2181D0FCCE0404F8189D8515D', 1, 'BenefitsCalculationMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('RSTA', '61AD9AB2181E0FCCE0404F8189D8515D', 1, 'RestrictedStatusMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('TAXR', '61AD9AB2181F0FCCE0404F8189D8515D', 1, 'TaxRegionMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('FGRP', '61AD9AB218200FCCE0404F8189D8515D', 1, 'FundGroupMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PRPS', '61AD9AB218210FCCE0404F8189D8515D', 1, 'PurposeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ACCT', '61AD9AB218220FCCE0404F8189D8515D', 1, 'AccountMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMVC', '61AD9AB218230FCCE0404F8189D8515D', 1, 'PurchaseOrderVendorChoiceMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ICA', '61AD9AB218240FCCE0404F8189D8515D', 1, 'IndirectCostAdjustmentDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('YEGE', '61AD9AB218250FCCE0404F8189D8515D', 1, 'YearEndGeneralErrorCorrectionDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ACHT', '61AD9AB218260FCCE0404F8189D8515D', 1, 'ACHTransactionTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMIT', '61AD9AB218270FCCE0404F8189D8515D', 1, 'ItemTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ST', '61AD9AB218280FCCE0404F8189D8515D', 1, 'SalaryExpenseTransferDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('IB', '61AD9AB2182A0FCCE0404F8189D8515D', 1, 'InternalBillingDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMAT', '61AD9AB2182B0FCCE0404F8189D8515D', 1, 'AddressTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('LLCP', '61AD9AB2182C0FCCE0404F8189D8515D', 1, 'LaborLedgerCorrectionProcessDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('OSTY', '61AD9AB2182E0FCCE0404F8189D8515D', 1, 'ObjectSubTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('POSP', '61AD9AB2182F0FCCE0404F8189D8515D', 1, 'PurchaseOrderSplitDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMPS', '61AD9AB218300FCCE0404F8189D8515D', 1, 'PurchaseOrderStatusMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('LOBJ', '61AD9AB218310FCCE0404F8189D8515D', 1, 'LaborObjectMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('BT', '61AD9AB218320FCCE0404F8189D8515D', 1, 'BenefitExpenseTransferDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMBA', '61AD9AB218330FCCE0404F8189D8515D', 1, 'BillingAddressMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('LOBN', '61AD9AB218340FCCE0404F8189D8515D', 1, 'PositionObjectBenefitMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('DVDL', '61AD9AB218350FCCE0404F8189D8515D', 1, 'DisbursementVoucherDocumentationLocationMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('CR', '61AD9AB218360FCCE0404F8189D8515D', 1, 'CashReceiptDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('CRM', '61AD9AB218380FCCE0404F8189D8515D', 1, 'CustomerCreditMemoDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('BCPS', '61AD9AB218390FCCE0404F8189D8515D', 1, 'BudgetConstructionPositionMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('POV', '61AD9AB2183A0FCCE0404F8189D8515D', 1, 'PurchaseOrderVoidDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('BRL', '61AD9AB2183B0FCCE0404F8189D8515D', 1, 'BudgetRecordingLevelMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('APPT', '61AD9AB2183C0FCCE0404F8189D8515D', 1, 'AppointmentTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('CM', '61AD9AB2183D0FCCE0404F8189D8515D', 1, 'VendorCreditMemoDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('DDT', '61AD9AB2183E0FCCE0404F8189D8515D', 1, 'DueDateTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMTT', '61AD9AB2183F0FCCE0404F8189D8515D', 1, 'AssetTransactionTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('GDLM', '61AD9AB218400FCCE0404F8189D8515D', 1, 'AccountDelegateModelMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PORH', '61AD9AB218410FCCE0404F8189D8515D', 1, 'PurchaseOrderRemoveHoldDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('APRD', '61AD9AB218420FCCE0404F8189D8515D', 1, 'AccountingPeriodMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PATY', '61AD9AB218430FCCE0404F8189D8515D', 1, 'ProposalAwardTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('FFD', '61AD9AB218440FCCE0404F8189D8515D', 1, 'FunctionalFieldDescriptionMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('YETF', '61AD9AB218450FCCE0404F8189D8515D', 1, 'YearEndTransferOfFundsDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('GOBJ', '61AD9AB218460FCCE0404F8189D8515D', 1, 'ObjectCodeGlobalMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMCC', '61AD9AB218470FCCE0404F8189D8515D', 1, 'CommodityCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMAA', '61AD9AB218480FCCE0404F8189D8515D', 1, 'AutoApproveExcludeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('AGTY', '61AD9AB218490FCCE0404F8189D8515D', 1, 'AgencyTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('UDAT', '61AD9AB2184A0FCCE0404F8189D8515D', 1, 'UniversityDateMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('FFUN', '61AD9AB2184B0FCCE0404F8189D8515D', 1, 'FederalFunctionMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMSN', '61AD9AB2184C0FCCE0404F8189D8515D', 1, 'SensitiveDataMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('NPOC', '61AD9AB2184D0FCCE0404F8189D8515D', 1, 'NonPersonnelObjectCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('AA', '61AD9AB2184E0FCCE0404F8189D8515D', 1, 'AssetGlobalMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMRA', '61AD9AB2184F0FCCE0404F8189D8515D', 1, 'ReceivingAddressMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('SFGT', '61AD9AB218500FCCE0404F8189D8515D', 1, 'SubFundGroupTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ASLT', '61AD9AB218510FCCE0404F8189D8515D', 1, 'AssetLocationTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('DBRG', '61AD9AB218520FCCE0404F8189D8515D', 1, 'DisbursementNumberRangeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('GSOB', '61AD9AB218530FCCE0404F8189D8515D', 1, 'SubObjectCodeGlobalMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('OBJL', '61AD9AB218540FCCE0404F8189D8515D', 1, 'ObjectLevelMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMNP', '61AD9AB218550FCCE0404F8189D8515D', 1, 'NegativePaymentRequestApprovalLimitMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('REQS', '61AD9AB218560FCCE0404F8189D8515D', 1, 'RequisitionDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('AR', '61AD9AB218570FCCE0404F8189D8515D', 1, 'AssetRetirementGlobalMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('BCAR', '61AD9AB218580FCCE0404F8189D8515D', 1, 'AccountReportsMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMRS', '61AD9AB218590FCCE0404F8189D8515D', 1, 'RequisitionStatusMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMIR', '61AD9AB2185A0FCCE0404F8189D8515D', 1, 'VendorInactiveReasonMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('INVW', '61AD9AB2185B0FCCE0404F8189D8515D', 1, 'CustomerInvoiceWriteoffDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('LFGR', '61AD9AB2185D0FCCE0404F8189D8515D', 1, 'LetterOfCreditFundGroupMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('GAR', '61AD9AB2185E0FCCE0404F8189D8515D', 1, 'GraduateAssistantRateMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('DVWT', '61AD9AB2185F0FCCE0404F8189D8515D', 1, 'WireChargeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMCS', '61AD9AB218600FCCE0404F8189D8515D', 1, 'PurchaseOrderCostSourceMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('KRFD', '61AD9AB218610FCCE0404F8189D8515D', 1, 'RoutingFormDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('BENT', '61AD9AB218620FCCE0404F8189D8515D', 1, 'BenefitsTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('RPTC', '61AD9AB218630FCCE0404F8189D8515D', 1, 'ReportingCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('RRSN', '61AD9AB218640FCCE0404F8189D8515D', 1, 'AssetRetirementReasonMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMOC', '61AD9AB218650FCCE0404F8189D8515D', 1, 'OwnershipCategoryMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PVEN', '61AD9AB218660FCCE0404F8189D8515D', 1, 'VendorMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('MPAY', '61AD9AB218670FCCE0404F8189D8515D', 1, 'AssetPaymentDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('RTCM', '61AD9AB218150FCCE0404F8189D8515D', 1, 'ResearchTypeCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ACQT', '61AD9AB218680FCCE0404F8189D8515D', 1, 'AssetAcquisitionTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ORTY', '61AD9AB2186A0FCCE0404F8189D8515D', 1, 'OrganizationTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ITYP', '61AD9AB2186B0FCCE0404F8189D8515D', 1, 'IndirectCostRecoveryTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('YEBA', '61AD9AB217C00FCCE0404F8189D8515D', 1, 'YearEndBudgetAdjustmentDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('IICO', '61AD9AB217C10FCCE0404F8189D8515D', 1, 'CustomerInvoiceItemCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('POR', '61AD9AB217C20FCCE0404F8189D8515D', 1, 'PurchaseOrderReopenDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMQL', '61AD9AB217C30FCCE0404F8189D8515D', 1, 'PurchaseOrderQuoteLanguageMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('DSTP', '61AD9AB217C40FCCE0404F8189D8515D', 1, 'DisbursementTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMSP', '61AD9AB217C50FCCE0404F8189D8515D', 1, 'ShippingPaymentTermsMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMSS', '61AD9AB217C60FCCE0404F8189D8515D', 1, 'ShippingSpecialConditionMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ELR', '61AD9AB217C70FCCE0404F8189D8515D', 1, 'EquipmentLoanOrReturnDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('SACC', '61AD9AB217C80FCCE0404F8189D8515D', 1, 'SubAccountMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('BANK', '61AD9AB217C90FCCE0404F8189D8515D', 1, 'BankMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('CUS', '61AD9AB217CA0FCCE0404F8189D8515D', 1, 'CustomerMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ALOC', '61AD9AB217CB0FCCE0404F8189D8515D', 1, 'AssetLocationGlobalMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('OOPT', '61AD9AB217CC0FCCE0404F8189D8515D', 1, 'OrganizationOptionsMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('BLDG', '61AD9AB217CD0FCCE0404F8189D8515D', 1, 'BuildingMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('OBJT', '61AD9AB217CE0FCCE0404F8189D8515D', 1, 'ObjectCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMSY', '61AD9AB217CF0FCCE0404F8189D8515D', 1, 'CapitalAssetSystemTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('DVTC', '61AD9AB217D00FCCE0404F8189D8515D', 1, 'TravelCompanyCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('RCVL', '61AD9AB217D10FCCE0404F8189D8515D', 1, 'LineItemReceivingDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('DVPD', '61AD9AB217D20FCCE0404F8189D8515D', 1, 'TravelPerDiemMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('CMD', '61AD9AB217D30FCCE0404F8189D8515D', 1, 'CashManagementDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMTS', '61AD9AB217D40FCCE0404F8189D8515D', 1, 'PaymentStatusMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('IDCL', '61AD9AB217D50FCCE0404F8189D8515D', 1, 'IndirectCostLookupMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('POPH', '61AD9AB217BE0FCCE0404F8189D8515D', 1, 'PurchaseOrderPaymentHoldDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ICRE', '61AD9AB217BF0FCCE0404F8189D8515D', 1, 'IndirectCostRecoveryRateMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('CCVN', '61AD9AB217D60FCCE0404F8189D8515D', 1, 'CreditCardVendorMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PCDO', '61AD9AB217D70FCCE0404F8189D8515D', 1, 'ProcurementCardDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PROJ', '61AD9AB217D80FCCE0404F8189D8515D', 1, 'ProjectCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('DURA', '61AD9AB217D90FCCE0404F8189D8515D', 1, 'AppointmentFundingDurationMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PREQ', '61AD9AB217DA0FCCE0404F8189D8515D', 1, 'PaymentRequestDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('LLJV', '61AD9AB217DB0FCCE0404F8189D8515D', 1, 'LaborJournalVoucherDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('DV', '61AD9AB217DC0FCCE0404F8189D8515D', 1, 'DisbursementVoucherDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PE', '61AD9AB217DD0FCCE0404F8189D8515D', 1, 'PreEncumbranceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('THLD', '61AD9AB217DE0FCCE0404F8189D8515D', 1, 'ReceivingThresholdMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('DVML', '61AD9AB217DF0FCCE0404F8189D8515D', 1, 'TravelMileageRateMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('SUBC', '61AD9AB217E00FCCE0404F8189D8515D', 1, 'SubContractorMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('CSPR', '61AD9AB217E10FCCE0404F8189D8515D', 1, 'CustomerProfileMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PRSN', '61AD9AB217E20FCCE0404F8189D8515D', 1, 'ContractsAndGrantsRoleCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ACTY', '61AD9AB217E30FCCE0404F8189D8515D', 1, 'BasicAccountingCategoryMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('GEC', '61AD9AB217E40FCCE0404F8189D8515D', 1, 'GeneralErrorCorrectionDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ICRA', '61AD9AB217E50FCCE0404F8189D8515D', 1, 'IndirectCostRecoveryExclusionAccountMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('IINC', '61AD9AB217E60FCCE0404F8189D8515D', 1, 'IntendedIncumbentMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMOT', '61AD9AB217E70FCCE0404F8189D8515D', 1, 'OwnershipTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PORT', '61AD9AB217E80FCCE0404F8189D8515D', 1, 'PurchaseOrderRetransmitDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('FR', '61AD9AB217E90FCCE0404F8189D8515D', 1, 'AssetFabricationMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('CCR', '61AD9AB217EA0FCCE0404F8189D8515D', 1, 'CreditCardReceiptDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ORIG', '61AD9AB217EB0FCCE0404F8189D8515D', 1, 'OriginationCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMSO', '61AD9AB217EC0FCCE0404F8189D8515D', 1, 'RequisitionSourceMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('AT', '61AD9AB217ED0FCCE0404F8189D8515D', 1, 'AssetTransferDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('POGR', '61AD9AB217EE0FCCE0404F8189D8515D', 1, 'PositionObjectGroupMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMDR', '61AD9AB217EF0FCCE0404F8189D8515D', 1, 'DeliveryRequiredDateReasonMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('JV', '61AD9AB217F00FCCE0404F8189D8515D', 1, 'JournalVoucherDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ND', '61AD9AB217F10FCCE0404F8189D8515D', 1, 'NonCheckDisbursementDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ORGN', '61AD9AB217F20FCCE0404F8189D8515D', 1, 'OrganizationMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('AWDS', '61AD9AB217F30FCCE0404F8189D8515D', 1, 'AwardStatusMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMRP', '61AD9AB217F40FCCE0404F8189D8515D', 1, 'RecurringPaymentTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('BA', '61AD9AB217F50FCCE0404F8189D8515D', 1, 'BudgetAdjustmentDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('BCIE', '61AD9AB217F60FCCE0404F8189D8515D', 1, 'BarcodeInventoryErrorDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('CFDA', '61AD9AB217F70FCCE0404F8189D8515D', 1, 'CFDAMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('BCOR', '61AD9AB217F80FCCE0404F8189D8515D', 1, 'OrganizationReportsMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMCM', '61AD9AB217F90FCCE0404F8189D8515D', 1, 'CreditMemoStatusMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('CTY', '61AD9AB217FA0FCCE0404F8189D8515D', 1, 'CustomerTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('RCVC', '61AD9AB217FB0FCCE0404F8189D8515D', 1, 'CorrectionReceivingDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('GACC', '61AD9AB217FC0FCCE0404F8189D8515D', 1, 'AccountGlobalMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('GLCP', '61AD9AB217FD0FCCE0404F8189D8515D', 1, 'GeneralLedgerCorrectionProcessDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ACM', '61AD9AB217FF0FCCE0404F8189D8515D', 1, 'ContractManagerAssignmentDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('BAMD', '61AD9AB218000FCCE0404F8189D8515D', 1, 'BudgetAggregationCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMTP', '61AD9AB218010FCCE0404F8189D8515D', 1, 'PaymentTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('EIRT', '61AD9AB218020FCCE0404F8189D8515D', 1, 'ElectronicInvoiceRejectDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('ACTR', '61AD9AB218030FCCE0404F8189D8515D', 1, 'ACHTransactionCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('SFGR', '61AD9AB218040FCCE0404F8189D8515D', 1, 'SubFundGroupMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('BCRC', '61AD9AB218050FCCE0404F8189D8515D', 1, 'AppointmentFundingReasonCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('HEFN', '61AD9AB218060FCCE0404F8189D8515D', 1, 'HigherEducationFunctionMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PRPL', '61AD9AB218070FCCE0404F8189D8515D', 1, 'ProposalMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PURP', '61AD9AB218080FCCE0404F8189D8515D', 1, 'ProposalPurposeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PMSI', '61AD9AB218090FCCE0404F8189D8515D', 1, 'VendorStipulationMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('YEST', '61AD9AB2180A0FCCE0404F8189D8515D', 1, 'YearEndSalaryExpenseTransferDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('BC', '61AD9AB2180B0FCCE0404F8189D8515D', 1, 'BudgetConstructionDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('DVTX', '61AD9AB2180C0FCCE0404F8189D8515D', 1, 'NonResidentAlienTaxPercentMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('A21', '61AD9AB2180D0FCCE0404F8189D8515D', 1, 'EffortCertificationDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('YEDI', '61AD9AB2180E0FCCE0404F8189D8515D', 1, 'YearEndDistributionOfIncomeAndExpenseDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('PYTP', '61AD9AB2180F0FCCE0404F8189D8515D', 1, 'PayeeTypeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('MTE', '61AD9AB218100FCCE0404F8189D8515D', 1, 'MandatoryTransferEliminationCodeMaintenanceDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('TF', '61AD9AB218110FCCE0404F8189D8515D', 1, 'TransferOfFundsDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('AV', '61AD9AB218120FCCE0404F8189D8515D', 1, 'AuxiliaryVoucherDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('RCVB', '61AD9AB218130FCCE0404F8189D8515D', 1, 'BulkReceivingDocument', 'Y', 'N')
/
INSERT INTO FS_DOC_TYP_CD_T(FS_DOC_TYP_CD, OBJ_ID, VER_NBR, DOC_TYP_NM, ACTIVE_IND, TRNSCTN_SCRBR_OFFST_GEN_IND)
  VALUES('INV', '61AD9AB218140FCCE0404F8189D8515D', 1, 'CustomerInvoiceDocument', 'Y', 'N')
/
drop table krns_doc_typ_t cascade constraints
/
drop table gl_input_typ_t
/
update krew_doc_typ_t set doc_typ_nm = 'FinancialSystemDocumentTypeCodeMaintenanceDocument', lbl = 'Financial System Document Type Code' where doc_typ_nm = 'GeneralLedgerInputTypeMaintenanceDocument'
/
update fs_doc_typ_cd_t set doc_typ_nm = 'FinancialSystemDocumentTypeCodeMaintenanceDocument' where doc_typ_nm = 'GeneralLedgerInputTypeMaintenanceDocument'
/

alter table fs_doc_header_t add (FS_DOC_TYP_CD VARCHAR2(4) NULL)
/
ALTER TABLE fs_doc_header_t
    ADD (CONSTRAINT fs_doc_header_tR1
	FOREIGN KEY(FS_DOC_TYP_CD)
	REFERENCES FS_DOC_TYP_CD_T(FS_DOC_TYP_CD))
/

