insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('A', '"Academic (i.e. GPA, Merit)"', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('AP', '"Academic (i.e. GPA, Merit)--Preference"', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('C', '"County, Area, State, City, Country"', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('CP', '"County, Area, State, City, Country--Preference"', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('D', 'Limits on dollar amount/number of', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('DP', 'Limits on dollar amount/number of--Preference', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('F', 'Faith/Religion', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('FP', 'Faith/Religion--Preference', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('G', 'Gender', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('GP', 'Gender--Preference', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('H', 'High School', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('HP', 'High School--Preference', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('I', 'Indiana Resident', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('IP', 'Indiana Resident--Preference', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('L', 'Leadership', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('LP', 'Leadership--Preference', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('M', 'Marital Status', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('MP', 'Marital Status--Preference', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('N', 'Need', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('NP', 'Need--Preference', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('O', '"Organization (i.e. sorority, fraternity)"', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('OP', '"Organization (i.e. sorority, fraternity)--Preference"', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('Q', 'US Citizen', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('QP', 'US Citizen--Preference', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('R', 'Race', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('RP', 'Race--Preference', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('S', '"Class Standing (i.e. sophomore, junior, etc.)"', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('SP', '"Class Standing (i.e. sophomore, junior, etc.)--Preference"', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('T', 'International Student', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('TP', 'International Student--Preference', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('U', '"Unit (major, minor, discipline specific or program, sport)"', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('UP', '"Unit (major, minor, discipline specific or program, sport)--Preference"', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('X', 'Full-time/Part-time', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('XP', 'Full-time/Part-time--Preference', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('Y', 'Renewable/Non-renewable', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('YP', 'Renewable/Non-renewable--Preference', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('Z', 'Other', 'Y',sys_guid());
insert into END_USE_CRIT_T columns (USE_CRIT_CD, USE_CRIT_DESC, ROW_ACTV_IND, OBJ_ID) values ('ZP', 'Other--Preference', 'Y',sys_guid());
