insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('00100', 'Petty Cash', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('01005', 'Other Trust Bank Accounts', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('01200', 'Money Market Participation', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('01205', 'Money Market Participant Liab', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('01290', 'Separately Held Money Market', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('02020', 'Int Receivable - Sep Held', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('02100', 'Int Receivable - Interfund', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('03050', 'Other Receivables', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('05030', 'Student Loans', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('05035', 'Faculty & Staff Advances', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('05100', 'Notes Receivable - Interfund', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('06000', 'Other Assets', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('10000', 'Common and Preferred Stock', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('10100', 'US Securities - Par', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('10200', 'Corp Bonds - Par', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('10300', 'Tax Exempt - Par', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('10400', 'Mutual Funds', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('10600', 'Outside Managers Cash & Cash Equivalents', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('10700', 'Commercial Paper', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('10900', 'Certificates of Deposit', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('11000', 'Pooled Equity Shares', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('11100', 'PEF - Participant Liability', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('11500', 'Equity Trust Investment Pool', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('11700', 'Pooled Long Term Investment Fund', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('12000', 'Pooled Fixed Income Shares', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('12100', 'PFI - Participant Liability', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('12500', 'Bond Trust Investment Pool', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('13000', 'Real Estate', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('14000', 'Mortgage Contracts', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('15000', 'CSV of Life Insurance', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('17000', 'Alternative Investments', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('22025', 'Legal Fees Payable', 'L', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('22500', 'Damage deposit payable', 'L', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('24000', 'Notes Pay - Compton CRUT', 'L', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('42000', 'Trust Accounts - Interest', 'I', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('42010', 'Money Markets - Interest', 'I', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('42015', 'CDs - Interest', 'I', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('42020', 'Miscellaneous - Interest', 'I', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('42100', 'Stock Dividends', 'I', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('42120', 'US Securities - Interest', 'I', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('42140', 'Corp Bonds - Interest', 'I', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('42160', 'Tax Exempt - Interest', 'I', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('42190', 'Mortgage Contracts - Interest', 'I', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('42200', 'Pooled Equity Dividends', 'I', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('42210', 'Equity TIP Dividends', 'I', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('42270', 'Pooled Long-Term Dividends', 'I', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('42300', 'Pooled Fixed Income Interest', 'I', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('42320', 'Bond TIP Interest', 'I', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('42415', 'Student Loans - Interest', 'I', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('45000', 'Rent Income', 'I', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('45100', 'Interest Income - Interfund', 'I', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('74000', 'Interest Expense', 'E', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('74100', 'Interest Expense - Interfund related to IU', 'E', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('75010', 'PEF - Distrib to Accounts', 'E', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('75020', 'Equity TIP - Distribution to Accounts - ONLY FUND 99', 'E', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('76010', 'PFI - Distrib to Accounts', 'E', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('76020', 'Bond TIP - Distribution to Accounts', 'E', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('78100', 'Pooled Fund Dist. Gain/loss', 'E', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('77000', 'Separately Held Management Fees', 'E', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('10601', 'Negative Cash & Equivalents held by mgrs', 'A', 'Y',sys_guid());
insert into END_ETRAN_CD_T columns (ETRAN_CD, ETRAN_CD_DESC, ETRAN_TYP_CD, ROW_ACTV_IND, OBJ_ID) values ('75720', 'PLTIF - Distribution to Accounts', 'E', 'Y',sys_guid());
