-- Accommodation Type

INSERT INTO TEM_ACCOMM_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('HOTL','Hotel','Y',1,SYS_GUID());

INSERT INTO TEM_ACCOMM_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('HOUS','House','Y',1,SYS_GUID());

INSERT INTO TEM_ACCOMM_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('APTS','Apartment','Y',1,SYS_GUID());

INSERT INTO TEM_ACCOMM_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('DORM','Dormitory','Y',1,SYS_GUID());

INSERT INTO TEM_ACCOMM_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('BARR','Barracks','Y',1,SYS_GUID());

INSERT INTO TEM_ACCOMM_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('CAMP','Camping','Y',1,SYS_GUID());

INSERT INTO TEM_ACCOMM_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('MOTL','Motel','Y',1,SYS_GUID());

INSERT INTO TEM_ACCOMM_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('UNKN','Unknown','Y',1,SYS_GUID());

INSERT INTO TEM_ACCOMM_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('OTHR','Other','Y',1,SYS_GUID());

-- Contact Relationship

INSERT INTO TEM_CONT_REL_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('CWK','Co-worker','Y',1,SYS_GUID());

INSERT INTO TEM_CONT_REL_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('FRD','Friend','Y',1,SYS_GUID());

INSERT INTO TEM_CONT_REL_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('GRP','Grandparent','Y',1,SYS_GUID());

INSERT INTO TEM_CONT_REL_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('OTH','Other','Y',1,SYS_GUID());

INSERT INTO TEM_CONT_REL_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('PRN','Parent','Y',1,SYS_GUID());

INSERT INTO TEM_CONT_REL_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('PAR','Partner','Y',1,SYS_GUID());

INSERT INTO TEM_CONT_REL_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('REL','Relative','Y',1,SYS_GUID());

INSERT INTO TEM_CONT_REL_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('SBL','Sibling','Y',1,SYS_GUID());

INSERT INTO TEM_CONT_REL_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('SPS','Spouse','Y',1,SYS_GUID());

INSERT INTO TEM_CONT_REL_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('NON','None','Y',1,SYS_GUID());

-- Travel Card Type
INSERT INTO TEM_TRVL_CARD_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('CTS','CTS Travel','Y',1,SYS_GUID());

INSERT INTO TEM_TRVL_CARD_TYP_T (CODE,NM,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('CORP','Coporate Travel','Y',1,SYS_GUUID());

-- Traveler Type

INSERT INTO TEM_TRAVELER_TYP_T (CODE,SRC_CODE,NM,ADVANCES_IND,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('EMP','KIM','Employee','Y','Y',1,SYS_GUID());

INSERT INTO TEM_TRAVELER_TYP_T (CODE,SRC_CODE,NM,ADVANCES_IND,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('NON','MANUAL','Non-Employee','N','Y',1,SYS_GUID());

-- Trip Type

INSERT INTO TEM_TRIP_TYP_T (CODE,NM,GEN_ENC_IND,ENC_BAL_TYP,ENC_OBJ_CD,CONT_INFO_REQ_IND,BLANKET_IND,AUTO_TR_LIMIT,USE_PER_DIEM,TA_REQUIRED,PER_DIEM_CALC_METHOD,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('IN','In-State','Y','EX','6000','N','N','0.00','Y','Y','P','Y',1,SYS_GUID());

INSERT INTO TEM_TRIP_TYP_T (CODE,NM,GEN_ENC_IND,ENC_BAL_TYP,ENC_OBJ_CD,CONT_INFO_REQ_IND,BLANKET_IND,AUTO_TR_LIMIT,USE_PER_DIEM,TA_REQUIRED,PER_DIEM_CALC_METHOD,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('OUT','Out of State','Y','EX','6100','N','N','0.00','Y','Y','P','Y',1,SYS_GUID());

INSERT INTO TEM_TRIP_TYP_T (CODE,NM,GEN_ENC_IND,ENC_BAL_TYP,ENC_OBJ_CD,CONT_INFO_REQ_IND,BLANKET_IND,AUTO_TR_LIMIT,USE_PER_DIEM,TA_REQUIRED,PER_DIEM_CALC_METHOD,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('INT','International','Y','EX','6200','Y','N','0.00','Y','Y','P','Y',1,SYS_GUID());

INSERT INTO TEM_TRIP_TYP_T (CODE,NM,GEN_ENC_IND,ENC_BAL_TYP,ENC_OBJ_CD,CONT_INFO_REQ_IND,BLANKET_IND,AUTO_TR_LIMIT,USE_PER_DIEM,TA_REQUIRED,PER_DIEM_CALC_METHOD,ACTV_IND,VER_NBR,OBJ_ID)
VALUES('BLN','In-State Blanket','N',NULL,NULL,'N','Y','0.00','Y','Y','P','Y',1,SYS_GUID());

-- Airfare Source

INSERT INTO TEM_AIRFARE_SRC_T (CODE, NAME, ACTV_IND,VER_NBR,OBJ_ID)
VALUES ('NEWHORIZON', 'New Horizons (Ghost Card)', 'Y',1,SYS_GUID());

INSERT INTO TEM_AIRFARE_SRC_T (CODE, NAME, ACTV_IND,VER_NBR,OBJ_ID)
VALUES ('INTERNET', 'Internet', 'Y',1,SYS_GUID());

INSERT INTO TEM_AIRFARE_SRC_T (CODE, NAME, ACTV_IND,VER_NBR,OBJ_ID)
VALUES ('FROSCH', 'Frosch (Ghost Card)', 'Y',1,SYS_GUID());

-- Class Of Service
INSERT INTO TEM_CLASS_SVC_T(CODE, DV_EXP_CD, CLASS_SVC_NAME, APRVL_REQ_IND, ACTV_IND, OBJ_ID)
VALUES('COACH','A','Coach-Economy','N','Y', SYS_GUID());

INSERT INTO TEM_CLASS_SVC_T(CODE, DV_EXP_CD, CLASS_SVC_NAME, APRVL_REQ_IND, ACTV_IND, OBJ_ID)
VALUES('BUSINS','A','Business-First Class','Y','Y', SYS_GUID());

INSERT INTO TEM_CLASS_SVC_T(CODE, DV_EXP_CD, CLASS_SVC_NAME, APRVL_REQ_IND, ACTV_IND, OBJ_ID)
VALUES('ECNPLUS','A','Economy Plus','Y','Y', SYS_GUID());

INSERT INTO TEM_CLASS_SVC_T(CODE, DV_EXP_CD, CLASS_SVC_NAME, APRVL_REQ_IND, ACTV_IND, OBJ_ID)
VALUES('ECONMY','R','Economy, Intermediate','N','Y', SYS_GUID());

INSERT INTO TEM_CLASS_SVC_T(CODE, DV_EXP_CD, CLASS_SVC_NAME, APRVL_REQ_IND, ACTV_IND, OBJ_ID)
VALUES('UPGRDE','R','Upgrade (Mid-Size, Van, Other)','Y','Y', SYS_GUID());

INSERT INTO TEM_CLASS_SVC_T(CODE, DV_EXP_CD, CLASS_SVC_NAME, APRVL_REQ_IND, ACTV_IND, OBJ_ID)
VALUES('GPS','R','GPS','Y','N', SYS_GUID());

INSERT INTO TEM_CLASS_SVC_T(CODE, DV_EXP_CD, CLASS_SVC_NAME, APRVL_REQ_IND, ACTV_IND, OBJ_ID)
VALUES('PRIVLIMO','L','Private Limo','Y','Y', SYS_GUID());

INSERT INTO TEM_CLASS_SVC_T(CODE, DV_EXP_CD, CLASS_SVC_NAME, APRVL_REQ_IND, ACTV_IND, OBJ_ID)
VALUES('SHRRIDE','L','Shared Ride','N','Y', SYS_GUID());


-- Transportation Mode

INSERT INTO TEM_TRANS_MD_T (CODE, NAME, ACTV_IND,VER_NBR,OBJ_ID)
VALUES ('AIR', 'Airplane', 'Y',1,SYS_GUID());

INSERT INTO TEM_TRANS_MD_T (CODE, NAME, ACTV_IND,VER_NBR,OBJ_ID)
VALUES ('BUS', 'Bus', 'Y',1,SYS_GUID());

INSERT INTO TEM_TRANS_MD_T (CODE, NAME, ACTV_IND,VER_NBR,OBJ_ID)
VALUES ('HV', 'Host Vehicle', 'Y',1,SYS_GUID());

INSERT INTO TEM_TRANS_MD_T (CODE, NAME, ACTV_IND,VER_NBR,OBJ_ID)
VALUES ('PV', 'Personal Vehicle', 'Y',1,SYS_GUID());

INSERT INTO TEM_TRANS_MD_T (CODE, NAME, ACTV_IND,VER_NBR,OBJ_ID)
VALUES ('RV', 'Rental Vehicle', 'Y',1,SYS_GUID());

INSERT INTO TEM_TRANS_MD_T (CODE, NAME, ACTV_IND,VER_NBR,OBJ_ID)
VALUES ('RVD', 'Rental Vehicle w/Driver', 'Y',1,SYS_GUID());

INSERT INTO TEM_TRANS_MD_T (CODE, NAME, ACTV_IND,VER_NBR,OBJ_ID)
VALUES ('SHP', 'Ship/Ferry/Boat', 'Y',1,SYS_GUID());

INSERT INTO TEM_TRANS_MD_T (CODE, NAME, ACTV_IND,VER_NBR,OBJ_ID)
VALUES ('TRN', 'Train', 'Y',1,SYS_GUID());

INSERT INTO TEM_TRANS_MD_T (CODE, NAME, ACTV_IND,VER_NBR,OBJ_ID)
VALUES ('WLK', 'Walking/Hiking', 'Y',1,SYS_GUID());

INSERT INTO TEM_TRANS_MD_T (CODE, NAME, ACTV_IND,VER_NBR,OBJ_ID)
VALUES ('OTH', 'Other', 'Y',1,SYS_GUID());

-- AR Refunding
INSERT INTO PDP_PAYEE_TYP_T (PAYEE_TYP_CD, OBJ_ID, VER_NBR, PAYEE_TYP_DESC) VALUES ('C', SYS_GUID(), 1, 'AR Customers');

INSERT INTO KRIM_PERM_T (PERM_ID, OBJ_ID, VER_NBR, PERM_TMPL_ID, NMSPC_CD, NM, DESC_TXT, ACTV_IND) VALUES ('TEM-11001', SYS_GUID(), 1, '1', 'KFS-FP', 'Pay AR Customers', 'Allows users to select AR customers for payment on the disbursement voucher document.', 'Y');

INSERT INTO KRIM_ROLE_PERM_T (ROLE_PERM_ID, OBJ_ID, VER_NBR, ROLE_ID, PERM_ID, ACTV_IND) VALUES ('TEM-11001', SYS_GUID(), 1, '3', 'TEM-11001', 'Y');

INSERT INTO AR_PMT_MEDIUM_T VALUES ('TR', SYS_GUID(), 1, 'Travel', 'Y');

-- AR_CUST_TYP_T
INSERT INTO AR_CUST_TYP_T (CUST_TYP_CD, OBJ_ID, VER_NBR, CUST_TYP_DESC, ROW_ACTV_IND) VALUES ('11', SYS_GUID(), 1, 'Traveler', 'Y');

-- new TRAVEL item type for AR AR_INV_ITM_CODE_T
INSERT INTO AR_INV_ITM_CODE_T (FIN_COA_CD, ORG_CD, AR_INV_ITM_CD, AR_INV_ITM_DESC, INV_FIN_COA_CD, INV_ACCT_NBR, INV_FIN_OBJ_CD, ROW_ACTV_IND, OBJ_ID, VER_NBR)
VALUES('UA', 'VPIT', 'TRAVEL', 'Travel Advance', 'UA', '9323001', '1800', 'Y',  SYS_GUID(), 1);

-- Offset Definitions for TA, TAA, TAC, TR
-- EX For RESV OUTSTANDING ORDR EXTRNL ENCUMBRNCES 
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BL','TA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BA','TA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'EA','TA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'FW','TA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'HO','TA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IA','TA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IN','TA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IU','TA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'KO','TA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'NW','TA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SB','TA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SE','TA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'UA','TA', 'EX', '9892',1,SYS_GUID());

INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BL','TA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BA','TA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'EA','TA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'FW','TA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'HO','TA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IA','TA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IN','TA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IU','TA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'KO','TA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'NW','TA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SB','TA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SE','TA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'UA','TA', 'AC', '8000',1,SYS_GUID());

INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BL','TAA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BA','TAA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'EA','TAA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'FW','TAA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'HO','TAA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IA','TAA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IN','TAA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IU','TAA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'KO','TAA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'NW','TAA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SB','TAA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SE','TAA', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'UA','TAA', 'EX', '9892',1,SYS_GUID());

INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BL','TAA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BA','TAA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'EA','TAA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'FW','TAA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'HO','TAA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IA','TAA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IN','TAA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IU','TAA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'KO','TAA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'NW','TAA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SB','TAA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SE','TAA', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'UA','TAA', 'AC', '8000',1,SYS_GUID());

INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BL','TAC', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BA','TAC', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'EA','TAC', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'FW','TAC', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'HO','TAC', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IA','TAC', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IN','TAC', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IU','TAC', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'KO','TAC', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'NW','TAC', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SB','TAC', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SE','TAC', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'UA','TAC', 'EX', '9892',1,SYS_GUID());

INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BL','TAC', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BA','TAC', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'EA','TAC', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'FW','TAC', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'HO','TAC', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IA','TAC', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IN','TAC', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IU','TAC', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'KO','TAC', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'NW','TAC', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SB','TAC', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SE','TAC', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'UA','TAC', 'AC', '8000',1,SYS_GUID());

INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BL','TR', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BA','TR', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'EA','TR', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'FW','TR', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'HO','TR', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IA','TR', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IN','TR', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IU','TR', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'KO','TR', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'NW','TR', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SB','TR', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SE','TR', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'UA','TR', 'EX', '9892',1,SYS_GUID());

INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BL','TR', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BA','TR', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'EA','TR', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'FW','TR', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'HO','TR', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IA','TR', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IN','TR', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IU','TR', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'KO','TR', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'NW','TR', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SB','TR', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SE','TR', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'UA','TR', 'AC', '8000',1,SYS_GUID());

INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BL','RELO', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BA','RELO', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'EA','RELO', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'FW','RELO', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'HO','RELO', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IA','RELO', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IN','RELO', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IU','RELO', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'KO','RELO', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'NW','RELO', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SB','RELO', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SE','RELO', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'UA','RELO', 'EX', '9892',1,SYS_GUID());

INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BL','RELO', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BA','RELO', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'EA','RELO', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'FW','RELO', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'HO','RELO', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IA','RELO', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IN','RELO', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IU','RELO', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'KO','RELO', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'NW','RELO', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SB','RELO', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SE','RELO', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'UA','RELO', 'AC', '8000',1,SYS_GUID());


INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BL','ENT', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BA','ENT', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'EA','ENT', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'FW','ENT', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'HO','ENT', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IA','ENT', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IN','ENT', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IU','ENT', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'KO','ENT', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'NW','ENT', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SB','ENT', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SE','ENT', 'EX', '9892',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'UA','ENT', 'EX', '9892',1,SYS_GUID());

INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BL','ENT', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'BA','ENT', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'EA','ENT', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'FW','ENT', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'HO','ENT', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IA','ENT', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IN','ENT', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'IU','ENT', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'KO','ENT', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'NW','ENT', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SB','ENT', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'SE','ENT', 'AC', '8000',1,SYS_GUID());
INSERT INTO GL_OFFSET_DEFN_T (UNIV_FISCAL_YR,FIN_COA_CD,FDOC_TYP_CD,FIN_BALANCE_TYP_CD,FIN_OBJECT_CD,VER_NBR,OBJ_ID)
VALUES(2011,'UA','ENT', 'AC', '8000',1,SYS_GUID());

UPDATE FP_DV_EXP_TYP_T SET FIN_OBJECT_CD = '6000' WHERE DV_EXP_CD = 'A';
UPDATE FP_DV_EXP_TYP_T SET FIN_OBJECT_CD = '6100' WHERE DV_EXP_CD = 'L';
UPDATE FP_DV_EXP_TYP_T SET FIN_OBJECT_CD = '5070' WHERE DV_EXP_CD = 'M';
UPDATE FP_DV_EXP_TYP_T SET FIN_OBJECT_CD = '5055' WHERE DV_EXP_CD = 'O';
UPDATE FP_DV_EXP_TYP_T SET FIN_OBJECT_CD = '6000' WHERE DV_EXP_CD = 'PA';
UPDATE FP_DV_EXP_TYP_T SET FIN_OBJECT_CD = '4013' WHERE DV_EXP_CD = 'PC';
UPDATE FP_DV_EXP_TYP_T SET FIN_OBJECT_CD = '6000' WHERE DV_EXP_CD = 'PL';
UPDATE FP_DV_EXP_TYP_T SET FIN_OBJECT_CD = '5070' WHERE DV_EXP_CD = 'PM';
UPDATE FP_DV_EXP_TYP_T SET FIN_OBJECT_CD = '5055' WHERE DV_EXP_CD = 'PO';
UPDATE FP_DV_EXP_TYP_T SET FIN_OBJECT_CD = '5055' WHERE DV_EXP_CD = 'PR';
UPDATE FP_DV_EXP_TYP_T SET FIN_OBJECT_CD = '5055' WHERE DV_EXP_CD = 'PT';
UPDATE FP_DV_EXP_TYP_T SET FIN_OBJECT_CD = '5055' WHERE DV_EXP_CD = 'R';
UPDATE FP_DV_EXP_TYP_T SET FIN_OBJECT_CD = '6000' WHERE DV_EXP_CD = 'T';

INSERT INTO FP_DV_EXP_TYP_T (DV_EXP_CD, OBJ_ID, VER_NBR, DV_EXP_NM, DV_EXP_PRPY_IND, ROW_ACTV_IND, FIN_OBJECT_CD)
VALUES ('HB', SYS_GUID(), 1, 'Breakfast', 'N', 'Y', '6000');
INSERT INTO FP_DV_EXP_TYP_T (DV_EXP_CD, OBJ_ID, VER_NBR, DV_EXP_NM, DV_EXP_PRPY_IND, ROW_ACTV_IND, FIN_OBJECT_CD)
VALUES ('HL', SYS_GUID(), 1, 'Lunch', 'N', 'Y', '6000');
INSERT INTO FP_DV_EXP_TYP_T (DV_EXP_CD, OBJ_ID, VER_NBR, DV_EXP_NM, DV_EXP_PRPY_IND, ROW_ACTV_IND, FIN_OBJECT_CD)
VALUES ('HD', SYS_GUID(), 1, 'Dinner', 'N', 'Y', '6000');
INSERT INTO FP_DV_EXP_TYP_T (DV_EXP_CD, OBJ_ID, VER_NBR, DV_EXP_NM, DV_EXP_PRPY_IND, ROW_ACTV_IND, FIN_OBJECT_CD)
VALUES ('MH', SYS_GUID(), 1, 'House hunting costs', 'N', 'Y', '6000');
INSERT INTO FP_DV_EXP_TYP_T (DV_EXP_CD, OBJ_ID, VER_NBR, DV_EXP_NM, DV_EXP_PRPY_IND, ROW_ACTV_IND, FIN_OBJECT_CD)
VALUES ('MT', SYS_GUID(), 1, 'Temporary living', 'N', 'Y', '6000');
INSERT INTO FP_DV_EXP_TYP_T (DV_EXP_CD, OBJ_ID, VER_NBR, DV_EXP_NM, DV_EXP_PRPY_IND, ROW_ACTV_IND, FIN_OBJECT_CD)
VALUES ('ML', SYS_GUID(), 1, 'Living allowances', 'N', 'Y', '6000');
INSERT INTO FP_DV_EXP_TYP_T (DV_EXP_CD, OBJ_ID, VER_NBR, DV_EXP_NM, DV_EXP_PRPY_IND, ROW_ACTV_IND, FIN_OBJECT_CD)
VALUES ('MF', SYS_GUID(), 1, 'Final move meals', 'N', 'Y', '6000');
INSERT INTO FP_DV_EXP_TYP_T (DV_EXP_CD, OBJ_ID, VER_NBR, DV_EXP_NM, DV_EXP_PRPY_IND, ROW_ACTV_IND, FIN_OBJECT_CD)
VALUES ('MM', SYS_GUID(), 1, 'Mileage allowed per mile', 'N', 'Y', '6000');
INSERT INTO FP_DV_EXP_TYP_T (DV_EXP_CD, OBJ_ID, VER_NBR, DV_EXP_NM, DV_EXP_PRPY_IND, ROW_ACTV_IND, FIN_OBJECT_CD)
VALUES ('MD', SYS_GUID(), 1, 'Domestic storage over 30d', 'N', 'Y', '6000');
INSERT INTO FP_DV_EXP_TYP_T (DV_EXP_CD, OBJ_ID, VER_NBR, DV_EXP_NM, DV_EXP_PRPY_IND, ROW_ACTV_IND, FIN_OBJECT_CD)
VALUES ('MI', SYS_GUID(), 1, 'International storage', 'N', 'Y', '6000');
INSERT INTO FP_DV_EXP_TYP_T (DV_EXP_CD, OBJ_ID, VER_NBR, DV_EXP_NM, DV_EXP_PRPY_IND, ROW_ACTV_IND, FIN_OBJECT_CD)
VALUES ('MO', SYS_GUID(), 1, 'Misc. Expense', 'N', 'Y', '6000');
INSERT INTO FP_DV_EXP_TYP_T (DV_EXP_CD, OBJ_ID, VER_NBR, DV_EXP_NM, DV_EXP_PRPY_IND, ROW_ACTV_IND, FIN_OBJECT_CD)
VALUES ('EL', SYS_GUID(), 1, 'Light refreshments', 'N', 'Y', '6000');
INSERT INTO FP_DV_EXP_TYP_T (DV_EXP_CD, OBJ_ID, VER_NBR, DV_EXP_NM, DV_EXP_PRPY_IND, ROW_ACTV_IND, FIN_OBJECT_CD)
VALUES ('AL', SYS_GUID(), 1, 'Alcohol', 'N', 'Y', '6000');
INSERT INTO FP_DV_EXP_TYP_T (DV_EXP_CD, OBJ_ID, VER_NBR, DV_EXP_NM, DV_EXP_PRPY_IND, ROW_ACTV_IND, FIN_OBJECT_CD)
VALUES ('ST', SYS_GUID(), 1, 'Show Tickets', 'N', 'Y', '6000');


--  KUALITEM-273 updating parameters and maintenace tables to make testing easier
-- SW: taken cared of in the krns_parm_t.csv convertion
-- UPDATE KRNS_PARM_T SET TXT = '1=C;2=C;3=C;4=C;5=C;6=C;A=V;B=V,E;C=V,S,E;D=V;E=V;F=V,E;G=V;H=V;K=V,F;L=V;M=V,E;N=V;P=V,E;R=V;T=C,V;W=V;X=V;Z=E' WHERE PARM_NM = 'VALID_PAYEE_TYPES_BY_PAYMENT_REASON';
-- UPDATE KRNS_PARM_T SET TXT = 'A=T;B=T;E=T;F=T;G=T;H=T;K=T;L=T;R=T;W=T;Z=T' WHERE PARM_NM = 'INVALID_DOCUMENTATION_LOCATIONS_BY_PAYMENT_REASON';
UPDATE FP_DV_PMT_REAS_T SET DV_PMT_REAS_NM = 'Travel and Entertainment Module (TEM)' WHERE DV_PMT_REAS_CD = 'T';
UPDATE AR_ORG_OPTION_T SET AR_PRN_INV_IND = 'U' WHERE FIN_COA_CD = 'UA' AND ORG_CD = 'VPIT';


-- Canada
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','CA','AB','Alberta');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','CA','BC','British Columbia');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','CA','MB','Manitoba');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','CA','NB','New Brunswick');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','CA','NF','Newfoundland');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','CA','NT','Northwest Territories');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','CA','NS','Nova Scotia');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','CA','NU','Nunavut');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','CA','ON','Ontario');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','CA','PE','Prince Edward Island');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','CA','QC','Quebec');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','CA','SK','Saskatchewan');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','CA','YT','Yukon');
-- Mexico
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','AG','Aguascalientes');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','BC','Baja California Norte');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','BS','Baja California Sur');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','CH','Chihuahua');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','CL','Colima');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','CM','Campeche');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','CO','Coahuila');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','CS','Chiapas');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','DF','Distrito Federal');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','DG','Durango');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','GR','Guerrero');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','GT','Guanajuato');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','HG','Hidalgo');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','JA','Jalisco');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','MI','Michoacan');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','MO','Morelos');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','NA','Nayarit');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','NL','Nuevo Leon');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','OA','Oaxaca');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','PU','Puebla');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','QR','Quintana Roo');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','QT','Queretaro');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','SI','Sinaloa');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','SL','San Luis Potosi');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','SO','Sonora');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','TB','Tabasco');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','TL','Tlaxcala');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','TM','Tamaulipas');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','VE','Veracruz');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','YU','Yucatan');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','MX','ZA','Zacatecas');
-- Australia
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','AU','AC','Australian Capital Territory');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','AU','NS','New South Wales');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','AU','NT','Northern Territory');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','AU','QL','Queensland');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','AU','SA','South Australia');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','AU','TA','Tasmania');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','AU','VI','Victoria');
INSERT INTO KR_STATE_T (OBJ_ID, VER_NBR, ACTV_IND, POSTAL_CNTRY_CD, POSTAL_STATE_CD, POSTAL_STATE_NM) VALUES (SYS_GUID(),1,'Y','AU','WA','Western Australia');

-- Add TA, TAA, TAC to the list of documents that enter amounts in open amount.
UPDATE KRNS_PARM_T SET TXT = CONCAT(TXT,';TA;TAA;TAC') WHERE PARM_NM = 'ENCUMBRANCE_OPEN_AMOUNT_OVERRIDING_DOCUMENT_TYPES';

-- KUALITEM-704
INSERT INTO TEM_ADV_PMNT_RSN_T (CODE, DESCRIPTION, ACTV_IND, VER_NBR, OBJ_ID)
VALUES('01','Special handling, group leader', 'Y', 1, SYS_GUID());

INSERT INTO TEM_ADV_PMNT_RSN_T (CODE, DESCRIPTION, ACTV_IND, VER_NBR, OBJ_ID)
VALUES('02','Not eligible for corporate card program, students and non-employees', 'Y', 1, SYS_GUID());

INSERT INTO TEM_ADV_PMNT_RSN_T (CODE, DESCRIPTION, ACTV_IND, VER_NBR, OBJ_ID)
VALUES('03','Corporate card not yet issued/rejected', 'Y', 1, SYS_GUID());

INSERT INTO TEM_ADV_PMNT_RSN_T (CODE, DESCRIPTION, ACTV_IND, VER_NBR, OBJ_ID)
VALUES('04','Expenses incurred before trip that need to be paid', 'Y', 1, SYS_GUID());

INSERT INTO TEM_ADV_PMNT_RSN_T (CODE, DESCRIPTION, ACTV_IND, VER_NBR, OBJ_ID)
VALUES('05','Foreign travel - Per Diem', 'Y', 1, SYS_GUID());

INSERT INTO TEM_ADV_PMNT_RSN_T (CODE, DESCRIPTION, ACTV_IND, VER_NBR, OBJ_ID)
VALUES('06','Other (requires free form text)', 'Y', 1, SYS_GUID());

-- Entries for Relocation reason table
INSERT INTO TEM_RELO_REASON_T (RELO_REASON_CD, RELO_REASON_NM, ROW_ACTV_IND, OBJ_ID)
VALUES('HH','House Hunting', 'Y', SYS_GUID());

INSERT INTO TEM_RELO_REASON_T (RELO_REASON_CD, RELO_REASON_NM, ROW_ACTV_IND, OBJ_ID)
VALUES('NH','New Hire', 'Y', SYS_GUID());

INSERT INTO TEM_RELO_REASON_T (RELO_REASON_CD, RELO_REASON_NM, ROW_ACTV_IND, OBJ_ID)
VALUES('RM','Removal', 'Y', SYS_GUID());

INSERT INTO TEM_RELO_REASON_T (RELO_REASON_CD, RELO_REASON_NM, ROW_ACTV_IND, OBJ_ID)
VALUES('IC','Inter Campus Transfer', 'Y', SYS_GUID());


-- Entries for JOb Classification table 
INSERT INTO TEM_JOB_CLASS_T (JOB_CLS_CD, JOB_CLS_NM, ROW_ACTV_IND, OBJ_ID)
VALUES('MSP','Management/Senior Professional','Y',SYS_GUID());

INSERT INTO TEM_JOB_CLASS_T (JOB_CLS_CD, JOB_CLS_NM, ROW_ACTV_IND, OBJ_ID)
VALUES('PSS','Professional Support Staff','Y',SYS_GUID());

INSERT INTO TEM_JOB_CLASS_T (JOB_CLS_CD, JOB_CLS_NM, ROW_ACTV_IND, OBJ_ID)
VALUES('AP','Academic Personnel','Y',SYS_GUID());

INSERT INTO TEM_JOB_CLASS_T (JOB_CLS_CD, JOB_CLS_NM, ROW_ACTV_IND, OBJ_ID)
VALUES('TA','Teaching Assistants','Y',SYS_GUID());

-- Entries for Purpose table
INSERT INTO TEM_PURPOSE_T (DOCUMENT_TYPE, PURPOSE_CODE, PURPOSE_NAME,PURPOSE_DESCRIPTION,REVIEW_REQUIRED_IND,ROW_ACTV_IND,OBJ_ID)
VALUES('ENT','SA', 'Student or Administrative Meetings','Student or Administrative Meetings','Y','Y', SYS_GUID());

INSERT INTO TEM_PURPOSE_T (DOCUMENT_TYPE, PURPOSE_CODE, PURPOSE_NAME,PURPOSE_DESCRIPTION,REVIEW_REQUIRED_IND,ROW_ACTV_IND,OBJ_ID)
VALUES('ENT','RR', 'Reception or Retirement','Reception or retirement','Y','Y', SYS_GUID());

INSERT INTO TEM_PURPOSE_T (DOCUMENT_TYPE, PURPOSE_CODE, PURPOSE_NAME,PURPOSE_DESCRIPTION,REVIEW_REQUIRED_IND,ROW_ACTV_IND,OBJ_ID)
VALUES('ENT','PD', 'Prospective Donor Events','Prospective Donor Events','Y','Y', SYS_GUID());

INSERT INTO TEM_PURPOSE_T (DOCUMENT_TYPE, PURPOSE_CODE, PURPOSE_NAME,PURPOSE_DESCRIPTION,REVIEW_REQUIRED_IND,ROW_ACTV_IND,OBJ_ID)
VALUES('ENT','RC', 'Recruitment','Recruitment','Y','Y', SYS_GUID());

INSERT INTO TEM_PURPOSE_T (DOCUMENT_TYPE, PURPOSE_CODE, PURPOSE_NAME,PURPOSE_DESCRIPTION,REVIEW_REQUIRED_IND,ROW_ACTV_IND,OBJ_ID)
VALUES('RELO','NH', 'New Hire','New Hire','Y','Y', SYS_GUID());

-- Per diem load data
INSERT INTO TEM_PER_DIEM_MIE_BREAK_DOWN_T (MEALS_INC, BKFST, LUNCH, DIN, INC, FIRST_LAST_DAY_AMOUNT, LAST_UPD_DT, ACTV_IND, VER_NBR, OBJ_ID)
VALUES ('46', '7', '11', '23', '5', '34.50', TO_DATE('2011-08-31','yyyy-mm-dd'), 'Y', '1', SYS_GUID());

INSERT INTO TEM_PER_DIEM_MIE_BREAK_DOWN_T (MEALS_INC, BKFST, LUNCH, DIN, INC, FIRST_LAST_DAY_AMOUNT, LAST_UPD_DT, ACTV_IND, VER_NBR, OBJ_ID)
VALUES ('51', '8', '12', '26', '5', '38.25', TO_DATE('2011-08-31','yyyy-mm-dd'), 'Y', '1', SYS_GUID());

INSERT INTO TEM_PER_DIEM_MIE_BREAK_DOWN_T (MEALS_INC, BKFST, LUNCH, DIN, INC, FIRST_LAST_DAY_AMOUNT, LAST_UPD_DT, ACTV_IND, VER_NBR, OBJ_ID)
VALUES ('56', '9', '13', '29', '5', '42', TO_DATE('2011-08-31','yyyy-mm-dd'), 'Y', '1', SYS_GUID());

INSERT INTO TEM_PER_DIEM_MIE_BREAK_DOWN_T (MEALS_INC, BKFST, LUNCH, DIN, INC, FIRST_LAST_DAY_AMOUNT, LAST_UPD_DT, ACTV_IND, VER_NBR, OBJ_ID)
VALUES ('61', '10', '15', '31', '5', '45.75', TO_DATE('2011-08-31','yyyy-mm-dd'), 'Y', '1', SYS_GUID());

INSERT INTO TEM_PER_DIEM_MIE_BREAK_DOWN_T (MEALS_INC, BKFST, LUNCH, DIN, INC, FIRST_LAST_DAY_AMOUNT, LAST_UPD_DT, ACTV_IND, VER_NBR, OBJ_ID)
VALUES ('66', '11', '16', '34', '5', '49.50', TO_DATE('2011-08-31','yyyy-mm-dd'), 'Y', '1', SYS_GUID());

INSERT INTO TEM_PER_DIEM_MIE_BREAK_DOWN_T (MEALS_INC, BKFST, LUNCH, DIN, INC, FIRST_LAST_DAY_AMOUNT, LAST_UPD_DT, ACTV_IND, VER_NBR, OBJ_ID)
VALUES ('71', '12', '18', '36', '5', '53.25', TO_DATE('2011-08-31','yyyy-mm-dd'), 'Y', '1', SYS_GUID());

-- Dummy value for custom per diem expenses.
INSERT INTO TEM_PER_DIEM_T (ID,TRIP_TYP_CD,COUNTRY,COUNTRY_NM,COUNTY_CD,PRI_DEST,EFFECT_FROM_DT,EFFECT_TO_DT,BKFST,LUNCH,DIN,LODGING,INC,MEALS_INC,ACTV_IND,VER_NBR,OBJ_ID)
VALUES (2147483647,'IN','***','***','***','Record used for custom per diems',NULL,NULL,0,0,0,0.00,0.00,0.00,'Y',1,SYS_GUID());

INSERT INTO FP_DV_PMT_REAS_T (DV_PMT_REAS_CD,OBJ_ID,VER_NBR,DV_PMT_REAS_NM,DV_PMT_REAS_DESC,DV_PMT_REAS_ACTV_IND,AR_REFND_IND)
VALUES ('4',SYS_GUID(),1,'Entertainment Reimbursments','used by Travel Managers','Y','N');

INSERT INTO FP_DV_PMT_REAS_T(DV_PMT_REAS_CD,OBJ_ID,VER_NBR,DV_PMT_REAS_NM,DV_PMT_REAS_DESC,DV_PMT_REAS_ACTV_IND,AR_REFND_IND)
VALUES ('3',SYS_GUID(),1,'Travel Vendor Payments','Used to make payments to the vendor','Y','N');

INSERT INTO FP_DV_PMT_REAS_T(DV_PMT_REAS_CD,OBJ_ID,VER_NBR,DV_PMT_REAS_NM,DV_PMT_REAS_DESC,DV_PMT_REAS_ACTV_IND,AR_REFND_IND)
VALUES ('2',SYS_GUID(),1,'Default Refund Payment','Used for Travel Reimbursements.','Y','N');

INSERT INTO FP_DV_PMT_REAS_T(DV_PMT_REAS_CD,OBJ_ID,VER_NBR,DV_PMT_REAS_NM,DV_PMT_REAS_DESC,DV_PMT_REAS_ACTV_IND,AR_REFND_IND)
VALUES ('5',SYS_GUID(),1,'Moving And Relocation Reimbursements','Used for Moving and Relocation Reimbursements','Y','N');

INSERT INTO FP_DV_PMT_REAS_T(DV_PMT_REAS_CD,OBJ_ID,VER_NBR,DV_PMT_REAS_NM,DV_PMT_REAS_DESC,DV_PMT_REAS_ACTV_IND,AR_REFND_IND)
VALUES ('6',SYS_GUID(),1,'Corporate Card Bank Payment','Used to make payments to corporate card bank','Y','N');

INSERT INTO FP_DV_PMT_REAS_T(DV_PMT_REAS_CD,OBJ_ID,VER_NBR,DV_PMT_REAS_NM,DV_PMT_REAS_DESC,DV_PMT_REAS_ACTV_IND,AR_REFND_IND)
VALUES ('1',SYS_GUID(),1,'Travel Advances','Used for Travel Advances','Y','N');

-- SW: taken cared of in the krns_parm_t.csv convertion
-- UPDATE KRNS_PARM_T SET TXT = 'customerLoadInputFileType=default.htm?turl=WordDocuments%2Fbatch.htm;procurementCardInputFileType=default.htm?turl=WordDocuments%2Fbatch.htm;collectorFlatFileInputFileType=default.htm?turl=WordDocuments%2Fbatch.htm;collectorXmlInputFileType=default.htm?turl=WordDocuments%2Fbatch.htm;enterpriseFeederFileSetType=default.htm?turl=WordDocuments%2Fbatch.htm;laborEnterpriseFeederFileSetType=default.htm?turl=WordDocuments%2Fbatch.htm;assetBarcodeInventoryInputFileType=default.htm?turl=WordDocuments%2Fbatch.htm;paymentInputFileType=default.htm?turl=WordDocuments%2Fbatch.htm;creditCardDataXmlInputFileType=default.htm?turl=WordDocuments%2Fbatch.htm;agencyDataXmlInputFileType=default.htm?turl=WordDocuments%2Fbatch.htm;perDiemTxtInputFileType=default.htm?turl=WordDocuments%2Fbatch.htm;perDiemXmlInputFileType=default.htm?turl=WordDocuments%2Fbatch.htm;' WHERE PARM_NM='BATCH_UPLOAD_HELP_URL' AND NMSPC_CD='KFS-SYS';