CREATE TABLE IF NOT EXISTS TEM_ACCOMM_TYP_T
  (
     CODE     VARCHAR(4) NOT NULL,
     NM       VARCHAR(40) NOT NULL,
     ACTV_IND VARCHAR(1) NOT NULL,
     VER_NBR  DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID   VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_ACCOMM_TYP_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_ACCOMM_TYP_T_TP1 PRIMARY KEY(CODE)
  );

CREATE TABLE IF NOT EXISTS TEM_AIRFARE_SRC_T
  (
     CODE     VARCHAR(10) NOT NULL,
     NAME     VARCHAR(40) NOT NULL,
     ACTV_IND VARCHAR(1) NOT NULL,
     VER_NBR  DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID   VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_AIRFARE_SRC_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_AIRFARE_SRC_T_TP1 PRIMARY KEY(CODE)
  );

CREATE TABLE IF NOT EXISTS TEM_CLASS_SVC_T
  (
     CODE           VARCHAR(10) NOT NULL,
     DV_EXP_CD      VARCHAR(2) NOT NULL,
     CLASS_SVC_NAME VARCHAR(40) NOT NULL,
     APRVL_REQ_IND  VARCHAR(1) NULL,
     ACTV_IND       VARCHAR(1) NOT NULL,
     VER_NBR        DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID         VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_CLASS_SVC_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_CLASS_SVC_T_TP1 PRIMARY KEY(CODE),
     CONSTRAINT TEM_CLASS_SVC_T_TR1 FOREIGN KEY (DV_EXP_CD) REFERENCES
     FP_DV_EXP_TYP_T (DV_EXP_CD)
  );

CREATE TABLE IF NOT EXISTS TEM_CONT_REL_TYP_T
  (
     CODE     VARCHAR(3) NOT NULL,
     NM       VARCHAR(40) NOT NULL,
     ACTV_IND VARCHAR(1) NOT NULL,
     VER_NBR  DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID   VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_CONT_REL_TYP_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_CONT_REL_TYP_T_TP1 PRIMARY KEY(CODE)
  );

CREATE TABLE IF NOT EXISTS TEM_MILEAGE_RATE_T
  (
     ID            BIGINT(19) NOT NULL,
     NM            VARCHAR(40) NOT NULL,
     RATE          DECIMAL(19, 2) NULL,
     ACTV_FROM_DT  DATE NOT NULL,
     ACTV_TO_DT    DATE NOT NULL,
     ACTV_IND      VARCHAR(1) NOT NULL,
     VER_NBR       DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID        VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_MILEAGE_RATE_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_MILEAGE_RATE_T_TP1 PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_TRANS_MD_T
  (
     CODE     VARCHAR(3) NOT NULL,
     NAME     VARCHAR(40) NOT NULL,
     ACTV_IND VARCHAR(1) NOT NULL,
     VER_NBR  DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID   VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_TRANS_MD_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_TRANS_MD_T_TP1 PRIMARY KEY(CODE)
  );

CREATE TABLE IF NOT EXISTS TEM_TRIP_TYP_T
  (
     CODE              		VARCHAR(3) 		NOT NULL,
     NM                		VARCHAR(40) 	NOT NULL,
     GEN_ENC_IND       		VARCHAR(1) 		NOT NULL,
     ENC_BAL_TYP       		VARCHAR(2) 		NULL,
     ENC_OBJ_CD        		VARCHAR(4) 		NULL,
     CONT_INFO_REQ_IND 		VARCHAR(1) 		NOT NULL,
     BLANKET_IND       		VARCHAR(1) 		NOT NULL,
     AUTO_TR_LIMIT			DECIMAL(19,2)  	NOT NULL,
     USE_PER_DIEM 			VARCHAR(1) 		NOT NULL,
     TA_REQUIRED 			VARCHAR(1) 		NOT NULL,
     PER_DIEM_CALC_METHOD 	VARCHAR(1) 		NOT NULL,
     ACTV_IND          		VARCHAR(1) 		NOT NULL,
     VER_NBR           		DECIMAL(8, 0) 	DEFAULT 1 NOT NULL,
     OBJ_ID            		VARCHAR(36) 	NOT NULL,
     CONSTRAINT TEM_TRIP_TYP_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_TRIP_TYP_T_TP1 PRIMARY KEY(CODE)
  );

CREATE TABLE IF NOT EXISTS TEM_TRAVELER_TYP_T
  (
     CODE         VARCHAR(3) NOT NULL,
     SRC_CODE     VARCHAR(10) NULL,
     NM           VARCHAR(40) NOT NULL,
     ADVANCES_IND VARCHAR(1) NOT NULL,
     ACTV_IND     VARCHAR(1) NOT NULL,
     VER_NBR      DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID       VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_TRAVELER_TYP_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_TRAVELER_TYP_T_TP1 PRIMARY KEY(CODE)
  );

CREATE TABLE IF NOT EXISTS TEM_SPCL_CRCMSNCS_Q_T
  (
     ID            BIGINT(19) NOT NULL,
     DOCUMENT_TYPE VARCHAR(4) NOT NULL,     
     TEXT          VARCHAR(255) NULL,
     TXT_IND       VARCHAR(1) NULL,
     ACTV_IND      VARCHAR(1) NOT NULL,
     VER_NBR       DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID        VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_SPCL_CRCMSNCS_Q_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_SPCL_CRCMSNCS_Q_T_TP1 PRIMARY KEY (ID)
  );

CREATE TABLE IF NOT EXISTS TEM_SPCL_CRCMSNCS_T
  (
     ID       BIGINT(19) NOT NULL,
     QID      BIGINT(19) NOT NULL,
     FDOC_NBR VARCHAR(255) NOT NULL,
     RESPONSE VARCHAR(1) NULL,
     TEXT     VARCHAR(255) NULL,
     VER_NBR  DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID   VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_SPCL_CRCMSNCS_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_SPCL_CRCMSNCS_T_TR1 FOREIGN KEY (QID) REFERENCES
     TEM_SPCL_CRCMSNCS_Q_T(ID),
     CONSTRAINT TEM_SPCL_CRCMSNCS_T_TP1 PRIMARY KEY (ID)
  );

CREATE TABLE IF NOT EXISTS TEM_PER_DIEM_T
  (
     ID                BIGINT(19) NOT NULL,
     TRIP_TYP_CD       VARCHAR(3) NOT NULL,
     COUNTRY           VARCHAR(100) NULL,
     COUNTRY_NM        VARCHAR(100) NULL,
     COUNTY_CD         VARCHAR(100) NULL,
     PRI_DEST          VARCHAR(100) NULL,
     SSN_BGN_DT        DATE NULL,
     EFFECT_FROM_DT    DATE NULL,
     EFFECT_TO_DT      DATE DEFAULT NULL NULL,
     LOAD_DT           DATE DEFAULT NULL NULL,
     SSN_BGN_MONTH_DAY VARCHAR(5) DEFAULT NULL NULL,
     BKFST             BIGINT(19) NULL,
     LUNCH             BIGINT(19) NULL,
     DIN               BIGINT(19) NULL,
     LODGING           DECIMAL(19, 2) DEFAULT 0 NULL,
     INC               DECIMAL(19, 2) DEFAULT 0 NULL,
     MEALS_INC         DECIMAL(19, 2) DEFAULT 0 NULL,
     ACTV_IND          VARCHAR(1) NOT NULL,
     VER_NBR           DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID            VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_PER_DIEM_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_PER_DIEM_T_TR1 FOREIGN KEY (TRIP_TYP_CD) REFERENCES
     TEM_TRIP_TYP_T(CODE),
     CONSTRAINT TEM_PER_DIEM_T_TP1 PRIMARY KEY(ID)
  );

-- add per diem meal and incidental expense break down table
CREATE TABLE IF NOT EXISTS TEM_PER_DIEM_MIE_BREAK_DOWN_T
  (
     MEALS_INC             DECIMAL(19, 2) NOT NULL,
     BKFST                 BIGINT(19) NULL,
     LUNCH                 BIGINT(19) NULL,
     DIN                   BIGINT(19) NULL,
     INC                   DECIMAL(19, 2) DEFAULT 0 NULL,
     FIRST_LAST_DAY_AMOUNT DECIMAL(19, 2) DEFAULT 0 NULL,
     LAST_UPD_DT           DATE,
     ACTV_IND              VARCHAR(1) NOT NULL,
     VER_NBR               DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID                VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_PER_DIEM_MIE_BRK_DWN_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_PER_DIEM_MIE_BRK_DWN_T_TP1 PRIMARY KEY(MEALS_INC)
  );

CREATE TABLE IF NOT EXISTS TEM_TRIP_DTL_EST_T
  (
     ID            BIGINT(19) NOT NULL,
     FDOC_NBR      VARCHAR(255) NULL,
     FDOC_LINE_NBR BIGINT(19) NULL,
     DETAIL_DT     DATE NULL,
     COUNTRY       VARCHAR(100) NULL,
     COUNTY_CD     VARCHAR(100) NULL,
     PRI_DEST      VARCHAR(100) NULL,
     PERSONAL      VARCHAR(1) NULL,
     MEALS_INC     DECIMAL(19, 2) DEFAULT 0 NULL,
     LODGING       DECIMAL(19, 2) DEFAULT 0 NULL,
     MILES         BIGINT(19) NULL,
     MILEAGE_RT_ID BIGINT(19) NULL,
     OTHER_EXP     DECIMAL(19, 2) DEFAULT 0 NULL,
     ACCOM_TYP_CD  VARCHAR(4) NULL,
     ACCOM_NM      VARCHAR(255) NULL,
     ACCOM_PH      VARCHAR(20) NULL,
     ACCOM_ADDRESS VARCHAR(255) NULL,
     PER_DIEM_ID   BIGINT(19) NOT NULL,
     VER_NBR       DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID        VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_TRIP_DTL_EST_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_TRIP_DTL_EST_T_TR1 FOREIGN KEY (MILEAGE_RT_ID) REFERENCES
     TEM_MILEAGE_RATE_T(ID),
     CONSTRAINT TEM_TRIP_DTL_EST_T_TR2 FOREIGN KEY (ACCOM_TYP_CD) REFERENCES
     TEM_ACCOMM_TYP_T(CODE),
     CONSTRAINT TEM_TRIP_DTL_EST_T_TR3 FOREIGN KEY (PER_DIEM_ID) REFERENCES
     TEM_PER_DIEM_T(ID),
     CONSTRAINT TEM_TRIP_DTL_EST_T_TP1 PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_TRAVELER_PROF_T
  (
     ID              BIGINT(19) NOT NULL,
     FIRST_NM        VARCHAR(40) NULL,
     LAST_NM         VARCHAR(40) NULL,
     ADDR_LINE_1     VARCHAR(50) NULL,
     ADDR_LINE_2     VARCHAR(50) NULL,
     CITY_NM         VARCHAR(50) NULL,
     POSTAL_STATE_CD VARCHAR(50) NULL,
     POSTAL_CD       VARCHAR(50) NULL,
     COUNTRY_CD      VARCHAR(50) NULL,
     EMAIL_ADDR      VARCHAR(50) NULL,
     PHONE_NBR       VARCHAR(20) NULL,
     TRAVELER_TYP_CD VARCHAR(3) NOT NULL,
     VER_NBR         DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID          VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_TRAVELER_PROF_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_TRAVELER_PROF_T_TR1 FOREIGN KEY (TRAVELER_TYP_CD) REFERENCES
     TEM_TRAVELER_TYP_T(CODE),
     CONSTRAINT TEM_TRAVELER_PROF_T_TP1 PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_MILEAGE_RATE_OBJ_CD_T
  (
     ID               BIGINT(19) NOT NULL,
     TRAVELER_TYP_CD  VARCHAR(3) NOT NULL,
     TRIP_TYP_CD      VARCHAR(3) NOT NULL,
     MILEAGE_RT_ID    BIGINT(19) NOT NULL,
     FIN_OBJECT_CD    VARCHAR(4) NOT NULL,
     DOCUMENT_TYPE    VARCHAR(4) NOT NULL,     
     ACTV_IND         VARCHAR(1) NOT NULL,
     VER_NBR          DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID           VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_MILEAGE_RATE_OBJ_CD_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_MILEAGE_RATE_OBJ_CD_T_TR1 FOREIGN KEY (TRAVELER_TYP_CD)
     REFERENCES TEM_TRAVELER_TYP_T(CODE),
     CONSTRAINT TEM_MILEAGE_RATE_OBJ_CD_T_TR2 FOREIGN KEY (TRIP_TYP_CD)
     REFERENCES TEM_TRIP_TYP_T(CODE),
     CONSTRAINT TEM_MILEAGE_RATE_OBJ_CD_T_TR3 FOREIGN KEY (MILEAGE_RT_ID)
     REFERENCES TEM_MILEAGE_RATE_T(ID),
     CONSTRAINT TEM_MILEAGE_RATE_OBJ_CD_T_TP1 PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_GRP_TRVLR_T
  (
     ID              BIGINT(19) NOT NULL,
     FDOC_NBR        VARCHAR(255) NULL,
     FDOC_LINE_NBR   BIGINT(19) NULL,
     NAME            VARCHAR(100) NULL,
     TRAVELER_TYP_CD VARCHAR(3) NOT NULL,
     TRVL_EMP_ID     VARCHAR(255) NULL,
     VER_NBR         DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID          VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_GRP_TRVLR_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_GRP_TRVLR_T_TR1 FOREIGN KEY (TRAVELER_TYP_CD) REFERENCES
     TEM_TRAVELER_TYP_T(CODE),
     CONSTRAINT TEM_GRP_TRVLR_T_TP1 PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_TRAVELER_DTL_T
  (
     ID                  BIGINT(19) NOT NULL,
     DOC_NBR             VARCHAR(255) NULL,
     EMP_PRINCIPAL_ID    VARCHAR(255) NULL,
     CUST_NBR            VARCHAR(40) NULL,
     FIRST_NM            VARCHAR(40) NULL,
     LAST_NM             VARCHAR(40) NULL,
     ADDR_LINE_1         VARCHAR(50) NULL,
     ADDR_LINE_2         VARCHAR(50) NULL,
     CITY_NM             VARCHAR(50) NULL,
     POSTAL_STATE_CD     VARCHAR(50) NULL,
     POSTAL_CD           VARCHAR(50) NULL,
     COUNTRY_CD          VARCHAR(50) NULL,
     EMAIL_ADDR          VARCHAR(50) NULL,
     PHONE_NBR           VARCHAR(20) NULL,
     CITIZENSHIP         VARCHAR(40) NULL,
     LIABILITY_INSURANCE VARCHAR(1) NOT NULL,
     TRAVELER_TYP_CD     VARCHAR(3) NOT NULL,
     ACTV_IND            VARCHAR(1) NOT NULL,
     VER_NBR             DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID              VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_TRAVELER_DTL_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_TRAVELER_DTL_T_TR1 FOREIGN KEY (TRAVELER_TYP_CD) REFERENCES
     TEM_TRAVELER_TYP_T(CODE),
     CONSTRAINT TEM_TRAVELER_DTL_T_TR2 FOREIGN KEY (CUST_NBR) REFERENCES
     AR_CUST_T(CUST_NBR),
     CONSTRAINT TEM_TRAVELER_DTL_T_TP1 PRIMARY KEY(ID)
  );
  
CREATE TABLE IF NOT EXISTS TEM_PROFILE_EM_CONT_T
  (
     ID              BIGINT(19) NOT NULL,
     FDOC_NBR        VARCHAR(255) NULL,
     FDOC_LINE_NBR   BIGINT(19) NULL,
     CONT_REL_TYP_CD VARCHAR(3) NOT NULL,
     CONT_NM         VARCHAR(40) NULL,
     PHONE_NBR       VARCHAR(20) NULL,
     EMAIL_ADDR      VARCHAR(50) NULL,
     TEM_PROFILE_ID  BIGINT(19) NULL,
     PRIMARY_IND     VARCHAR(1) NULL,
     VER_NBR         DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID          VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_PROFILE_EM_CONT_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_PROFILE_EM_CONT_T_TR1 FOREIGN KEY (CONT_REL_TYP_CD)
     REFERENCES TEM_CONT_REL_TYP_T(CODE),
     CONSTRAINT TEM_PROFILE_EM_CONT_T_TP1 PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_EM_CONT_T
  (
     ID              BIGINT(19) NOT NULL,
     FDOC_NBR        VARCHAR(255) NULL,
     FDOC_LINE_NBR   BIGINT(19) NULL,
     CONT_REL_TYP_CD VARCHAR(3) NOT NULL,
     CONT_NM         VARCHAR(40) NULL,
     PHONE_NBR       VARCHAR(20) NULL,
     EMAIL_ADDR      VARCHAR(50) NULL,
     TRAVELER_DTL_ID BIGINT(19) NULL,
     PRIMARY_IND     VARCHAR(1) NULL,
     VER_NBR         DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID          VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_EM_CONT_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_EM_CONT_T_TR1 FOREIGN KEY (CONT_REL_TYP_CD) REFERENCES
     TEM_CONT_REL_TYP_T(CODE),
     CONSTRAINT TEM_EM_CONT_T_TR2 FOREIGN KEY (TRAVELER_DTL_ID) REFERENCES
     TEM_TRAVELER_DTL_T(ID),
     CONSTRAINT TEM_EM_CONT_T_TP1 PRIMARY KEY(ID)
  );


CREATE TABLE IF NOT EXISTS TEM_TRVL_EXP_T
  (
     ID       			  BIGINT(19) NOT NULL,
     FDOC_NBR             VARCHAR(14) NOT NULL,
     FDOC_LINE_NBR        BIGINT(19) NULL,
     EXP_TYPE_CD		  VARCHAR(1) NULL,
     EXP_PARENT_ID        BIGINT(19) DEFAULT NULL,
     HIST_EXP_ID          BIGINT(19) DEFAULT NULL,
     EXP_DT               DATE NULL,
     EXP_AMT              DECIMAL(20, 3) DEFAULT 0,
     EXP_DESC             VARCHAR(255) NULL,
     CUR_RT               DECIMAL(7, 6) DEFAULT 0,
     CUR_COUNTRY_CD       VARCHAR(100) NULL,
     CONVERTED_AMT        DECIMAL(7, 2) DEFAULT 0,
     TEM_EXP_TYP_ID       BIGINT(19) NOT NULL,
     DV_EXP_CO_NM         VARCHAR(40) NULL,
     AIRFARE_SRC_CD       VARCHAR(10) NULL,
     CLASS_SVC_CODE       VARCHAR(10) NULL,
     MILEAGE_RT_ID        BIGINT(19) NULL,
     MILES                BIGINT(19) NULL,
     MILEAGE_OTHR_RT      DECIMAL(19, 2) DEFAULT 0,
     CARD_TYPE       	  VARCHAR(40) NULL,
     RENTAL_CAR_INSURANCE VARCHAR(1) NULL,
     NON_REIMB_IND        VARCHAR(1) NULL,
     TAXABLE_IND          VARCHAR(1) NULL,
     MISG_RCPT_IND		  VARCHAR(1) NULL,
     RCPT_RQD_IND		  VARCHAR(1) NULL,
     VER_NBR              DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID               VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_TRVL_EXP_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_TRVL_EXP_T_TR1 FOREIGN KEY (AIRFARE_SRC_CD) REFERENCES
     TEM_AIRFARE_SRC_T (CODE),
     --  CONSTRAINT TEM_TRVL_EXP_T_TR3 FOREIGN KEY (MILEAGE_RT_ID) REFERENCES
     --  TEM_MILEAGE_RATE_T (ID),
     CONSTRAINT TEM_TRVL_EXP_T_TR4 FOREIGN KEY (CLASS_SVC_CODE) REFERENCES
     TEM_CLASS_SVC_T (CODE),
     -- CONSTRAINT TEM_TRVL_EXP_T_TR5 FOREIGN KEY (EXP_PARENT_ID) REFERENCES
     -- TEM_TRVL_EXP_T(ID),
     CONSTRAINT TEM_TRVL_EXP_T_TP1 PRIMARY KEY (ID)
  );

CREATE TABLE IF NOT EXISTS TEM_EXP_TYP_T
  (
     TEM_EXP_TYP_ID      BIGINT(19) NOT NULL,
     TRAVEL_EXP_CD       VARCHAR(2) NOT NULL,
     TRAVEL_EXP_NM       VARCHAR(25) NOT NULL,
     TRAVEL_EXP_PRPY_IND VARCHAR(1) NOT NULL,
     FIN_OBJECT_CD       VARCHAR(4) NULL,
     HST_ML_IND          VARCHAR(1) NULL,
     LNG_DESC            VARCHAR(1000) NULL,
     INDV_IND            VARCHAR(1) NULL,
     GRP_TRVL_IND        VARCHAR(1) NULL,
     TRIP_TYP_CD         VARCHAR(3) NULL,
     TRAVELER_TYP_CD     VARCHAR(3) NULL,
     DOCUMENT_TYPE       VARCHAR(4) NULL,
     MAX_AMT             DECIMAL(9, 2) NULL,
     MAX_AMT_PER         VARCHAR(1) NULL,
     ERR_TYP_CD          VARCHAR(1) NULL,
     NOTE_REQ_IND        VARCHAR(1) NULL,
     RCPT_REQ_IND        VARCHAR(1) NULL,
     RCPT_REQ_THRSH      BIGINT(19) NULL,
     TAXABLE_IND         VARCHAR(1) NULL,
     SPCL_RQST_REQ_IND   VARCHAR(1) NULL,
     ACTV_IND            VARCHAR(1) NOT NULL,
     VER_NBR             DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID              VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_EXP_TYP_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_EXP_TYP_T_TC1 UNIQUE (TEM_EXP_TYP_ID),
     CONSTRAINT TEM_EXP_TYP_T_TR1 FOREIGN KEY (TRIP_TYP_CD) REFERENCES TEM_TRIP_TYP_T(CODE),
     CONSTRAINT TEM_EXP_TYP_T_TR2 FOREIGN KEY (TRAVELER_TYP_CD) REFERENCES TEM_TRAVELER_TYP_T(CODE),
     CONSTRAINT TEM_EXP_TYP_T_TP1 PRIMARY KEY(TRAVEL_EXP_CD, TRIP_TYP, TRV_TYP, DOCUMENT_TYPE)
  );
  
CREATE TABLE IF NOT EXISTS TEM_TRVL_ADV_T
  (
     ID              BIGINT(19) NOT NULL,
     FDOC_NBR        VARCHAR(255) NULL,
     FDOC_LINE_NBR   BIGINT(19) NULL,
     TVL_ADV_REQ     DECIMAL(19, 2) DEFAULT 0 NULL,
     AR_CUST_ID      VARCHAR(255) NULL,
     AR_INV_DOC_NBR  VARCHAR(255) NULL,
     DUE_DT          DATE NULL,
     PYMT_MTHD       VARCHAR(255) NULL,
     ACCOUNT_NBR     VARCHAR(7) NULL,
     SUB_ACCT_NBR    VARCHAR(5) NULL,
     FIN_OBJECT_CD   VARCHAR(4) NULL,
     FIN_SUB_OBJ_CD  VARCHAR(3) NULL,
     ADV_PMNT_RSN_CD VARCHAR(2) NULL,
     TRVL_ADV_PLCY   VARCHAR(1) NOT NULL,
     ADD_JUST        VARCHAR(100) NULL,
     TAX_RAM_NTF_DT  DATETIME,
     FIN_COA_CD      VARCHAR(2),
     VER_NBR         DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID          VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_TRVL_ADV_T_TC0 UNIQUE (OBJ_ID),
     -- missing some extra fields for our constraints 
     -- CONSTRAINT TEM_TRVL_ADV_T_TR1 FOREIGN KEY (ACCOUNT_NBR) REFERENCES CA_ACCOUNT_T(ACCOUNT_NBR),
     -- CONSTRAINT TEM_TRVL_ADV_T_TR2 FOREIGN KEY (SUB_ACCT_NBR) REFERENCES CA_SUB_ACCT_T(SUB_ACCT_NBR),
     -- CONSTRAINT TEM_TRVL_ADV_T_TR3 FOREIGN KEY (FIN_OBJECT_CD) REFERENCES CA_OBJECT_CODE_T(FIN_OBJECT_CD),
     -- CONSTRAINT TEM_TRVL_ADV_T_TR4 FOREIGN KEY (FIN_SUB_OBJ_CD) REFERENCES CA_SUB_OBJECT_CD_T(FIN_SUB_OBJ_CD),
     CONSTRAINT TEM_TRVL_ADV_T_TP1 PRIMARY KEY(ID)
  );

-- Transactional Documents
CREATE TABLE IF NOT EXISTS TEM_TRVL_AUTH_DOC_T
  (
     FDOC_NBR                VARCHAR(14) NOT NULL,
     TRVL_ID                 VARCHAR(19) NULL,
     TRAVELER_DTL_ID         BIGINT(19) NULL,
     TEM_PROFILE_ID          BIGINT(19) NULL,
     TRIP_TYP_CD             VARCHAR(3) NULL,
     TRIP_BGN_DT             DATE NULL,
     TRIP_END_DT             DATE NULL,
     PRIMARY_DEST_ID         BIGINT(19) NULL,
     PRIMARY_DEST_NAME       VARCHAR(100) NULL,
     PRIMARY_DEST_CNTRY_ST   VARCHAR(100) NULL,
     PRIMARY_DEST_CNTY       VARCHAR(100) NULL,
     EXP_LMT                 DECIMAL(19, 2) DEFAULT 0 NULL,
     MEAL_WITHOUT_LODGING    VARCHAR(255) NULL,
     TRIP_DESC               VARCHAR(255) NULL,
     DELINQUENT_TR_EXCEPTION VARCHAR(1) NULL,
     PER_DIEM_ADJ            DECIMAL(19, 2) DEFAULT 0 NULL,
     AR_CUST_ID              VARCHAR(255) NULL,
     AR_INV_DOC_NBR          VARCHAR(255) NULL,
     CELL_PH_NUM             VARCHAR(20) NULL,
     RGN_FAMIL               VARCHAR(255) NULL,
     CTZN_CNTRY_CD           VARCHAR(255) NULL,
     FDOC_NXT_EXP_NBR        DECIMAL(7, 0),
     VER_NBR                 DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID                  VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_TRVL_AUTH_DOC_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_TRVL_AUTH_DOC_T_TR1 FOREIGN KEY (TRAVELER_DTL_ID) REFERENCES
     TEM_TRAVELER_DTL_T(ID),
     CONSTRAINT TEM_TRVL_AUTH_DOC_T_TR2 FOREIGN KEY (TRIP_TYP_CD) REFERENCES
     TEM_TRIP_TYP_T(CODE),
     CONSTRAINT TEM_TRVL_AUTH_DOC_T_TR3 FOREIGN KEY (PRIMARY_DEST_ID) REFERENCES
     TEM_PER_DIEM_T(ID),
     CONSTRAINT TEM_TRVL_AUTH_DOC_T_TP1 PRIMARY KEY(FDOC_NBR)
  );

CREATE TABLE IF NOT EXISTS TEM_TRVL_AUTH_AMEND_DOC_T
  (
     FDOC_NBR              VARCHAR(14) NOT NULL,
     TRVL_ID               VARCHAR(19) NULL,
     TRAVELER_DTL_ID       BIGINT(19) NULL,
     TEM_PROFILE_ID        BIGINT(19) NULL,
     TRIP_TYP_CD           VARCHAR(3) NULL,
     TRIP_BGN_DT           DATE NULL,
     TRIP_END_DT           DATE NULL,
     PRIMARY_DEST_ID       BIGINT(19) NULL,
     PRIMARY_DEST_NAME     VARCHAR(100) NULL,
     PRIMARY_DEST_CNTRY_ST VARCHAR(100) NULL,
     PRIMARY_DEST_CNTY     VARCHAR(100) NULL,
     EXP_LMT               DECIMAL(19, 2) DEFAULT 0 NULL,
     MEAL_WITHOUT_LODGING  VARCHAR(255) NULL,
     TRIP_DESC             VARCHAR(255) NULL,
     PER_DIEM_ADJ          DECIMAL(19, 2) DEFAULT 0 NULL,
     AR_CUST_ID            VARCHAR(255) NULL,
     AR_INV_DOC_NBR        VARCHAR(255) NULL,
     CELL_PH_NUM           VARCHAR(20) NULL,
     RGN_FAMIL             VARCHAR(255) NULL,
     CTZN_CNTRY_CD         VARCHAR(255) NULL,
     FDOC_NXT_EXP_NBR      DECIMAL(7, 0),
     VER_NBR               DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID                VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_TRVL_AUTH_AMEND_DOC_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_TRVL_AUTH_AMEND_DOC_T_TR1 FOREIGN KEY (TRAVELER_DTL_ID)
     REFERENCES TEM_TRAVELER_DTL_T(ID),
     CONSTRAINT TEM_TRVL_AUTH_AMEND_DOC_T_TR2 FOREIGN KEY (TRIP_TYP_CD)
     REFERENCES TEM_TRIP_TYP_T(CODE),
     CONSTRAINT TEM_TRVL_AUTH_AMEND_DOC_T_TR3 FOREIGN KEY (PRIMARY_DEST_ID)
     REFERENCES TEM_PER_DIEM_T(ID),
     CONSTRAINT TEM_TRVL_AUTH_AMEND_DOC_T_TP1 PRIMARY KEY(FDOC_NBR)
  );

CREATE TABLE IF NOT EXISTS TEM_TRVL_AUTH_CLOSE_DOC_T
  (
     FDOC_NBR              VARCHAR(14) NOT NULL,
     TRVL_ID               VARCHAR(19) NULL,
     TRAVELER_DTL_ID       BIGINT(19) NULL,
     TEM_PROFILE_ID        BIGINT(19) NULL,
     TRIP_TYP_CD           VARCHAR(3) NULL,
     TRIP_BGN_DT           DATE NULL,
     TRIP_END_DT           DATE NULL,
     PRIMARY_DEST_ID       BIGINT(19) NULL,
     PRIMARY_DEST_NAME     VARCHAR(100) NULL,
     PRIMARY_DEST_CNTRY_ST VARCHAR(100) NULL,
     PRIMARY_DEST_CNTY     VARCHAR(100) NULL,
     EXP_LMT               DECIMAL(19, 2) DEFAULT 0 NULL,
     MEAL_WITHOUT_LODGING  VARCHAR(255) NULL,
     TRIP_DESC             VARCHAR(255) NULL,
     PER_DIEM_ADJ          DECIMAL(19, 2) DEFAULT 0 NULL,
     AR_CUST_ID            VARCHAR(255) NULL,
     AR_INV_DOC_NBR        VARCHAR(255) NULL,
     CELL_PH_NUM           VARCHAR(20) NULL,
     RGN_FAMIL             VARCHAR(255) NULL,
     CTZN_CNTRY_CD         VARCHAR(255) NULL,
     FDOC_NXT_EXP_NBR      DECIMAL(7, 0),
     VER_NBR               DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID                VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_TRVL_AUTH_CLOSE_DOC_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_TRVL_AUTH_CLOSE_DOC_T_TR1 FOREIGN KEY (TRAVELER_DTL_ID)
     REFERENCES TEM_TRAVELER_DTL_T(ID),
     CONSTRAINT TEM_TRVL_AUTH_CLOSE_DOC_T_TR2 FOREIGN KEY (TRIP_TYP_CD)
     REFERENCES TEM_TRIP_TYP_T(CODE),
     CONSTRAINT TEM_TRVL_AUTH_CLOSE_DOC_T_TR3 FOREIGN KEY (PRIMARY_DEST_ID)
     REFERENCES TEM_PER_DIEM_T(ID),
     CONSTRAINT TEM_TRVL_AUTH_CLOSE_DOC_T_TP1 PRIMARY KEY(FDOC_NBR)
  );

CREATE TABLE IF NOT EXISTS TEM_TRANS_MD_DTL_T
  (
     TRANS_MODE_CD VARCHAR(3) NOT NULL,
     FDOC_NBR      VARCHAR(14) NOT NULL,
     VER_NBR       DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID        VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_TRANS_MD_DTL_T_TR1 FOREIGN KEY (TRANS_MODE_CD) REFERENCES
     TEM_TRANS_MD_T(CODE),
     CONSTRAINT TEM_TRANS_MD_DTL_T_TP1 PRIMARY KEY(FDOC_NBR, TRANS_MODE_CD)
  );

CREATE TABLE IF NOT EXISTS TEM_TRVL_REIMB_DOC_T
  (
     FDOC_NBR                VARCHAR(14) NOT NULL,
     TRVL_ID                 VARCHAR(19) NULL,
     FINAL_REIMB_IND         VARCHAR(1) NULL,
     ADJUSTMENT              DECIMAL(19, 2) DEFAULT 0 NULL,
     EXP_LMT                 DECIMAL(19, 2) DEFAULT 0 NULL,
     MEAL_WITHOUT_LODGING    VARCHAR(255) NULL,
     EMP_PRINCIPAL_ID        VARCHAR(255) NULL,
     TRAVELER_DTL_ID         BIGINT(19) NULL,
     TEM_PROFILE_ID          BIGINT(19) NULL,
     EMP_CERT_IND            VARCHAR(1) NULL,
     CON_NM                  VARCHAR(40) NULL,
     CON_PHONE_NBR           VARCHAR(20) NULL,
     CON_EMAIL_ADDR          VARCHAR(40) NULL,
     CON_CAMPUS_CD           VARCHAR(2) NULL,
     TRIP_TYP_CD             VARCHAR(3) NULL,
     TRIP_BGN_DT             DATE NULL,
     TRIP_END_DT             DATE NULL,
     PRIMARY_DEST_ID         BIGINT(19) NULL,
     PRIMARY_DEST_NAME       VARCHAR(100) NULL,
     PRIMARY_DEST_CNTRY_ST   VARCHAR(100) NULL,
     PRIMARY_DEST_CNTY       VARCHAR(100) NULL,
     TRIP_DESC               VARCHAR(255) NULL,
     PAYMENT_METHOD			 VARCHAR(15) NULL,
     DELINQUENT_TR_EXCEPTION VARCHAR(1) NULL,
     FDOC_NXT_EXP_NBR        DECIMAL(7, 0),
     TVL_ADV_AMT             DECIMAL(19, 2) DEFAULT 0 NULL,
     VER_NBR                 DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID                  VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_TRVL_REIMB_DOC_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_TRVL_REIMB_DOC_T_TR1 FOREIGN KEY (TRAVELER_DTL_ID)
     REFERENCES TEM_TRAVELER_DTL_T(ID),
     CONSTRAINT TEM_TRVL_REIMB_DOC_T_TR2 FOREIGN KEY (TRIP_TYP_CD) REFERENCES
     TEM_TRIP_TYP_T(CODE),
     CONSTRAINT TEM_TRVL_REIMB_DOC_T_TR3 FOREIGN KEY (PRIMARY_DEST_ID)
     REFERENCES TEM_PER_DIEM_T(ID),
     CONSTRAINT TEM_TRVL_REIMB_DOC_T_TP1 PRIMARY KEY(FDOC_NBR)
  );

CREATE TABLE IF NOT EXISTS TEM_JOB_CLASS_T
  (
     JOB_CLS_CD   VARCHAR(3) NOT NULL,
     JOB_CLS_NM   VARCHAR(40) NOT NULL,
     ROW_ACTV_IND VARCHAR(1) NOT NULL,
     VER_NBR      DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID       VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_JOB_CLASS_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_JOB_CLASS_T_TP1 PRIMARY KEY(JOB_CLS_CD)
  );

CREATE TABLE IF NOT EXISTS TEM_RELO_REASON_T
  (
     RELO_REASON_CD    VARCHAR(2) NOT NULL,
     RELO_REASON_NM    VARCHAR(40) NOT NULL,
     RELO_REASON_DESCR VARCHAR(200) NULL,
     ROW_ACTV_IND      VARCHAR(1) NOT NULL,
     VER_NBR           DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID            VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_RELO_REASON_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_RELO_REASON_T_TP1 PRIMARY KEY(RELO_REASON_CD)
  );

CREATE TABLE IF NOT EXISTS TEM_RELO_DOC_T
  (
     FDOC_NBR         VARCHAR(14) NOT NULL,
     TRVL_ID          VARCHAR(19) NULL,
     TRIP_TYP_CD      VARCHAR(3) NULL,
     TRIP_BGN_DT      DATE NULL,
     TRIP_END_DT      DATE NULL,
     PRIMARY_DEST_ID         BIGINT(19) NULL,
     PRIMARY_DEST_NAME       VARCHAR(100) NULL,
     PRIMARY_DEST_CNTRY_ST   VARCHAR(100) NULL,
     PRIMARY_DEST_CNTY       VARCHAR(100) NULL,
     TRIP_DESC        VARCHAR(255) NULL,
     EXP_LMT          DECIMAL(19, 2) DEFAULT 0 NULL,
     TRAVELER_DTL_ID  BIGINT(19) NULL,
     TEM_PROFILE_ID   BIGINT(19) NULL,
     FRM_ADDR_LINE1   VARCHAR(50) NULL,
     FRM_ADDR_LINE2   VARCHAR(50) NULL,
     FRM_CITY_NM      VARCHAR(30) NULL,
     FRM_STATE_CD     VARCHAR(40) NULL,
     FRM_COUNTRY_CD   VARCHAR(40) NULL,
     TO_ADDR_LINE1    VARCHAR(50) NULL,
     TO_ADDR_LINE2    VARCHAR(50) NULL,
     TO_CITY_NM       VARCHAR(30) NULL,
     TO_STATE_CD      VARCHAR(40) NULL,
     TO_COUNTRY_CD    VARCHAR(40) NULL,
     PAYMENT_METHOD	  VARCHAR(15) NULL,
     REASON_CD        VARCHAR(255) NULL,
     JOB_CLS_CD       VARCHAR(255) NULL,
     TITLE_CD         VARCHAR(255) NULL,
     COMMENTS         VARCHAR(255) NULL,
     FDOC_NXT_EXP_NBR DECIMAL(7, 0),
     VER_NBR          DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID           VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_RELO_DOC_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_RELO_DOC_T_TR1 FOREIGN KEY (TRAVELER_DTL_ID) REFERENCES
     TEM_TRAVELER_DTL_T(ID),
     CONSTRAINT TEM_RELO_DOC_T_TR2 FOREIGN KEY (TRIP_TYP_CD) REFERENCES
     TEM_TRIP_TYP_T(CODE),
     CONSTRAINT TEM_RELO_DOC_T_TR3 FOREIGN KEY (REASON_CD) REFERENCES
     TEM_RELO_REASON_T(RELO_REASON_CD),
     CONSTRAINT TEM_RELO_DOC_T_TR4 FOREIGN KEY (JOB_CLS_CD) REFERENCES
     TEM_JOB_CLASS_T(JOB_CLS_CD),
     CONSTRAINT TEM_RELO_DOC_T_TR5 FOREIGN KEY (PRIMARY_DEST_ID)
     REFERENCES TEM_PER_DIEM_T(ID),
     CONSTRAINT TEM_RELO_DOC_T_TP1 PRIMARY KEY(FDOC_NBR)
  );

CREATE TABLE IF NOT EXISTS TEM_PER_DIEM_EXP_T
  (
     ID              BIGINT(19) NOT NULL,
     FDOC_NBR        VARCHAR(14) NOT NULL,
     COUNTRY         VARCHAR(100) NULL,
     COUNTY_CD       VARCHAR(100) NULL,
     PRI_DEST        VARCHAR(100) NULL,
     BREAKFAST_IND   VARCHAR(1) NULL,
     LUNCH_IND       VARCHAR(1) NULL,
     DINNER_IND      VARCHAR(1) NULL,     
     SINGLE_DAY_IND  VARCHAR(1) NULL,
     BREAKFAST_VAL   DECIMAL(19, 2) DEFAULT 0 NULL,
     LUNCH_VAL       DECIMAL(19, 2) DEFAULT 0 NULL,
     DINNER_VAL      DECIMAL(19, 2) DEFAULT 0 NULL,
     INCIDENTALS_VAL DECIMAL(19, 2) DEFAULT 0 NULL,
     PERSONAL        VARCHAR(1) NULL,
     MILES           BIGINT(19) NULL,
     MILEAGE_RT_ID   BIGINT(19) NOT NULL,
     LODGING         DECIMAL(19, 2) DEFAULT 0 NULL,
     ACCOM_TYP_CD    VARCHAR(4) NULL,
     ACCOM_NM        VARCHAR(255) NULL,
     ACCOM_PH        VARCHAR(20) NULL,
     ACCOM_ADDRESS   VARCHAR(255) NULL,
     MLG_DT          DATE NULL,
     PER_DIEM_ID     BIGINT(19) NULL,
     VER_NBR         DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID          VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_PER_DIEM_EXP_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_PER_DIEM_EXP_T_TR1 FOREIGN KEY (MILEAGE_RT_ID) REFERENCES
     TEM_MILEAGE_RATE_T(ID),
     CONSTRAINT TEM_PER_DIEM_EXP_T_TR2 FOREIGN KEY (PER_DIEM_ID) REFERENCES
     TEM_PER_DIEM_T(ID),
     CONSTRAINT TEM_PER_DIEM_EXP_T_TR3 FOREIGN KEY (ACCOM_TYP_CD) REFERENCES
     TEM_ACCOMM_TYP_T(CODE),
     CONSTRAINT TEM_PER_DIEM_EXP_T_TP1 PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_PROFILE_T
  (
     PROFILE_ID               BIGINT(19) NOT NULL,
     PRNCPL_ID                VARCHAR(40) NULL,
     CUSTOMER_NUM             VARCHAR(40) NULL,
     DRIVE_LIC_NUM            VARCHAR(20) NULL,
     DRIVE_LIC_STATE          VARCHAR(2) NULL,
     DRIVE_LIC_EXP_DT         DATE NULL,
     CITIZENSHIP              VARCHAR(40) NULL,
     UPDATED_BY               VARCHAR(40) NULL,
     LAST_UPDATE              DATE NULL,
     TRAVELER_TYP_CD          VARCHAR(3) NOT NULL,
     DATE_OF_BIRTH            DATE NOT NULL,
     GENDER                   VARCHAR(1) NOT NULL,
     MOT_VEH_REC_CHK          VARCHAR(1) NULL,
     NON_RES_ALIEN            VARCHAR(1) NULL,
     NOTIFY_TA_FINAL          VARCHAR(1) NULL,
     NOTIFY_TA_STATUS_CHANGE  VARCHAR(1) NULL,
     NOTIFY_TER_FINAL         VARCHAR(1) NULL,
     NOTIFY_TER_STATUS_CHANGE VARCHAR(1) NULL,
     HOME_DEPT_ORG_CD         VARCHAR(40) NOT NULL,
     HOME_DEPT_COA_CD         VARCHAR(40) NOT NULL,
     CHART_CD                 VARCHAR(40) NULL,
     ACCOUNT_CD               VARCHAR(40) NULL,
     SUB_ACCOUNT_CD           VARCHAR(40) NULL,
     PROJ_CD                  VARCHAR(40) NULL,
     FIRST_NM                 VARCHAR(30) NULL,
     MIDDLE_NM                VARCHAR(30) NULL,
     LAST_NM                  VARCHAR(30) NULL,
     PHONE_NBR                VARCHAR(20) NULL,
     EMAIL_ADDR               VARCHAR(60) NULL,
     EMP_ID       		      VARCHAR(20) NULL,
     ACTV_IND                 VARCHAR(1) NOT NULL,
     VER_NBR                  DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID                   VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_PROFILE_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_PROFILE_T_TR1 FOREIGN KEY (TRAVELER_TYP_CD) REFERENCES
     TEM_TRAVELER_TYP_T(CODE),
     CONSTRAINT TEM_PROFILE_T_TP1 PRIMARY KEY(PROFILE_ID)
  );

CREATE TABLE IF NOT EXISTS TEM_PROFILE_ARRANGER_T
  (
     ARRANGER_ID BIGINT(19) NOT NULL,
     PRNCPL_ID   VARCHAR(40) NULL,
     PROFILE_ID  BIGINT(19) NOT NULL,
     TA_IND      VARCHAR(1) NOT NULL,
     TR_IND      VARCHAR(1) NOT NULL,
     ACTV_IND    VARCHAR(1) NOT NULL,
     PRIMARY_IND VARCHAR(1) NOT NULL,
     VER_NBR     DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID      VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_PROFILE_ARRANGER_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_PROFILE_ARRANGER_T_TR1 FOREIGN KEY (PROFILE_ID) REFERENCES
     TEM_PROFILE_T(PROFILE_ID),
     CONSTRAINT TEM_PROFILE_ARRANGER_T_TP1 PRIMARY KEY(ARRANGER_ID)
  );

CREATE TABLE IF NOT EXISTS TEM_TRVL_CARD_TYP_T (
		CODE 					VARCHAR(4) 	NOT NULL,
    	NM						VARCHAR(40) NOT NULL,
  		ACTV_IND				VARCHAR(1)	NOT NULL,
		VER_NBR					DECIMAL(8,0)	default 1	NOT NULL,
		OBJ_ID					VARCHAR(36)	NOT NULL,
  		CONSTRAINT TEM_TRVL_CARD_TYP_T_TC0 UNIQUE (OBJ_ID),
		CONSTRAINT TEM_TRVL_CARD_TYP_T_TP1 PRIMARY KEY(CODE)
);

CREATE TABLE IF NOT EXISTS TEM_CREDIT_CARD_AGENCY_T (
		ID						BIGINT(19)	NOT NULL,
		CREDIT_CARD_AGENCY_CODE	VARCHAR(4)	NOT NULL,
		TRAVEL_CARD_TYPE_CD		VARCHAR(4)	NOT NULL,
		PAYMENT_IND				VARCHAR(1)	NOT NULL,
		CREDIT_CARD_AGENCY_NAME	VARCHAR(45)	NOT NULL,
		ADDRESS1				VARCHAR(45)	NULL,
		ADDRESS2				VARCHAR(45)	NULL,
		CITY					VARCHAR(45)	NULL,
		STATE					VARCHAR(2)	NULL,
		ZIPCODE					VARCHAR(20)	NULL,
		EMAIL					VARCHAR(90)	NULL,
		PHONE					VARCHAR(40)	NULL,
		CONTACT_NAME			VARCHAR(45)	NULL,
		TYPE_CODE				VARCHAR(1)	NULL,
		PRE_RECONCILED			VARCHAR(1)	NULL,
		ENABLE_NON_REIMBURSABLE	VARCHAR(1)	NULL,
		VENDOR_NUMBER			VARCHAR(20)	NULL,
		FOREIGN_COMPANY			VARCHAR(1)	NOT NULL,
		ACTV_IND				VARCHAR(1)	NOT NULL,
		VER_NBR					DECIMAL(8,0)	default 1	NOT NULL,
		OBJ_ID					VARCHAR(36)	NOT NULL,
		CONSTRAINT TEM_CREDIT_CARD_AGENCY_T_TC0 UNIQUE (OBJ_ID),
		CONSTRAINT TEM_CREDIT_CARD_AGENCY_T_TR1 FOREIGN KEY (TRAVEL_CARD_TYPE_CD) REFERENCES TEM_TRVL_CARD_TYP_T(CODE),
		CONSTRAINT TEM_CREDIT_CARD_AGENCY_T_TP1 PRIMARY KEY(ID)
);
  
CREATE TABLE IF NOT EXISTS TEM_PROFILE_ACCOUNT_T
  (
     ACCOUNT_ID     BIGINT(19) NOT NULL,
     PROFILE_ID     BIGINT(19) NOT NULL,
     CARD_ID     BIGINT(19) NOT NULL,
     NAME           VARCHAR(50) NOT NULL,
     ACCOUNT_NBR    VARCHAR(50) NOT NULL,
     EXP_DATE       DATE NULL,
     EFFECTIVE_DATE DATE NULL,
     NOTE           VARCHAR(500) NULL,
     ACTV_IND       VARCHAR(1) NOT NULL,
     VER_NBR        DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID         VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_PROFILE_ACCOUNT_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_PROFILE_ACCOUNT_T_TR1 FOREIGN KEY (PROFILE_ID) REFERENCES
     TEM_PROFILE_T(PROFILE_ID),
     CONSTRAINT TEM_PROFILE_ACCOUNT_T_TR2 FOREIGN KEY (CARD_ID) REFERENCES
     TEM_CREDIT_CARD_AGENCY_T(ID),
     CONSTRAINT TEM_PROFILE_ACCOUNT_T_TP1 PRIMARY KEY(ACCOUNT_ID)
  );

CREATE TABLE IF NOT EXISTS TEM_PROFILE_CUST_T
  (
     CUST_NBR        VARCHAR(40) NULL,
     CUSTOMER_TYP_CD VARCHAR(2) NULL,
     CUST_NM         VARCHAR(19) NULL,
     CUST_PHONE_NBR  VARCHAR(40) NULL,
     CUST_TAX_NBR    VARCHAR(40) NULL,
     CUST_TAX_TYP_CD VARCHAR(4) NULL,
     ACTV_IND        VARCHAR(1) NOT NULL,
     ADDRESS_NAME    VARCHAR(40) NULL,
     ADDR_LINE_1     VARCHAR(50) NULL,
     ADDR_LINE_2     VARCHAR(50) NULL,
     CITY_NM         VARCHAR(30) NULL,
     STATE_CD        VARCHAR(40) NULL,
     ZIP_CD          VARCHAR(10) NULL,
     INTL_PROV_NM    VARCHAR(45) NULL,
     CUST_EMAIL_ADDR VARCHAR(40) NULL,
     VER_NBR         DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID          VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_PROFILE_CUST_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_PROFILE_CUST_T_TR1 FOREIGN KEY (CUSTOMER_TYP_CD) REFERENCES
     AR_CUST_TYP_T(CUST_TYP_CD),
     CONSTRAINT TEM_PROFILE_CUST_T_TP1 PRIMARY KEY(CUST_NBR)
  );

CREATE TABLE IF NOT EXISTS TEM_PROFILE_ADDR_T
  (
     TEM_PROFILE_ID BIGINT(19) NOT NULL,
     ADDR_LINE_1    VARCHAR(50) NULL,
     ADDR_LINE_2    VARCHAR(50) NULL,
     CITY_NM        VARCHAR(30) NULL,
     STATE_CD       VARCHAR(40) NULL,
     ZIP_CD         VARCHAR(40) NULL,
     COUNTRY_CD     VARCHAR(40) NULL,
     VER_NBR        DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID         VARCHAR(36) NOT NULL,
     CUST_ADDR_ID   BIGINT(19) NULL,
     CONSTRAINT TEM_PROFILE_ADDR_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_PROFILE_ADDR_T_TP1 PRIMARY KEY(TEM_PROFILE_ID)
  );

CREATE TABLE IF NOT EXISTS TEM_ADV_PMNT_RSN_T
  (
     CODE        VARCHAR(2) NOT NULL,
     DESCRIPTION VARCHAR(100) NULL,
     ACTV_IND    VARCHAR(1) NOT NULL,
     VER_NBR     DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID      VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_ADV_PMNT_RSN_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_ADV_PMNT_RSN_T_TP1 PRIMARY KEY(CODE)
  );

CREATE TABLE IF NOT EXISTS TEM_ACCT_DOC_REL_T
  (
     ID           BIGINT(19) NOT NULL,
     DOC_NBR      VARCHAR(40) NOT NULL,
     REL_DOC_NBR  VARCHAR(40) NOT NULL,
     PRNCPL_ID    VARCHAR(40) NULL,
     DESCRIPTION  VARCHAR(100) NULL,
     ACTV_IND     VARCHAR(1) NOT NULL,
     VER_NBR      DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID       VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_ACCT_DOC_REL_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_ACCT_DOC_REL_T_TP1 PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_ATTENDEE_T
  (
     ID            BIGINT(19) NOT NULL,
     FDOC_NBR      VARCHAR(14) NOT NULL,
     ATTENDEE_TYPE VARCHAR(10) NULL,
     COMPANY       VARCHAR(40) NULL,
     TITLE         VARCHAR(40) NULL,
     NAME          VARCHAR(40) NULL,
     VER_NBR       DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID        VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_ATTENDEE_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_ATTENDEE_T_TP1 PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_PURPOSE_T
  (
     DOCUMENT_TYPE       VARCHAR(4) NOT NULL,
     PURPOSE_CODE        VARCHAR(4) NOT NULL,
     PURPOSE_NAME        VARCHAR(40) NULL,
     PURPOSE_DESCRIPTION VARCHAR(100) NULL,
     REVIEW_REQUIRED_IND VARCHAR(1) NULL,
     ROW_ACTV_IND        VARCHAR(1) NOT NULL,
     VER_NBR             DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID              VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_PURPOSE_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_PURPOSE_T_TP1 PRIMARY KEY(PURPOSE_CODE)
  );

CREATE TABLE IF NOT EXISTS TEM_ENT_DOC_T
  (
     FDOC_NBR               VARCHAR(14) NOT NULL,
     TRVL_ID                VARCHAR(19) NULL,
     HOST_TEM_PROFILE_ID    BIGINT(19) NULL,
     HOST_NAME 				VARCHAR(50) NULL,
     TITLE                  VARCHAR(100) NULL,
     TRAVELER_DTL_ID        BIGINT(19) NULL,
     TEM_PROFILE_ID         BIGINT(19) NULL,
     TRIP_TYP_CD            VARCHAR(3) NULL,
     TRIP_BGN_DT            DATE NULL,
     TRIP_END_DT            DATE NULL,
     PRIMARY_DEST_ID        BIGINT(19) NULL,
     PRIMARY_DEST_NAME      VARCHAR(100) NULL,
     PRIMARY_DEST_CNTRY_ST  VARCHAR(100) NULL,
     PRIMARY_DEST_CNTY      VARCHAR(100) NULL,
     HOST_CERTIFIED         VARCHAR(1) NULL,
     NON_EMPLOYEE_CERTIFIED VARCHAR(1) NULL,
     SPOUSE_INCLUDED        VARCHAR(1) NULL,
     DESCRIPTION            VARCHAR(255) NULL,
     PURPOSE_CODE           VARCHAR(4) NULL,
     PAYMENT_METHOD			VARCHAR(15) NULL,
     ATTENDEE_LIST_ATTACHED VARCHAR(1) NULL,
     NUMBER_ATTENDEES       BIGINT(19) NULL,
     FDOC_NXT_EXP_NBR       DECIMAL(7, 0) NULL,
     EXP_LMT                DECIMAL(19, 2) DEFAULT 0 NULL,
     VER_NBR                DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID                 VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_ENT_DOC_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_ENT_DOC_T_TP1 PRIMARY KEY(FDOC_NBR),
     CONSTRAINT TEM_ENT_DOC_T_TR1 FOREIGN KEY (TRAVELER_DTL_ID) REFERENCES
     TEM_TRAVELER_DTL_T(ID),
     CONSTRAINT TEM_ENT_DOC_T_TR2 FOREIGN KEY (TRIP_TYP_CD) REFERENCES
     TEM_TRIP_TYP_T(CODE),
     CONSTRAINT TEM_ENT_DOC_T_TR3 FOREIGN KEY (PURPOSE_CODE) REFERENCES
     TEM_PURPOSE_T(PURPOSE_CODE),
     CONSTRAINT TEM_ENT_DOC_T_TR4 FOREIGN KEY (PRIMARY_DEST_ID) REFERENCES
     TEM_PER_DIEM_T(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_TRVL_ARRANGER_DOC_T
  (
     FDOC_NBR    VARCHAR(14) NOT NULL,
     ARRANGER_ID VARCHAR(40) NOT NULL,
     PROFILE_ID  BIGINT(19) NOT NULL,
     TA_IND      VARCHAR(1) NOT NULL,
     TR_IND      VARCHAR(1) NOT NULL,
     RESIGN_IND  VARCHAR(1) NOT NULL,
     PRIMARY_IND VARCHAR(1) NOT NULL,
     VER_NBR     DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID      VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_TRVL_ARRANGER_DOC_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_TRVL_ARRANGER_DOC_T_TP1 PRIMARY KEY(FDOC_NBR)
  );
  
CREATE TABLE IF NOT EXISTS TEM_TRP_ACCT_INFO_T 
	(
		ID				BIGINT(19)	NOT NULL,
		AGENCY_ID		BIGINT(19)	NULL,
		FIN_COA_CD		VARCHAR(2) 	NULL,
		ACCT_NBR		VARCHAR(7)	NULL,
		SUB_ACCT_NBR	VARCHAR(5)	NULL,
		OBJ_CD			VARCHAR(4)	NULL,
		SUB_OBJ_CD		VARCHAR(3)	NULL,
		PRJ_CD			VARCHAR(10)	NULL,
		ORG_REF			VARCHAR(8)	NULL,
		AMOUNT			DECIMAL(8,2)	NULL,
		VER_NBR			DECIMAL(8,0)	DEFAULT 1	NOT NULL,
		OBJ_ID			VARCHAR(36)	NOT NULL,
		CONSTRAINT TEM_TRP_ACCT_INFO_T_TC0 UNIQUE (OBJ_ID),
		CONSTRAINT TEM_TRP_ACCT_INFO_T_TP1 PRIMARY KEY(ID)
	);

CREATE TABLE IF NOT EXISTS TEM_AGENCY_STAGING_T 
	(
		ID						BIGINT(19)		NOT NULL,
		ERROR_CD				VARCHAR(40)		NULL,
        DUP_REC_ID              BIGINT(19)      NULL,
		IMPORT_BY				VARCHAR(3)		NULL,
		PROFILE_ID				BIGINT(19)		NULL,
		AGENCY_DATA_ID			BIGINT(19)		NULL,
        card_id                 BIGINT(19)      NULL,
        SRCH_FIN_COA_CD         VARCHAR(2)      NULL,
        SRCH_ACCT_NBR           VARCHAR(7)      NULL,
        SRCH_SUB_ACCT_NBR       VARCHAR(5)      NULL,
		CREDIT_AGENCY_CD		VARCHAR(4)		NULL,
		AGENCY					VARCHAR(20)		NULL,
		OTHER_CO_NM				VARCHAR(30)		NULL,
		AGENCY_FL_NM			VARCHAR(50)		NULL,
		STAGING_FILE_NM			VARCHAR(60)		NULL,
		MERCH_NM				VARCHAR(40)		NULL,
		BILLING_CYCLE_DT		DATE			NULL,
		TRIP_ID					VARCHAR(12)		NULL,
		TRIP_INV_NBR			VARCHAR(20)		NULL,
		TRIP_TRV_TYP_ID			VARCHAR(1)		NULL,
		OTHER_AMT				DECIMAL(8,2)	NULL,
		TRAVELER_NM				VARCHAR(50)		NOT NULL,
		TRAVELER_ID				VARCHAR(40)		NULL,
		TRAVELER_NTWK_ID		VARCHAR(9)		NULL,
		TRP_EXP_AMT				DECIMAL(8,2)	NULL,
		ALT_TRP_ID				VARCHAR(20)		NULL,
		TRP_ARR_NM				VARCHAR(50)		NULL,
		GRP_OBJ_CD				VARCHAR(20)		NULL,
		DI_CD					VARCHAR(4)		NULL,
		TRP_DPT_DT				DATE			NULL,
		TRP_RTRN_DT				DATE			NULL,
		FARE_SVR_CD				VARCHAR(1)		NULL,
		AIR_BK_DT				DATE			NULL,
		AIR_CARR_CD				VARCHAR(3)		NULL,
		AIR_TKT_NBR				VARCHAR(20)		NULL,
		PNR_NBR					VARCHAR(20)		NULL,
		AIR_TKT_CLASS			VARCHAR(20)		NULL,
		AIR_TRANS_AMT			DECIMAL(8,2)	NULL,
		AIR_BASE_FARE_AMT		DECIMAL(8,2)	NULL,
		AIR_TX_AMT				DECIMAL(8,2)	NULL,
		AIR_LOW_FARE_AMT		DECIMAL(8,2)	NULL,
		AIR_RSN_CD				VARCHAR(1)		NULL,
		AIR_SEG_ID				VARCHAR(100)	NULL,
		AIR_DEST_CD				VARCHAR(3)		NULL,
		AIR_SRVC_FEE_NBR		VARCHAR(20)		NULL,
		AIR_SRVC_FEE_AMT		DECIMAL(8,2)	NULL,
		TRANS_ID				VARCHAR(40)		NULL,
		LDG_ITN_NBR				VARCHAR(20)		NULL,
		LDG_PRPY_DT				DATE			NULL,
		LDG_AMT					DECIMAL(8,2)	NULL,
		LDG_PRPY_NBR			VARCHAR(3)		NULL,
		LDG_PRP_NM				VARCHAR(30)		NULL,
		TRP_LDG_ARRV_DT			DATE			NULL,
		LDG_DEPT_DT				DATE			NULL,
		LDG_BK_DT				DATE			NULL,
		LDG_PRP_CITY_NM			VARCHAR(30)		NULL,
		LDG_PRP_STATE_CD		VARCHAR(3)		NULL,
		LDG_PRP_COUNTRY_NM		VARCHAR(40)		NULL,
		RNT_CAR_ITN_NBR			VARCHAR(255)	NULL,
		RNT_CAR_AMT				DECIMAL(8,2)	NULL,
		RNT_CAR_NMR_DAYS		VARCHAR(3)		NULL,
		RNT_CAR_CO_NM			VARCHAR(30)		NULL,
		RNT_CAR_OPN_DT			DATE			NULL,
		RNT_CAR_CLOSE_DT		DATE			NULL,
		RNT_CAR_FUEL_AMT		DECIMAL(8,2)	NULL,
		RNT_CAR_ADD_AMT			DECIMAL(8,2)	NULL,
		RNT_CAR_TX_AMT			DECIMAL(8,2)	NULL,
		RNT_CAR_SRCHRG_AMT		DECIMAL(8,2)	NULL,
		RNT_CAR_GOVR_SRCHRG_AMT	DECIMAL(8,2)	NULL,
		RNT_CAR_BILL_AMT		DECIMAL(8,2)	NULL,
		RNT_CAR_DTL				VARCHAR(100)	NULL,
		REG_CO_NM				VARCHAR(50)		NULL,
		REG_AMT					DECIMAL(8,2)	NULL,
		TRANS_POST_DT			DATE			NULL,
		OBJ_VER_NBR				VARCHAR(255)	NULL,
		CREATION_TS				DATE			NULL,
		PROCESSING_TS			DATE			NULL,
		MV_TO_HISTORY			VARCHAR(1)		NULL,
		VER_NBR					DECIMAL(8,0)	DEFAULT 1	NOT NULL,
		OBJ_ID					VARCHAR(36)	NOT NULL,
		CONSTRAINT TEM_AGENCY_STAGING_T_TC0 UNIQUE (OBJ_ID),
		CONSTRAINT TEM_AGENCY_STAGING_T_TP1 PRIMARY KEY(ID)
	);

CREATE TABLE IF NOT EXISTS TEM_CREDIT_CARD_STAGING_T 
	(
		ID					BIGINT(19)	NOT NULL,
		CREDIT_CARD_KEY		VARCHAR(38)	NULL,
		TRAVELER_ID			BIGINT(20)	NULL,
		AIR_NUMBER			VARCHAR(3)	NULL,
		BILLING_CYCLE_DT	DATE		NULL,
		CREDIT_AGENCY_CD	VARCHAR(4)	NULL,
     	CC_AGENCY_ID  		BIGINT(19) 	NULL,
		CREATION_DT			DATE		NULL,
		CREATION_TIMESTAMP	TIMESTAMP	NULL,
		DEPARTURE_DT		DATE		NULL,
		IDENTIFIER			VARCHAR(1)	NULL,
		RECONCILIATION_DT	DATE		NULL,
		REFERENCE_NBR		VARCHAR(23)	NULL,
		SEQUENCE_NBR		VARCHAR(3)	NULL,
		TICKET_NBR			VARCHAR(16)	NULL,
		TRANSACTION_AMOUNT	DECIMAL(15,4)	NULL,
		TRANSACTION_CD		VARCHAR(1)	NULL,
		TRANSACTION_DT		DATE		NOT NULL,
		TRAVELER_NM			VARCHAR(40)	NULL,
		TYPE_CD				VARCHAR(1)	NULL,
		DV_EXP_CD				VARCHAR(2)	NULL,
		DV_DOC_NUM			VARCHAR(14) NULL,
		MERCHANT_NM			VARCHAR(40)	NULL,
		BANK_POST_DT		DATE		NULL,
		PROCESSING_TS			DATE			NULL,
		MV_TO_HISTORY		VARCHAR(1)		NULL,
		LOC					VARCHAR(40)		NULL,
		SRVC_FEE_NBR		VARCHAR(20)		NULL,
		ITN_NBR				VARCHAR(20)		NULL,
		ERROR_CD			VARCHAR(40)		NULL,
		IMPORT_BY				VARCHAR(3)		NULL,
		STAGING_FILE_NM		VARCHAR(60)		NULL,
     	PROFILE_ID  		BIGINT(19) 		NULL,
		VER_NBR				DECIMAL(8,0) default 1 NOT NULL,
		OBJ_ID				VARCHAR(36)	NOT NULL,
		CONSTRAINT TEM_CREDIT_CARD_STAGING_T_TC0 UNIQUE (OBJ_ID),
		CONSTRAINT TEM_CREDIT_CARD_STAGING_T_TP1 PRIMARY KEY(ID)
	);
	
CREATE TABLE IF NOT EXISTS TEM_HIST_EXP_T 
(
	ID					BIGINT(19)		NOT NULL,
	CC_AGENCY_ID		BIGINT(19)		NULL,
	IMPORT_DT			DATE			NULL,
	COMPANY				VARCHAR(40)		NULL,
	LOCATION			VARCHAR(40)		NULL,
	DV_EXP_CD			VARCHAR(2)		NULL,
	AMOUNT				DECIMAL(8,2)	NULL,
	TRANS_POST_DT		DATE			NULL,
	DESCRIPTION			VARCHAR(25)		NULL,
	RECON_DT			DATE			NULL,
	RECONCILED			VARCHAR(1)		NULL,
	CURR_RT				DECIMAL(8,2)	NULL,
	CONV_AMT			DECIMAL(8,2)	NULL,
	REIMB				VARCHAR(1)		NULL,
	MISSING_RCPT		VARCHAR(1)		NULL,
	ASSIGNED			VARCHAR(1)		NULL,
	CC_STAGE_ID			BIGINT(19)		NULL,
	AGENCY_STAGE_ID		BIGINT(19)		NULL,
	PROFILE_ID			BIGINT(19)		NULL,
	DOC_NBR             VARCHAR(14) 	NULL,
	DOC_TYPE            VARCHAR(10) 	NULL,
	EXP_NTF_DT			DATE			NULL,
	TRIP_ID				VARCHAR(255)	NULL,
	CCA_CD            	VARCHAR(4) 		NULL,
	TRAVEL_EXP_NM      	VARCHAR(25) 	NULL,
	ver_nbr				DECIMAL(8,0)	default 1	NOT NULL,
	obj_id				VARCHAR(36)		NOT NULL,
	CONSTRAINT TEM_HIST_EXP_T_TC0 UNIQUE (obj_id),
	CONSTRAINT TEM_HIST_EXP_T_TR1 FOREIGN KEY (CC_AGENCY_ID) REFERENCES TEM_CREDIT_CARD_AGENCY_T (ID),
	CONSTRAINT TEM_HIST_EXP_T_TR2 FOREIGN KEY (DV_EXP_CD) REFERENCES FP_DV_EXP_TYP_T (DV_EXP_CD),
	CONSTRAINT TEM_HIST_EXP_T_TP1 PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS TEM_ACCT_LINES_T
  (
     ID					BIGINT(19)	NOT NULL,
  	 FDOC_NBR           VARCHAR(14) DEFAULT '' NOT NULL,
     FDOC_LINE_NBR      DECIMAL(7, 0) DEFAULT '0' NOT NULL,
     FDOC_LN_TYP_CD     VARCHAR(1) DEFAULT '' NOT NULL,
     OBJ_ID             VARCHAR(36) NOT NULL,
     VER_NBR            DECIMAL(8, 0) DEFAULT '1' NOT NULL,
     FIN_COA_CD         VARCHAR(2) DEFAULT NULL,
     ACCOUNT_NBR        VARCHAR(7) DEFAULT NULL,
     FDOC_POST_YR       DECIMAL(4, 0) DEFAULT NULL,
     FIN_OBJECT_CD      VARCHAR(4) DEFAULT NULL,
     FIN_BALANCE_TYP_CD VARCHAR(2) DEFAULT NULL,
     FDOC_LINE_AMT      DECIMAL(19, 2) DEFAULT NULL,
     SUB_ACCT_NBR       VARCHAR(5) DEFAULT NULL,
     FIN_SUB_OBJ_CD     VARCHAR(3) DEFAULT NULL,
     PROJECT_CD         VARCHAR(10) DEFAULT NULL,
     ORG_REFERENCE_ID   VARCHAR(8) DEFAULT NULL,
     FS_REF_ORIGIN_CD   VARCHAR(2) DEFAULT NULL,
     FDOC_REF_NBR       VARCHAR(14) DEFAULT NULL,
     FDOC_REF_TYP_CD    VARCHAR(4) DEFAULT NULL,
     FDOC_OVERRIDE_CD   VARCHAR(100) DEFAULT NULL,
     FDOC_LINE_DESC     VARCHAR(40) DEFAULT NULL,
     FDOC_LINE_DBCR_CD  VARCHAR(1) DEFAULT NULL,
     TRN_ENCUM_UPDT_CD  VARCHAR(1) DEFAULT NULL,
     CARD_TYPE          VARCHAR(40) DEFAULT NULL,
     PRIMARY KEY (ID, FDOC_NBR, FDOC_LINE_NBR, FDOC_LN_TYP_CD),
     UNIQUE KEY TEM_ACCT_LINES_TC0 (OBJ_ID),
     KEY TEM_ACCT_LINES_TR3 (FDOC_POST_YR, FIN_COA_CD, FIN_OBJECT_CD),
     KEY TEM_ACCT_LINES_TR4 (FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR),
     KEY TEM_ACCT_LINES_TR5 (FDOC_POST_YR, FIN_COA_CD, ACCOUNT_NBR,
     FIN_OBJECT_CD, FIN_SUB_OBJ_CD),
     KEY TEM_ACCT_LINES_TR6 (PROJECT_CD),
     KEY TEM_ACCT_LINES_TR7 (FIN_BALANCE_TYP_CD),
     KEY TEM_ACCT_LINES_TR9 (FS_REF_ORIGIN_CD),
     CONSTRAINT TEM_ACCT_LINES_TR1 FOREIGN KEY (FIN_COA_CD) REFERENCES
     CA_CHART_T (FIN_COA_CD),
     CONSTRAINT TEM_ACCT_LINES_TR2 FOREIGN KEY (FIN_COA_CD, ACCOUNT_NBR)
     REFERENCES CA_ACCOUNT_T (FIN_COA_CD, ACCOUNT_NBR),
     CONSTRAINT TEM_ACCT_LINES_TR3 FOREIGN KEY (FDOC_POST_YR, FIN_COA_CD,
     FIN_OBJECT_CD) REFERENCES CA_OBJECT_CODE_T (UNIV_FISCAL_YR, FIN_COA_CD,
     FIN_OBJECT_CD),
     CONSTRAINT TEM_ACCT_LINES_TR4 FOREIGN KEY (FIN_COA_CD, ACCOUNT_NBR,
     SUB_ACCT_NBR) REFERENCES CA_SUB_ACCT_T (FIN_COA_CD, ACCOUNT_NBR,
     SUB_ACCT_NBR),
     CONSTRAINT TEM_ACCT_LINES_TR5 FOREIGN KEY (FDOC_POST_YR, FIN_COA_CD,
     ACCOUNT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD) REFERENCES CA_SUB_OBJECT_CD_T (
     UNIV_FISCAL_YR, FIN_COA_CD, ACCOUNT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD),
     CONSTRAINT TEM_ACCT_LINES_TR6 FOREIGN KEY (PROJECT_CD) REFERENCES
     CA_PROJECT_T (PROJECT_CD),
     CONSTRAINT TEM_ACCT_LINES_TR7 FOREIGN KEY (FIN_BALANCE_TYP_CD) REFERENCES
     CA_BALANCE_TYPE_T (FIN_BALANCE_TYP_CD),
     CONSTRAINT TEM_ACCT_LINES_TR9 FOREIGN KEY (FS_REF_ORIGIN_CD) REFERENCES
     FS_ORIGIN_CODE_T (FS_ORIGIN_CD)
  );

CREATE TABLE IF NOT EXISTS TEM_TAX_RAM_DOC_T
  (
     FDOC_NBR           VARCHAR(14) DEFAULT '' NOT NULL,
     TRVL_ID            VARCHAR(19) NULL,
     TRVL_DTL_ID        INT NOT NULL,
     TRVL_ADV_ID        INT NOT NULL,
     AR_INV_DOC_NBR     VARCHAR(14) NOT NULL,
     TAX_RAM_NTC        VARCHAR(2000),
     INV_AMT            DECIMAL NOT NULL,
     OPN_AMT            DECIMAL NOT NULL,
     DUE_DT             DATE,
     OBJ_ID             VARCHAR(36) NOT NULL,
     VER_NBR            DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     PRIMARY KEY (FDOC_NBR)  
  );

CREATE TABLE IF NOT EXISTS TEM_AGENCY_SRVC_FEE_T 
(
	ID			BIGINT(19)		NOT NULL,
	DI_CD		VARCHAR(3)		NOT NULL,
	DI_DESC		VARCHAR(40)		NULL,
	CHART_CD	VARCHAR(2)		NOT NULL,
	ACCT_NBR	VARCHAR(7)		NOT NULL,
	OBJ_CD		VARCHAR(4)		NOT NULL,
	SRVC_FEE	DECIMAL(8,2)	NULL,
	ACTV_IND	VARCHAR(1)		NOT NULL,
	VER_NBR		DECIMAL(8,0)	DEFAULT 1	NOT NULL,
	OBJ_ID		VARCHAR(36)		NOT NULL,
	CONSTRAINT TEM_AGENCY_SRVC_FEE_T_TC0 UNIQUE (OBJ_ID),
	CONSTRAINT TEM_AGENCY_SRVC_FEE_T_TP1 PRIMARY KEY(ID)
);

-- KFSCNTRB-1148 START
CREATE TABLE IF NOT EXISTS TEM_CTS_CARD_APP_DOC_T 
 (
     FDOC_NBR                VARCHAR(14) NOT NULL,
     TEM_PROFILE_ID          BIGINT(19) NOT NULL,
     BNK_APPL_DT             DATE NULL,
     BNK_APPR_DT             DATE NULL,
     USR_AGRMNT              VARCHAR(1) NULL,
     VER_NBR                 DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID                  VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_E_CARD_APP_DOC_T_TP1 PRIMARY KEY(FDOC_NBR),
     CONSTRAINT TEM_E_CARD_APP_DOC_T_TC0 UNIQUE (OBJ_ID)
  );

CREATE TABLE IF NOT EXISTS TEM_CORP_CARD_APP_DOC_T 
 (
     FDOC_NBR                VARCHAR(14) NOT NULL,
     TEM_PROFILE_ID          BIGINT(19) NOT NULL,
     PSUEDO_NUM              VARCHAR(16) NULL,
     USR_AGRMNT              VARCHAR(1) NULL,
     DEPT_HD_AGRMNT          VARCHAR(1) NULL,
     VER_NBR                 DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID                  VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_CORP_CARD_APP_DOC_T_TP1 PRIMARY KEY(FDOC_NBR),
     CONSTRAINT TEM_CORP_CARD_APP_DOC_T_TC0 UNIQUE (OBJ_ID)
  );

CREATE TABLE IF NOT EXISTS TEM_CORP_CARD_PSEUDO_NUM_T
  (
     NUM				 	 BIGINT(19) NOT NULL,
     VER_NBR                 DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID                  VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_CORP_CARD_PSEUDO_NUM_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_CORP_CARD_PSEUDO_NUM_T_TP1 PRIMARY KEY(NUM)
  );
  
CREATE TABLE IF NOT EXISTS TEM_CORP_CARD_PSEUDO_NUM_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );
-- KFSCNTRB-1148 END

-- KFSCNTRB-1149 START
CREATE TABLE IF NOT EXISTS TEM_CC_IMP_EXP_CLR_T
  (
     FDOC_NBR      VARCHAR(14) NOT NULL,
     VER_NBR       DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID        VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_CC_IMP_EXP_CLR_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_CC_IMP_EXP_CLR_T_TP1 PRIMARY KEY(FDOC_NBR)
  );

CREATE TABLE IF NOT EXISTS TEM_CC_IMP_EXP_CLR_DTL_T
  (
     FDOC_NBR      VARCHAR(14) NOT NULL,
     CC_STG_DAT_ID   BIGINT(19) NOT NULL,
     VER_NBR       DECIMAL(8, 0) DEFAULT 1 NOT NULL,
     OBJ_ID        VARCHAR(36) NOT NULL,
     CONSTRAINT TEM_CC_IMP_EXP_CLR_DTL_T_TC0 UNIQUE (OBJ_ID),
     CONSTRAINT TEM_CC_IMP_EXP_CLR_DTL_T_TP1 PRIMARY KEY(FDOC_NBR,CC_STG_DAT_ID)
  );
-- KFSCNTRB-1149 END 
  
  
CREATE TABLE IF NOT EXISTS TEM_TRVL_EXP_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_ATTENDEE_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_EXP_OBJ_CD_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_EM_CONT_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_PROFILE_EM_CONT_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_GRP_TRVLR_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_MILEAGE_RT_OBJ_CD_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_PER_DIEM_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_TRAVELER_PROF_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_TRIP_DTL_EST_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_MILEAGE_RT_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_PER_DIEM_EXP_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_PROFILE_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_PROFILE_ARRANGER_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_PROFILE_ACCOUNT_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TRVL_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_TRAVELER_DTL_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_TRVL_ADV_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_SPCL_CRCMSNCS_Q_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_SPCL_CRCMSNCS_S
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_ACCT_DOC_REL_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_ENTERTAINMENT_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_RELO_DOC_ID_SEQ
  (
     ID BIGINT(19) NOT NULL AUTO_INCREMENT,
     PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_AGENCY_STAGING_ID_SEQ 
	(
		ID BIGINT(19) NOT NULL AUTO_INCREMENT, 
		PRIMARY KEY(ID) 
	);

CREATE TABLE IF NOT EXISTS TEM_TRP_ACCT_INFO_ID_SEQ 
	(
		ID BIGINT(19) NOT NULL AUTO_INCREMENT, 
		PRIMARY KEY(ID) 
	);
CREATE TABLE IF NOT EXISTS TEM_CREDIT_CARD_AGENCY_ID_SEQ 
	(
		  ID bigint(19) NOT NULL AUTO_INCREMENT,
		  PRIMARY KEY(ID)
	);
CREATE TABLE IF NOT EXISTS TEM_CREDIT_CARD_STAGING_ID_SEQ 
	(
		  ID bigint(19) NOT NULL AUTO_INCREMENT, 
		  PRIMARY KEY(ID)
	);
CREATE TABLE IF NOT EXISTS TEM_HIST_EXP_ID_SEQ 
	(
		  ID bigint(19) NOT NULL AUTO_INCREMENT, 
		  PRIMARY KEY(ID)
	);

CREATE TABLE IF NOT EXISTS TEM_AGENCY_SRVC_FEE_ID_SEQ 
	(
		ID bigint(19) NOT NULL AUTO_INCREMENT, 
		PRIMARY KEY(ID) 
	);

CREATE TABLE IF NOT EXISTS TEM_EXP_TYP_ID_SEQ
  (
		ID BIGINT(19) NOT NULL AUTO_INCREMENT,
		PRIMARY KEY(ID)
  );

CREATE TABLE IF NOT EXISTS TEM_ACCT_LINES_ID_SEQ
(
		ID BIGINT(19) NOT NULL AUTO_INCREMENT,
		PRIMARY KEY(ID)
);