ALTER TABLE FP_DV_EXP_TYP_T ADD FIN_OBJECT_CD VARCHAR2(4) NULL;

ALTER TABLE AR_SYS_INFO_T ADD REFND_PMT_REAS_CD VARCHAR2(1) NULL;

ALTER TABLE AR_SYS_INFO_T ADD REFND_FIN_OBJECT_CD VARCHAR2(4) NULL;

ALTER TABLE AR_SYS_INFO_T ADD REFND_DOC_LOC_CD VARCHAR2(2) NULL;

ALTER TABLE FP_DV_PMT_REAS_T ADD AR_REFND_IND VARCHAR2(1)  DEFAULT 'N' NOT NULL;

ALTER TABLE AR_APPLICATION_DOC_T ADD REFND_FDOC_NBR VARCHAR2(14) NULL;

ALTER TABLE AR_NON_INV_T ADD REFND_IND VARCHAR2(1)  DEFAULT 'N' NOT NULL;

ALTER TABLE FP_DV_DOC_T ADD REFND_IND VARCHAR2(1)  DEFAULT 'N' NOT NULL;

ALTER TABLE AR_CUST_T MODIFY (CUST_NBR VARCHAR2(40));

ALTER TABLE AR_DOC_HDR_T MODIFY (CUST_NBR VARCHAR2(40));

ALTER TABLE AR_CUST_ADDR_T MODIFY (CUST_NBR VARCHAR2(40));

ALTER TABLE AR_NON_APLD_HLDG_T MODIFY (CUST_NBR VARCHAR2(40));

ALTER TABLE AR_CSH_CTRL_DTL_T MODIFY (CUST_NBR VARCHAR2(40));

ALTER TABLE AR_INV_RCURRNC_DTL_T MODIFY (CUST_NBR VARCHAR2(40));

ALTER TABLE AR_LOCKBOX_T MODIFY (CUST_NBR VARCHAR2(40));

ALTER TABLE AR_DOC_RCURRNC_T MODIFY (CUST_NBR VARCHAR2(40));

ALTER TABLE AR_INV_DOC_T ADD AGING_RPT_SENT_TM DATE;

ALTER TABLE FP_DV_TRVL_CO_NM_T ADD FRGN_CMPNY VARCHAR2(1) DEFAULT 'N' NOT NULL;