DROP TABLE krim_dlgn_attr_data_t
/

CREATE TABLE KRIM_ENTITY_CACHE_T ( 
    ENTITY_ID    	VARCHAR2(40) NOT NULL,
    PRNCPL_ID    	VARCHAR2(40) NOT NULL,
    PRNCPL_NM    	VARCHAR2(40),
    ENTITY_TYP_CD	VARCHAR2(40),
    FIRST_NM     	VARCHAR2(40),
    MIDDLE_NM    	VARCHAR2(40),
    LAST_NM      	VARCHAR2(40),
    PRSN_NM      	VARCHAR2(40),
    CAMPUS_CD    	VARCHAR2(40),
    PRMRY_DEPT_CD	VARCHAR2(40),
    EMP_ID       	VARCHAR2(40),
    LAST_UPDT_TS 	DATE,
    OBJ_ID       	VARCHAR2(36) NOT NULL,
    CONSTRAINT KRIM_ENTITY_CACHE_TP1 PRIMARY KEY(ENTITY_ID)
)
/

CREATE UNIQUE INDEX KRIM_ENTITY_CACHE_TC0
    ON KRIM_ENTITY_CACHE_T(OBJ_ID)
/

CREATE UNIQUE INDEX KRIM_ENTITY_CACHE_TC1
    ON KRIM_ENTITY_CACHE_T(PRNCPL_ID)
/
