--------------------------------------------------
insert into pur_reqs_itm_t (REQS_ITM_ID, OBJ_ID, VER_NBR, REQS_ID, ITM_LN_NBR, ITM_UOM_CD, ITM_QTY, ITM_CATLG_NBR, ITM_DESC, ITM_UNIT_PRC, ITM_RSTRC_IND, ITM_TYP_CD, ITM_AUX_PART_ID, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, PUR_COMM_CD)
values (111, '1EB99FC8-D55F-4537-6F01-EA5658607EX1', 10, 11, 1, 'UN', 3.00, null, 'Laptop', 6000.0000, 'N', 'ITEM', null, null, null, 'N', null);

insert into pur_reqs_itm_t (REQS_ITM_ID, OBJ_ID, VER_NBR, REQS_ID, ITM_LN_NBR, ITM_UOM_CD, ITM_QTY, ITM_CATLG_NBR, ITM_DESC, ITM_UNIT_PRC, ITM_RSTRC_IND, ITM_TYP_CD, ITM_AUX_PART_ID, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, PUR_COMM_CD)
values (112, 'C4A98C5B-7BE0-ABEA-E363-C98BC40AB6X2', 10, 11, 2, 'PR', 2.00, null, 'Desk & Chair',7000.0000, 'N', 'ITEM', null, null, null, 'N', null);

insert into pur_reqs_itm_t (REQS_ITM_ID, OBJ_ID, VER_NBR, REQS_ID, ITM_LN_NBR, ITM_UOM_CD, ITM_QTY, ITM_CATLG_NBR, ITM_DESC, ITM_UNIT_PRC, ITM_RSTRC_IND, ITM_TYP_CD, ITM_AUX_PART_ID, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, PUR_COMM_CD)
values (113, '5C02FF0E-D84F-EF64-84FB-224E71EDFCX3', 10, 11, null,  null, null, null, 'USPS', 750.0000, 'N', 'FRHT', null, null, null, 'N', null);

insert into pur_reqs_itm_t (REQS_ITM_ID, OBJ_ID, VER_NBR, REQS_ID, ITM_LN_NBR, ITM_UOM_CD, ITM_QTY, ITM_CATLG_NBR, ITM_DESC, ITM_UNIT_PRC, ITM_RSTRC_IND, ITM_TYP_CD, ITM_AUX_PART_ID, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, PUR_COMM_CD)
values (114, '6A76BF01-E76B-BE88-8D93-ABB8D46CA0X4', 10, 11, null,  null, null, null, 'USPS', 250.0000, 'N', 'SPHD', null, null, null, 'N', null);
--------------------------------------------------
insert into pur_reqs_itm_t (REQS_ITM_ID, OBJ_ID, VER_NBR, REQS_ID, ITM_LN_NBR, ITM_UOM_CD, ITM_QTY, ITM_CATLG_NBR, ITM_DESC, ITM_UNIT_PRC, ITM_RSTRC_IND, ITM_TYP_CD, ITM_AUX_PART_ID, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, PUR_COMM_CD)
values (121, '1EB99FC8-D55F-4537-6F01-EA5658607EY1', 10, 12, 1,  'UN', 3.00, null, 'Laptop',  6000.0000, 'N', 'ITEM', null, null, null, 'N', null);

insert into pur_reqs_itm_t (REQS_ITM_ID, OBJ_ID, VER_NBR, REQS_ID, ITM_LN_NBR, ITM_UOM_CD, ITM_QTY, ITM_CATLG_NBR, ITM_DESC, ITM_UNIT_PRC, ITM_RSTRC_IND, ITM_TYP_CD, ITM_AUX_PART_ID, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, PUR_COMM_CD)
values (122, 'C4A98C5B-7BE0-ABEA-E363-C98BC40AB6Y2', 10, 12, 2, 'PR', 2.00, null, 'Desk & Chair',  7000.0000, 'N', 'ITEM', null, null, null, 'N', null);

insert into pur_reqs_itm_t (REQS_ITM_ID, OBJ_ID, VER_NBR, REQS_ID, ITM_LN_NBR, ITM_UOM_CD, ITM_QTY, ITM_CATLG_NBR, ITM_DESC, ITM_UNIT_PRC, ITM_RSTRC_IND, ITM_TYP_CD, ITM_AUX_PART_ID, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, PUR_COMM_CD)
values (123, '5C02FF0E-D84F-EF64-84FB-224E71EDFCY3', 10, 12, null, null, null, null, 'USPS', 750.0000, 'N', 'FRHT', null, null, null, 'N', null);

insert into pur_reqs_itm_t (REQS_ITM_ID, OBJ_ID, VER_NBR, REQS_ID, ITM_LN_NBR, ITM_UOM_CD, ITM_QTY, ITM_CATLG_NBR, ITM_DESC, ITM_UNIT_PRC, ITM_RSTRC_IND, ITM_TYP_CD, ITM_AUX_PART_ID, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, PUR_COMM_CD)
values (124, '6A76BF01-E76B-BE88-8D93-ABB8D46CA0Y4', 10, 12, null, null, null, null, 'USPS', 250.0000, 'N', 'SPHD', null, null, null, 'N', null);
--------------------------------------------------
insert into pur_reqs_itm_t (REQS_ITM_ID, OBJ_ID, VER_NBR, REQS_ID, ITM_LN_NBR, ITM_UOM_CD, ITM_QTY, ITM_CATLG_NBR, ITM_DESC, ITM_UNIT_PRC, ITM_RSTRC_IND, ITM_TYP_CD, ITM_AUX_PART_ID, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, PUR_COMM_CD)
values (131, '1EB99FC8-D55F-4537-6F01-EA5658607EZ1', 10, 13, 1, 'UN', 3.00, null, 'Laptop',  6000.0000, 'N', 'ITEM',null, null, null, 'N', null);

insert into pur_reqs_itm_t (REQS_ITM_ID, OBJ_ID, VER_NBR, REQS_ID, ITM_LN_NBR, ITM_UOM_CD, ITM_QTY, ITM_CATLG_NBR, ITM_DESC, ITM_UNIT_PRC, ITM_RSTRC_IND, ITM_TYP_CD, ITM_AUX_PART_ID, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, PUR_COMM_CD)
values (132, 'C4A98C5B-7BE0-ABEA-E363-C98BC40AB6Z2', 10, 13, 2, 'PR', 2.00, null, 'Desk & Chair', 7000.0000, 'N', 'ITEM', null, null, null, 'N', null);

insert into pur_reqs_itm_t (REQS_ITM_ID, OBJ_ID, VER_NBR, REQS_ID, ITM_LN_NBR, ITM_UOM_CD, ITM_QTY, ITM_CATLG_NBR, ITM_DESC, ITM_UNIT_PRC, ITM_RSTRC_IND, ITM_TYP_CD, ITM_AUX_PART_ID, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, PUR_COMM_CD)
values (133, '5C02FF0E-D84F-EF64-84FB-224E71EDFCZ3', 10, 13, null, null, null, null, 'USPS',  750.0000, 'N', 'FRHT', null, null, null, 'N', null);

insert into pur_reqs_itm_t (REQS_ITM_ID, OBJ_ID, VER_NBR, REQS_ID, ITM_LN_NBR, ITM_UOM_CD, ITM_QTY, ITM_CATLG_NBR, ITM_DESC, ITM_UNIT_PRC, ITM_RSTRC_IND, ITM_TYP_CD, ITM_AUX_PART_ID, EXT_ORG_B2B_PROD_REF_NBR, EXT_ORG_B2B_PROD_TYP_NM, ITM_ASND_TO_TRADE_IN_IND, PUR_COMM_CD)
values (134, '6A76BF01-E76B-BE88-8D93-ABB8D46CA0Z4', 10, 13, null,  null, null, null, 'USPS', 250.0000, 'N', 'SPHD', null, null, null, 'N', null);

--------------------------------------------------
