-- Changeset updates/2010-07-20-5412-1-KRNS_PARM_T.xml::5412-1-1::Winston::(MD5Sum: cdae1a7a3b6aa01437e28f2d328a5b59)
-- When tagging information exists for Pre-Asset Tagging on a Purchase Order, this is the Asset Acquisition Type code to be used on the Asset Global (Add) document generated by processing a transaction using the Capital Asset Builder (CAB) create asset function.
INSERT INTO `KRNS_PARM_T` (`VER_NBR`, `PARM_DESC_TXT`, `OBJ_ID`, `PARM_NM`, `PARM_DTL_TYP_CD`, `CONS_CD`, `APPL_NMSPC_CD`, `TXT`, `PARM_TYP_CD`, `NMSPC_CD`) VALUES (1, 'The Asset Acquisition Type code to be used when the Asset Global Add document is generated by processing a transaction using the Capital Asset Builder CAB create asset function', uuid(), 'NEW_ACQUISITION_CODE', 'AssetGlobal', 'A', 'KUALI', 'A', 'CONFG', 'KFS-CAM');


-- Changeset updates/2010-07-20-5412-1-KRNS_PARM_T.xml::5412-1-2::Winston::(MD5Sum: 7614d6c4653b8e6a8cafae995b10519)
-- When tagging information exists for Pre-Asset Tagging on a Purchase Order, this is the Asset Acquisition Type code to be used on the Asset Global (Add) document generated by processing a transaction using the Capital Asset Builder (CAB) create asset function.
INSERT INTO `KRNS_PARM_T` (`VER_NBR`, `PARM_DESC_TXT`, `OBJ_ID`, `PARM_NM`, `PARM_DTL_TYP_CD`, `CONS_CD`, `APPL_NMSPC_CD`, `TXT`, `PARM_TYP_CD`, `NMSPC_CD`) VALUES (1, 'Capital Asset Acquisition Types codes representing non-expenditure additions not purchased These Type codes are not associated with and do not require the user to enter the following fields on the Asset Global Add document: Document Number, Document Type Code and Posted Date', uuid(), 'NON_NEW_ACQUISITION_CODES', 'AssetGlobal', 'A', 'KUALI', 'G;F', 'CONFG', 'KFS-CAM');


-- Changeset updates/2010-07-20-5412-1-KRNS_PARM_T.xml::5412-1-3::Winston::(MD5Sum: 4e82e097fd9be7a57aaa63d9f52162c0)
-- When tagging information exists for Pre-Asset Tagging on a Purchase Order, this is the Asset Acquisition Type code to be used on the Asset Global (Add) document generated by processing a transaction using the Capital Asset Builder (CAB) create asset function.
INSERT INTO `KRNS_PARM_T` (`VER_NBR`, `PARM_DESC_TXT`, `OBJ_ID`, `PARM_NM`, `PARM_DTL_TYP_CD`, `CONS_CD`, `APPL_NMSPC_CD`, `TXT`, `PARM_TYP_CD`, `NMSPC_CD`) VALUES (1, 'All Capital Asset Acquisition Type codes not otherwise specified in the NEW_AQUISITION_CODE parameter Allows system to identify non-capital asset acquisition type codes and then determines the availability of the following fields on the Asset Global Add document: Document Number, Document Type Code and Posted Date', uuid(), 'CAPITAL_OBJECT_ACQUISITION_CODES', 'AssetGlobal', 'D', 'KUALI', 'F;G;S', 'CONFG', 'KFS-CAM');


-- Changeset updates/2010-07-20-5412-1-KRNS_PARM_T.xml::5412-1-4::Winston::(MD5Sum: 4824bc2d701b7795cc8eedecc4256467)
-- When tagging information exists for Pre-Asset Tagging on a Purchase Order, this is the Asset Acquisition Type code to be used on the Asset Global (Add) document generated by processing a transaction using the Capital Asset Builder (CAB) create asset function.
INSERT INTO `KRNS_PARM_T` (`VER_NBR`, `PARM_DESC_TXT`, `OBJ_ID`, `PARM_NM`, `PARM_DTL_TYP_CD`, `CONS_CD`, `APPL_NMSPC_CD`, `TXT`, `PARM_TYP_CD`, `NMSPC_CD`) VALUES (1, 'The Asset Acquisition Type code that will populate the Acquisition Type Code field when the Asset Fabrication document is initiated', uuid(), 'FABRICATED_ACQUISITION_CODE', 'Asset', 'A', 'KFS', 'C', 'CONFG', 'KFS-CAM');


-- Changeset updates/2010-07-20-5412-1-KRNS_PARM_T.xml::5412-1-5::Winston::(MD5Sum: 72b7fc5060779f9866e3abeaa04bbfa5)
-- When tagging information exists for Pre-Asset Tagging on a Purchase Order, this is the Asset Acquisition Type code to be used on the Asset Global (Add) document generated by processing a transaction using the Capital Asset Builder (CAB) create asset function.
INSERT INTO `KRNS_PARM_T` (`VER_NBR`, `PARM_DESC_TXT`, `OBJ_ID`, `PARM_NM`, `PARM_DTL_TYP_CD`, `CONS_CD`, `APPL_NMSPC_CD`, `TXT`, `PARM_TYP_CD`, `NMSPC_CD`) VALUES (1, 'When tagging information exists for Pre-Asset Tagging on a Purchase Order, this is the Asset Acquisition Type code to be used on the Asset Global Add document generated by processing a transaction using the Capital Asset Builder CAB create asset function', uuid(), 'PRE_TAGGING_ACQUISITION_CODE', 'AssetGlobal', 'A', 'KFS', 'P', 'CONFG', 'KFS-CAM');

