
SELECT 'KFS'||ENTITY_ID AS ENTITY_ID, 'KFS'||ENTITY_ID AS OBJ_ID, ACTV_IND
    FROM KRIM_ENTITY_T
    WHERE entity_id NOT IN ( '1', '3' )
/
SELECT 'KFS'||PRNCPL_ID AS PRNCPL_ID, 'KFS'||PRNCPL_ID AS OBJ_ID, PRNCPL_NM, 'KFS'||ENTITY_ID AS ENTITY_ID, ACTV_IND
    FROM KRIM_PRNCPL_T
    WHERE entity_id NOT IN ( '1', '3' )
/

SELECT ENT_TYP_CD, 'KFS'||ENTITY_ID AS ENTITY_ID, 'KFS'||ENTITY_ID||'-'||ENT_TYP_CD AS OBJ_ID, ACTV_IND
    FROM KRIM_ENTITY_ENT_TYP_T
    WHERE entity_id NOT IN ( '1', '3' )
/

SELECT 'KFS'||ENTITY_ADDR_ID AS ENTITY_ADDR_ID, 'KFS'||ENTITY_ADDR_ID AS OBJ_ID, 'KFS'||ENTITY_ID AS ENTITY_ID, ENT_TYP_CD, ADDR_TYP_CD, ADDR_LINE_1, ADDR_LINE_2, ADDR_LINE_3, CITY_NM, POSTAL_STATE_CD, POSTAL_CD, POSTAL_CNTRY_CD, DFLT_IND, ACTV_IND
    FROM KRIM_ENTITY_ADDR_T
    WHERE entity_id NOT IN ( '1', '3' )
/

SELECT 'KFS'||ENTITY_AFLTN_ID AS ENTITY_AFLTN_ID, 'KFS'||ENTITY_AFLTN_ID AS OBJ_ID, 'KFS'||ENTITY_ID AS ENTITY_ID, AFLTN_TYP_CD, CAMPUS_CD, DFLT_IND, ACTV_IND
    FROM KRIM_ENTITY_AFLTN_T
    WHERE entity_id NOT IN ( '1', '3' )
/

SELECT 'KFS'||ENTITY_ID AS ENTITY_ID, 'KFS'||ENTITY_ID AS OBJ_ID, BIRTH_DT, GNDR_CD, LAST_UPDT_DT, DECEASED_DT, MARITAL_STATUS, PRIM_LANG_CD, SEC_LANG_CD, BIRTH_CNTRY_CD, BIRTH_STATE_CD, BIRTH_CITY, GEO_ORIGIN 
    FROM KRIM_ENTITY_BIO_T
    WHERE entity_id NOT IN ( '1', '3' )
/

SELECT 'KFS'||ENTITY_CTZNSHP_ID AS ENTITY_CTZNSHP_ID, 'KFS'||ENTITY_CTZNSHP_ID AS OBJ_ID, ENTITY_ID, POSTAL_CNTRY_CD, CTZNSHP_STAT_CD, STRT_DT, END_DT, ACTV_IND 
    FROM KRIM_ENTITY_CTZNSHP_T
    WHERE entity_id NOT IN ( '1', '3' )
/

SELECT 'KFS'||ENTITY_EMAIL_ID AS ENTITY_EMAIL_ID, 'KFS'||ENTITY_EMAIL_ID AS OBJ_ID, 'KFS'||ENTITY_ID AS ENTITY_ID, ENT_TYP_CD, EMAIL_TYP_CD, EMAIL_ADDR, DFLT_IND, ACTV_IND
    FROM KRIM_ENTITY_EMAIL_T
    WHERE entity_id NOT IN ( '1', '3' )
/

SELECT 'KFS'||ENTITY_EMP_ID AS ENTITY_EMP_ID, 'KFS'||ENTITY_EMP_ID AS OBJ_ID, 'KFS'||ENTITY_ID AS ENTITY_ID, 'KFS'||ENTITY_AFLTN_ID AS ENTITY_AFLTN_ID, EMP_STAT_CD, EMP_TYP_CD, BASE_SLRY_AMT, PRMRY_IND, ACTV_IND, PRMRY_DEPT_CD, EMP_ID, EMP_REC_ID 
    FROM KRIM_ENTITY_EMP_INFO_T
    WHERE entity_id NOT IN ( '1', '3' )
/

SELECT 'KFS'||ID AS ID, 'KFS'||ENTITY_ID AS ENTITY_ID, ETHNCTY_CD, SUB_ETHNCTY_CD, 'KFS'||ID AS OBJ_ID 
    FROM KRIM_ENTITY_ETHNIC_T
/

SELECT 'KFS'||ENTITY_EXT_ID_ID AS ENTITY_EXT_ID_ID, 'KFS'||ENTITY_EXT_ID_ID AS OBJ_ID, 'KFS'||ENTITY_ID AS ENTITY_ID, EXT_ID_TYP_CD, EXT_ID
    FROM KRIM_ENTITY_EXT_ID_T
    WHERE entity_id NOT IN ( '1', '3' )
/

SELECT 'KFS'||ENTITY_NM_ID AS ENTITY_NM_ID, 'KFS'||ENTITY_NM_ID AS OBJ_ID, 'KFS'||ENTITY_ID AS ENTITY_ID, NM_TYP_CD, FIRST_NM, MIDDLE_NM, LAST_NM, SUFFIX_NM, TITLE_NM, DFLT_IND, ACTV_IND
    FROM KRIM_ENTITY_NM_T
    WHERE entity_id NOT IN ( '1', '3' )
/

SELECT 'KFS'||ENTITY_ID AS ENTITYID, 'KFS'||ENTITY_ID AS OBJ_ID, SUPPRESS_NM_IND, SUPPRESS_EMAIL_IND, SUPPRESS_ADDR_IND, SUPPRESS_PHONE_IND, SUPPRESS_PRSNL_IND
    FROM KRIM_ENTITY_PRIV_PREF_T
    WHERE entity_id NOT IN ( '1', '3' )
/
SELECT 'KFS'||ID AS ID, 'KFS'||ENTITY_ID AS ENTITY_ID, DETERMINATION_METHOD, IN_STATE, 'KFS'||ID AS OBJ_ID 
    FROM KRIM_ENTITY_RESIDENCY_T
    WHERE entity_id NOT IN ( '1', '3' )
/
SELECT 'KFS'||ID AS ID, 'KFS'||ENTITY_ID AS ENTITY_ID, VISA_TYPE_KEY, VISA_ENTRY, VISA_ID, VER_NBR, 'KFS'||ID AS OBJ_ID 
    FROM KRIM_ENTITY_VISA_T
    WHERE entity_id NOT IN ( '1', '3' )
/












