-- KIM Attribute Definitions
SELECT KIM_ATTR_DEFN_ID, KIM_ATTR_DEFN_ID AS OBJ_ID, 1 AS VER_NBR, NM, LBL, ACTV_IND, NMSPC_CD, CMPNT_NM 
    FROM KRIM_ATTR_DEFN_T
    WHERE nmspc_cd LIKE 'KFS%'
      OR CMPNT_NM LIKE '%kfs%'
/

-- KIM Types
SELECT KIM_TYP_ID, KIM_TYP_ID AS OBJ_ID, 1 AS VER_NBR, NM, SRVC_NM, ACTV_IND, NMSPC_CD 
    FROM KRIM_TYP_T
    WHERE nmspc_cd LIKE 'KFS%'
/

-- KIM Type Attributes
SELECT KIM_TYP_ATTR_ID, KIM_TYP_ATTR_ID AS OBJ_ID, 1 AS VER_NBR, SORT_CD, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ACTV_IND 
    FROM KRIM_TYP_ATTR_T
    WHERE kim_typ_id IN (
        SELECT KIM_TYP_ID
            FROM KRIM_TYP_T
            WHERE nmspc_cd LIKE 'KFS%'
    )
/
