CREATE TABLE END_KEMID_BENE_ORG_T (
		KEMID VARCHAR2(10) NOT NULL,
		BENE_ORG_SEQ NUMBER(3 , 0) NOT NULL,
		BENE_ORG_CD VARCHAR2(4) NOT NULL,
		BENE_PCT NUMBER(3 , 2) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		BENE_ORG_STRT_DT DATE NOT NULL,
		BENE_ORG_CHG_DT DATE,
		BENE_CHRT_CD VARCHAR2(2) NOT NULL
	);

CREATE TABLE END_CURR_ENDOW_CORPUS_T (
		KEMID VARCHAR2(10) NOT NULL,
		CORPUS_VAL NUMBER(19 , 2) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL
	);

CREATE TABLE END_AGRMNT_SPCL_INSTRC_CD_T (
		AGRMNT_SPCL_INSTRC_CD VARCHAR2(3) NOT NULL,
		AGRMNT_SPCL_INSTRC_DESC VARCHAR2(75) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_CSH_SWEEP_MDL_T (
		CSH_SWEEP_MDL_ID NUMBER(9 , 0) NOT NULL,
		CSH_SWEEP_MDL_NM VARCHAR2(100) NOT NULL,
		INC_SWEEP_LOWER_LMT NUMBER(7 , 2) DEFAULT 0.00  NOT NULL,
		INC_SWEEP_SEC_ID VARCHAR2(9),
		INC_SWEEP_REGIS_CD VARCHAR2(4),
		PRIN_SWEEP_LOWER_LMT NUMBER(7 , 2) DEFAULT 0.00  NOT NULL,
		CSH_SWEEP_FREQ VARCHAR2(4) NOT NULL,
		CSH_SWEEP_MDL_DT DATE NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y' NOT NULL,
		PRIN_SWEEP_SEC_ID VARCHAR2(9) NOT NULL,
		PRIN_SWEEP_REGIS_CD VARCHAR2(4) NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_CRNT_TAX_LOT_BAL_T (
		KEMID VARCHAR2(10) NOT NULL,
		SEC_ID VARCHAR2(9) NOT NULL,
		REGIS_CD VARCHAR2(4) NOT NULL,
		HLDG_LOT_NBR NUMBER(4 , 0) DEFAULT 1  NOT NULL,
		HLDG_IP_IND VARCHAR2(1) NOT NULL,
		HLDG_UNITS NUMBER(16 , 4) DEFAULT 0.0000  NOT NULL,
		HLDG_COST NUMBER(19 , 2) DEFAULT 0.00  NOT NULL,
		HLDG_ANNL_INC_EST NUMBER(19 , 2) DEFAULT 0.00  NOT NULL,
		HLDG_FY_REM_EST_INC NUMBER(19 , 2) DEFAULT 0.00  NOT NULL,
		HLDG_NEXT_FY_EST_INC NUMBER(19 , 2) DEFAULT 0.00  NOT NULL,
		SEC_UNIT_VAL NUMBER(19 , 5) NOT NULL,
		HLDG_ACQD_DT DATE NOT NULL,
		HLDG_PRIOR_ACRD_INC NUMBER(19 , 2) DEFAULT 0  NOT NULL,
		HLDG_ACRD_INC_DUE NUMBER(19 , 5) DEFAULT 0  NOT NULL,
		HLDG_FRGN_TAX_WITH NUMBER(19 , 5) NOT NULL,
		LAST_TRAN_DT DATE NOT NULL,
		HLDG_MVAL NUMBER(19 , 2) NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_TYP_RESTR_CD_T (
		TYP_RESTR_CD VARCHAR2(3) NOT NULL,
		TYP_RESTR_DESC VARCHAR2(36) NOT NULL,
		PERM VARCHAR2(1) DEFAULT 'N'  NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_FEE_BAL_TYP_CD_T (
		FEE_BAL_TYP_CD VARCHAR2(3) NOT NULL,
		FEE_BAL_TYP_DESC VARCHAR2(22) NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_HIST_CSH_T (
		KEMID VARCHAR2(10) NOT NULL,
		ME_DT_ID NUMBER(3 , 0) NOT NULL,
		HIST_INC_CSH NUMBER(19 , 2) DEFAULT 0.00  NOT NULL,
		HIST_PRIN_CSH NUMBER(19 , 2) DEFAULT 0.00  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_CAE_CD_T (
		CAE_CD VARCHAR2(1) NOT NULL,
		CAE_DESC VARCHAR2(75) NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		CAE_TYP VARCHAR2(1) NOT NULL
	);

CREATE TABLE END_AGRMNT_STAT_CD_T (
		AGRMNT_STAT_CD VARCHAR2(4) NOT NULL,
		AGRMNT_STAT_DESC VARCHAR2(75) NOT NULL,
		AGRMNT_DFLT_TRAN_RESTR VARCHAR2(5) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_ENDOW_CORPUS_T (
		KEMID VARCHAR2(10) NOT NULL,
		CORPUS_VAL_HIST_DT DATE NOT NULL,
		CORPUS_VAL NUMBER(19 , 2) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL
	);

CREATE TABLE END_FEE_TRAN_TYP_T (
		FEE_MTHD VARCHAR2(12) NOT NULL,
		TRAN_TYP_CD VARCHAR2(1) NOT NULL,
		INCL VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_TRAN_TYP_CD_T (
		TRAN_TYP_CD VARCHAR2(1) NOT NULL,
		TRAN_TYP_DESC VARCHAR2(10) NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_POOL_FND_VAL_T (
		POOL_SEC_ID VARCHAR2(9) NOT NULL,
		VAL_EFF_DT DATE NOT NULL,
		VAL_DT DATE NOT NULL,
		DSTRB_AMT NUMBER(19 , 5) DEFAULT 0  NOT NULL,
		DSTRB_PROC_ON_DT DATE,
		DSTRB_PROC_CMPLT VARCHAR2(1) DEFAULT 'N'  NOT NULL,
		LT_GAIN_LOSS NUMBER(19 , 5) DEFAULT 0  NOT NULL,
		LT_PROC_ON_DT DATE,
		LT_PROC_CMPLT VARCHAR2(1) DEFAULT 'N'  NOT NULL,
		ST_PROC_CMPLT VARCHAR2(1) DEFAULT 'N'  NOT NULL,
		ST_GAIN_LOSS NUMBER(19 , 5) DEFAULT 0  NOT NULL,
		ST_PROC_ON_DT DATE,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		POOL_FND_UNIT_VAL NUMBER(19 , 5) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_FEE_MTHD_T (
		FEE_MTHD VARCHAR2(12) NOT NULL,
		FEE_MTHD_DESC VARCHAR2(50) NOT NULL,
		FEE_FREQ_CD VARCHAR2(4) NOT NULL,
		FEE_NXT_PROC_DT DATE,
		FEE_LST_PROC_DT DATE,
		FEE_RT_DEF_CD VARCHAR2(1) NOT NULL,
		FEE_RT_1 NUMBER(9 , 4) DEFAULT 0.0000 NOT NULL,
		FEE_BRK_1 NUMBER(19 , 2) DEFAULT 99999999999999999.99 NOT NULL,
		FEE_RT_2 NUMBER(9 , 4) DEFAULT 0.0000 NOT NULL,
		FEE_BRK_2 NUMBER(19 , 2) DEFAULT 99999999999999999.99 NOT NULL,
		FEE_RT_3 NUMBER(9 , 4) DEFAULT 0.0000 NOT NULL,
		FEE_MIN_AMT NUMBER(4 , 2) DEFAULT 0,
		FEE_TYP_CD VARCHAR2(1) NOT NULL,
		FEE_BASE_CD VARCHAR2(1) NOT NULL,
		FEE_EXP_ETRAN_CD VARCHAR2(9) NOT NULL,
		FEE_POST_PEND_IND VARCHAR2(1) DEFAULT 'N'  NOT NULL,
		CORPUS_PCT_TLRNC NUMBER(5 , 2),
		FEE_BAL_TYP_CD VARCHAR2(3) NOT NULL,
		FEE_BY_CLS_CD VARCHAR2(1) DEFAULT 'N',
		FEE_BY_SEC_ID VARCHAR2(1) DEFAULT 'N',
		FEE_BY_TRAN_TYP VARCHAR2(1) DEFAULT 'N',
		FEE_BY_ETRAN_CD VARCHAR2(1) DEFAULT 'N',
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_KEMID_FND_SRC_T (
		KEMID VARCHAR2(10) NOT NULL,
		KEMID_FND_SRC_SEQ NUMBER(3 , 0) NOT NULL,
		FND_SRC_CD VARCHAR2(5) NOT NULL,
		OPND_FRM_KEMID VARCHAR2(10),
		FND_HIST VARCHAR2(250),
		FND_SRC_ADTNL_DTA VARCHAR2(250),
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL
	);

CREATE TABLE END_KEMID_CMB_GRP_T (
		KEMID VARCHAR2(10) NOT NULL,
		CMB_SEQ NUMBER(3 , 0) NOT NULL,
		CMB_GRP_ID VARCHAR2(5) NOT NULL,
		CMB_DT DATE NOT NULL,
		TERM_CMB_DT DATE,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL
	);

CREATE TABLE END_AGRMNT_TYP_CD_T (
		AGRMNT_TYP_CD VARCHAR2(3) NOT NULL,
		AGRMNT_TYP_CD_DESC VARCHAR2(75) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_TKLR_SEC_T (
		TKLR_NBR VARCHAR2(5) NOT NULL,
		TKLR_SEC_ID VARCHAR2(10) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1   NOT NULL
	);

CREATE TABLE END_TYP_FEE_MTHD_T (
		TYP_CD VARCHAR2(3) NOT NULL,
		FEE_MTHD VARCHAR2(10) NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'N'  NOT NULL
	);

CREATE TABLE END_KEMID_GL_LNK_T (
		KEMID VARCHAR2(10) NOT NULL,
		IP_IND_CD VARCHAR2(1) NOT NULL,
		CHRT_CD VARCHAR2(2) NOT NULL,
		ACCT_NBR VARCHAR2(7) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL
	);

CREATE TABLE END_POOL_FND_CTRL_T (
		POOL_SEC_ID VARCHAR2(9) NOT NULL,
		POOL_FND_DESC VARCHAR2(120),
		PF_BATCH_ID VARCHAR2(5),
		INCRM_VLTN_DAYS NUMBER(3 , 0) DEFAULT 0,
		KEMID VARCHAR2(10) NOT NULL,
		AST_PURCH_OFST_CD VARCHAR2(9),
		AST_SALE_OFST_CD VARCHAR2(9),
		SALE_GAIN_LOSS_CD VARCHAR2(9),
		CSH_DPST_OFST_CD VARCHAR2(9),
		DSTRB_GAIN_LOSS_IND VARCHAR2(1) DEFAULT 'N'  NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y' NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_SEC_T (
		SEC_ID VARCHAR2(9) NOT NULL,
		SEC_DESC VARCHAR2(120),
		SEC_TKR_SYMB VARCHAR2(6),
		SEC_CLS_CD VARCHAR2(3),
		SEC_SUBCLS_CD VARCHAR2(3),
		SEC_MAT_DT DATE,
		SEC_UNIT_VAL NUMBER(19 , 5) DEFAULT 1,
		SEC_UNITS_HELD NUMBER(16 , 5) DEFAULT 0,
		SEC_VAL_DT DATE,
		UNIT_VAL_SRC VARCHAR2(30),
		PREV_UNIT_VAL NUMBER(19 , 5),
		PREV_UNIT_VAL_DT DATE,
		SEC_CVAL NUMBER(19 , 2) DEFAULT 0,
		LAST_TRAN_DT DATE,
		SEC_INC_PAY_FREQ VARCHAR2(4),
		SEC_INC_NEXT_PAY_DT DATE,
		SEC_RT NUMBER(19 , 5),
		SEC_INC_CHG_DT DATE,
		SEC_ISS_DT DATE,
		SEC_DVDND_REC_DT DATE,
		SEC_EX_DVDND_DT DATE,
		SEC_DVDND_PAY_DT DATE,
		SEC_DVDND_AMT NUMBER(19 , 4),
		CMTMNT_AMT NUMBER(19 , 2),
		FRGN_WITH_PCT NUMBER(5 , 4) DEFAULT 0.00,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y' NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		NXT_FSCL_YR_DSTRB_AMT NUMBER(19 , 2)
	);

CREATE TABLE END_KEMID_USE_CRIT_T (
		KEMID VARCHAR2(10) NOT NULL,
		USE_CRIT_SEQ NUMBER(3 , 0) NOT NULL,
		USE_CRIT_CD VARCHAR2(5) NOT NULL,
		USE_CRIT_ADTNL_DTA VARCHAR2(150),
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL
	);

CREATE TABLE END_FEE_TYP_CD_T (
		FEE_TYP_CD VARCHAR2(1) NOT NULL,
		FEE_TYP_DESC VARCHAR2(12) NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_TKLR_RECP_GRP_T (
		TKLR_NBR VARCHAR2(5) NOT NULL,
		TKLR_RECP_GRP_ID VARCHAR2(40) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1   NOT NULL
	);

CREATE TABLE END_FEE_ETRAN_CD_T (
		FEE_MTHD VARCHAR2(12) NOT NULL,
		ETRAN_CD VARCHAR2(9) NOT NULL,
		INCL VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1   NOT NULL
	);

CREATE TABLE END_FEE_SEC_T (
		FEE_MTHD VARCHAR2(12) NOT NULL,
		SEC_ID VARCHAR2(9) NOT NULL,
		INCL VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_USE_CRIT_T (
		USE_CRIT_CD VARCHAR2(5) NOT NULL,
		USE_CRIT_DESC VARCHAR2(100) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_TYP_T (
		TYP_CD VARCHAR2(3) NOT NULL,
		TYP_DESC VARCHAR2(100) NOT NULL,
		TYP_INC_RESTR_CD VARCHAR2(3) NOT NULL,
		TYP_PRIN_RESTR_CD VARCHAR2(3) NOT NULL,
		TYP_CSH_SWEEP_MDL_ID NUMBER(9 , 0),
		TYP_INC_ACI_MDL_ID NUMBER(9 , 0),
		TYP_PRIN_ACI_MDL_ID NUMBER(9 , 0),
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_TRAN_RESTR_CD_T (
		TRAN_RESTR_CD VARCHAR2(5) NOT NULL,
		TRAN_RESTR_DESC VARCHAR2(36) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_FEE_PMT_TYP_T (
		FEE_MTHD VARCHAR2(12) NOT NULL,
		PMT_TYP_CD VARCHAR2(1) NOT NULL,
		INCL VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_ETRAN_TYP_CD_T (
		ETRAN_TYP_CD VARCHAR2(1) NOT NULL,
		ETRAN_TYP_DESC VARCHAR2(40) NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_REGIS_CD_T (
		REGIS_CD VARCHAR2(4) NOT NULL,
		REGIS_CD_DESC VARCHAR2(50),
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y' NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_RESP_ADMIN_CD_T (
		RESP_ADMIN_CD VARCHAR2(4) NOT NULL,
		RESP_ADMIN_DESC VARCHAR2(36) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_ETRAN_CD_T (
		ETRAN_CD VARCHAR2(9) NOT NULL,
		ETRAN_CD_DESC VARCHAR2(120) NOT NULL,
		ETRAN_TYP_CD VARCHAR2(1) NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		CORPUS_IND VARCHAR2(1) DEFAULT 'N'  NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL
	);

CREATE TABLE END_TKLR_RECP_PRNCPL_T (
		TKLR_NBR VARCHAR2(5) NOT NULL,
		TKLR_RECP_PRNCPL_ID VARCHAR2(40) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1   NOT NULL
	);

CREATE TABLE END_AVAIL_CSH_T (
		KEMID VARCHAR2(10) NOT NULL,
		AVAIL_INC_CSH NUMBER(19 , 2) DEFAULT 0.00  NOT NULL,
		AVAIL_PRIN_CSH NUMBER(19 , 2) DEFAULT 0.00  NOT NULL,
		AVAIL_TOT_CSH NUMBER(19 , 2) DEFAULT 0.00  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_FND_SRC_CD_T (
		FND_SRC_CD VARCHAR2(5) NOT NULL,
		FND_SRC_DESC VARCHAR2(36) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_PMT_TYP_CD_T (
		PMT_TYP_CD VARCHAR2(1) NOT NULL,
		PMT_TYP_DESC VARCHAR2(5) NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_KEMID_DONR_T (
		KEMID VARCHAR2(10) NOT NULL,
		DONR_ID VARCHAR2(10) NOT NULL,
		DONR_SEQ NUMBER(3 , 0) NOT NULL,
		DONR_STMT_CD VARCHAR2(5) NOT NULL,
		CMB_DONR_ID VARCHAR2(10),
		EFF_DT DATE NOT NULL,
		TERM_DT DATE,
		TERM_RSN VARCHAR2(150),
		DONR_LBL_SEL VARCHAR2(1) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL
	);

CREATE TABLE END_SUBCLS_CD_T (
		SEC_SUBCLS_CD VARCHAR2(3) NOT NULL,
		SEC_SUBCLS_CD_DESC VARCHAR2(150) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_DONR_T (
		DONR_ID VARCHAR2(10) NOT NULL,
		FIRST_NM VARCHAR2(36),
		MID_NM VARCHAR2(36),
		LAST_NM VARCHAR2(72),
		ADDR1 VARCHAR2(36),
		ADDR2 VARCHAR2(36),
		ADDR3 VARCHAR2(36),
		CITY VARCHAR2(36),
		ST VARCHAR2(2),
		PSTL_CD VARCHAR2(15),
		CNTRY VARCHAR2(2),
		PHN_NBR VARCHAR2(15),
		INDIV_SLTN VARCHAR2(80),
		INDIV_MAIL_LBL VARCHAR2(80),
		JNT_SLTN VARCHAR2(80),
		JNT_MAIL_LBL VARCHAR2(80),
		DEVEL_OFFCR VARCHAR2(80),
		DEC_DT DATE,
		CORP_NM1 VARCHAR2(80),
		CORP_TTL1 VARCHAR2(80),
		CORP_NM2 VARCHAR2(80),
		CORP_TTL2 VARCHAR2(80),
		CMNT VARCHAR2(300),
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_CLS_CD_TYP_T (
		CLS_CD_TYP VARCHAR2(1) NOT NULL,
		CLS_CD_TYP_DESC VARCHAR2(150),
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL
	);

CREATE TABLE END_FEE_RT_DEF_CD_T (
		FEE_RT_DEF_CD VARCHAR2(1) NOT NULL,
		FEE_RT_DEF_DESC VARCHAR2(5) NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_TKLR_T (
		TKLR_NBR VARCHAR2(5) NOT NULL,
		TKLR_TYP_CD VARCHAR2(4) NOT NULL,
		TKLR_FREQ VARCHAR2(4),
		TKLR_NXT_DUE_DT DATE NOT NULL,
		TKLR_DTL VARCHAR2(1024) NOT NULL,
		TKLR_ENTRY_DT DATE NOT NULL,
		TKLR_TERM_DT DATE,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1   NOT NULL
	);

CREATE TABLE END_TKLR_TYP_CD_T (
		TKLR_TYP_CD VARCHAR2(5) NOT NULL,
		TKLR_TYP_DESC VARCHAR2(36) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_CLS_CD_T (
		SEC_CLS_CD VARCHAR2(3) NOT NULL,
		SEC_CLS_CD_DESC VARCHAR2(150),
		SEC_RPT_GRP VARCHAR2(5) NOT NULL,
		SEC_ACRL_MTHD VARCHAR2(1) NOT NULL,
		SEC_ETRAN_CD VARCHAR2(9) NOT NULL,
		SEC_INC_ETRAN_POST_CD VARCHAR2(9) NOT NULL,
		TAX_LOT_IND VARCHAR2(1) DEFAULT 'N',
		CLS_CD_TYP VARCHAR2(1) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y',
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		VLTN_MTHD VARCHAR2(1)
	);

CREATE TABLE END_AUTO_CSH_INVEST_MDL_T (
		ACI_MDL_ID NUMBER(9 , 0) NOT NULL,
		ACI_MDL_NM VARCHAR2(100) NOT NULL,
		ACI_HLDG_IP_IND VARCHAR2(1) NOT NULL,
		ACI_POOL1_SEC_ID VARCHAR2(9) NOT NULL,
		ACI_POOL1_PCT NUMBER(5 , 4) DEFAULT 1.0000  NOT NULL,
		ACI_POOL2_SEC_ID VARCHAR2(9),
		ACI_POOL2_PCT NUMBER(5 , 4) DEFAULT 0.0000,
		ACI_POOL3_SEC_ID VARCHAR2(9),
		ACI_POOL3_REGIS_CD VARCHAR2(4),
		ACI_POOL3_PCT NUMBER(5 , 4) DEFAULT 0.0000,
		ACI_POOL4_SEC_ID VARCHAR2(9),
		ACI_POOL4_PCT NUMBER(5 , 4) DEFAULT 0.0000,
		ACI_FREQ VARCHAR2(4) NOT NULL,
		ACI_MDL_DT DATE NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		ACI_POOL1_REGIS_CD VARCHAR2(4) NOT NULL,
		ACI_POOL2_REGIS_CD VARCHAR2(4),
		ACI_POOL4_REGIS_CD VARCHAR2(4)
	);

CREATE TABLE END_FEE_CLS_CD_T (
		FEE_MTHD VARCHAR2(12) NOT NULL,
		SEC_CLS_CD VARCHAR2(3) NOT NULL,
		INCL VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_PRPS_CD_T (
		PRPS_CD VARCHAR2(4) NOT NULL,
		PRPS_DESC VARCHAR2(100) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_KEMID_CORPUS_VAL_T (
		KEMID VARCHAR2(10) NOT NULL,
		CURR_CORPUS_VAL NUMBER(19 , 2),
		CURR_PRIN_MVAL NUMBER(19 , 2),
		PRIOR_FY_CORPUS_VAL NUMBER(19 , 2),
		PRIOR_FY_PRIN_MVAL NUMBER(19 , 2),
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL
	);

CREATE TABLE END_ACRL_MTHD_T (
		SEC_ACRL_MTHD VARCHAR2(1) NOT NULL,
		SEC_ACRL_MTHD_DESC VARCHAR2(150) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL
	);

CREATE TABLE END_DONR_STMT_CD_T (
		DONR_STMT_CD VARCHAR2(5) NOT NULL,
		DONR_STMT_DESC VARCHAR2(50) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_SEC_RPT_GRP_T (
		SEC_RPT_GRP VARCHAR2(5) NOT NULL,
		SEC_RPT_GRP_DESC VARCHAR2(50),
		SEC_RPT_GRP_ORD NUMBER(2 , 0),
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_SEC_VLTN_MTHD_T (
		VLTN_MTHD VARCHAR2(1) NOT NULL,
		VLTN_MTHD_DESC VARCHAR2(40),
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_DONR_LBL_SEL_T (
		DONR_LBL_SEL VARCHAR2(1) NOT NULL,
		DONR_LBL_SEL_DESC VARCHAR2(50),
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL
	);

CREATE TABLE END_CMB_GRP_T (
		CMB_GRP_ID VARCHAR2(5) NOT NULL,
		CMB_GRP_DESC VARCHAR2(75) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_HLDG_HIST_T (
		KEMID VARCHAR2(10) NOT NULL,
		ME_DT_ID NUMBER(3 , 0) NOT NULL,
		SEC_ID VARCHAR2(9) NOT NULL,
		REGIS_CD VARCHAR2(4) NOT NULL,
		HLDG_LOT_NBR NUMBER(4 , 0) DEFAULT 1  NOT NULL,
		HLDG_IP_IND VARCHAR2(1) NOT NULL,
		HLDG_UNITS NUMBER(16 , 4) DEFAULT 0.0000  NOT NULL,
		HLDG_COST NUMBER(19 , 2) DEFAULT 0.00  NOT NULL,
		HLDG_ANNL_INC_EST NUMBER(19 , 2) DEFAULT 0.00  NOT NULL,
		SEC_UNIT_VAL NUMBER(19 , 5) NOT NULL,
		HLDG_ACQD_DT DATE NOT NULL,
		HLDG_PRIOR_ACRD_INC NUMBER(19 , 2) DEFAULT 0  NOT NULL,
		HLDG_ACRD_INC_DUE NUMBER(19 , 5) DEFAULT 0  NOT NULL,
		LAST_TRAN_DT DATE NOT NULL,
		HLDG_MVAL NUMBER(19 , 2) NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		HLDG_FRGN_TAX_WITH NUMBER(19 , 5) NOT NULL,
		AVG_MVAL NUMBER(19 , 2),
		HLDG_FY_REM_EST_INC NUMBER(19 , 2) NOT NULL,
		HLDG_NEXT_FY_EST_INC NUMBER(19 , 2) NOT NULL
	);

CREATE TABLE END_CLOSE_CD_T (
		CLOSE_CD VARCHAR2(3) NOT NULL,
		CLOSE_DESC VARCHAR2(75) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_FEE_BASE_CD_T (
		FEE_BASE_CD VARCHAR2(1) NOT NULL,
		FEE_BASE_DESC VARCHAR2(9) NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_FREQ_CD_T (
		FREQ_CD VARCHAR2(4) NOT NULL,
		FREQ_DESC VARCHAR2(150),
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL
	);

CREATE TABLE END_KEMID_SPCL_INSTRC_T (
		KEMID VARCHAR2(10) NOT NULL,
		INSTRC_SEQ NUMBER(3 , 0) NOT NULL,
		AGRMNT_SPCL_INSTRC_CD VARCHAR2(3) NOT NULL,
		CMNT VARCHAR2(1024),
		INSTRC_EST_DT DATE NOT NULL,
		INSTRC_TERM_DT DATE,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL
	);

CREATE TABLE END_ME_DT_T (
		ME_DT_ID NUMBER(3 , 0) NOT NULL,
		ME_DT DATE NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_KEMID_AGRMNT_T (
		KEMID VARCHAR2(10) NOT NULL,
		AGRMNT_ID NUMBER(2 , 0) NOT NULL,
		AGRMNT_TYP_CD VARCHAR2(3) NOT NULL,
		AGRMNT_STAT_CD VARCHAR2(4) DEFAULT 'PEND'  NOT NULL,
		AGRMNT_STAT_DT DATE NOT NULL,
		AGRMNT_OTHR_DOC VARCHAR2(1024),
		DONR_INTNT_TXT VARCHAR2(4000),
		CMNT VARCHAR2(1024),
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL
	);

CREATE TABLE END_ROLE_CD_T (
		ROLE_CD VARCHAR2(6) NOT NULL,
		ROLE_DESC VARCHAR2(36) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_KEMID_FEE_T (
		KEMID VARCHAR2(10) NOT NULL,
		FEE_MTHD VARCHAR2(12) NOT NULL,
		FEE_MTHD_SEQ NUMBER(3 , 0) NOT NULL,
		CHRG_FEE_TO_KEMID VARCHAR2(10) NOT NULL,
		PCT_CHRG_FEE_TO_INC NUMBER(3 , 2) NOT NULL,
		PCT_CHRG_FEE_TO_PRIN NUMBER(3 , 2),
		ACR_FEE VARCHAR2(1) DEFAULT 'N',
		ACRD_FEE_TO_DT NUMBER(19 , 2),
		WAIVE_FEE VARCHAR2(1) DEFAULT 'N',
		WAIVED_FEE_YTD NUMBER(19 , 2),
		WAIVED_FEE_TO_DT NUMBER(19 , 2),
		FEE_IMPL_DT DATE NOT NULL,
		FEE_TERM_DT DATE,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL
	);

CREATE TABLE END_CRNT_CSH_T (
		KEMID VARCHAR2(10) NOT NULL,
		CRNT_INC_CSH NUMBER(19 , 2) DEFAULT 0.00  NOT NULL,
		CRNT_PRIN_CSH NUMBER(19 , 2) DEFAULT 0.00  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL
	);

CREATE TABLE END_KEMID_T (
		KEMID VARCHAR2(10) NOT NULL,
		SHRT_TTL VARCHAR2(50) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1 NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		CLOSED_IND VARCHAR2(1) DEFAULT 'N',
		PRPS_CD VARCHAR2(4) NOT NULL,
		INC_CAE_CD VARCHAR2(1),
		PRIN_CAE_CD VARCHAR2(1),
		CLOSED_TO_KEMID VARCHAR2(10),
		CLOSE_CD VARCHAR2(3),
		FND_DISP VARCHAR2(150),
		CLOSE_DT DATE,
		LONG_TTL VARCHAR2(255) NOT NULL,
		OPND_DT DATE NOT NULL,
		ESTBL_DT DATE NOT NULL,
		TYP_CD VARCHAR2(4) NOT NULL,
		RESP_ADMIN_CD VARCHAR2(4),
		TRAN_RESTR_CD VARCHAR2(5) NOT NULL,
		CSH_SWEEP_MDL_ID NUMBER(9 , 0),
		INC_ACI_MDL_ID NUMBER(9 , 0),
		PRIN_ACI_MDL_ID NUMBER(9 , 0),
		DORMANT_IND VARCHAR2(1) DEFAULT 'N' NOT NULL
	);

CREATE TABLE END_IP_IND_T (
		IP_IND_CD VARCHAR2(1) NOT NULL,
		IP_IND_DESC VARCHAR2(150),
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL
	);

CREATE TABLE END_HLDG_TAX_LOT_T (
		KEMID VARCHAR2(10) NOT NULL,
		SEC_ID VARCHAR2(9) NOT NULL,
		REGIS_CD VARCHAR2(4) NOT NULL,
		HLDG_LOT_NBR NUMBER(4 , 0) NOT NULL,
		HLDG_IP_IND VARCHAR2(1) NOT NULL,
		HLDG_UNITS NUMBER(16 , 4),
		HLDG_COST NUMBER(19 , 2),
		HLDG_ACQD_DT DATE,
		HLDG_PRIOR_ACRD_INC NUMBER(19 , 2) DEFAULT 0,
		HLDG_ACRD_INC_DUE NUMBER(19 , 5) DEFAULT 0,
		LAST_TRAN_DT DATE,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		HLDG_FRGN_TAX_WITH NUMBER(19 , 5) NOT NULL
	);

CREATE TABLE END_KEMID_PAY_INC_T (
		KEMID VARCHAR2(10) NOT NULL,
		PAY_INC_SEQ NUMBER(3 , 0) NOT NULL,
		PAY_INC_TO_KEMID VARCHAR2(10) NOT NULL,
		PAY_INC_PCT NUMBER(3 , 2) NOT NULL,
		PAY_INC_AMT NUMBER(19 , 2),
		PAY_INC_STRT_DT DATE NOT NULL,
		PAY_INC_TERM_DT DATE,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL
	);

CREATE TABLE END_KEMID_DONR_CMB_T (
		KEMID VARCHAR2(10) NOT NULL,
		CMB_SEQ NUMBER(3 , 0) NOT NULL,
		CMB_KEMID VARCHAR2(10) NOT NULL,
		CMB_DT DATE NOT NULL,
		TERM_CMB_DT DATE,
		VER_NBR NUMBER(8 , 0) DEFAULT 1  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL
	);

CREATE TABLE END_ETRAN_GL_LNK_T (
		ETRAN_CD VARCHAR2(9) NOT NULL,
		CHART_CD VARCHAR2(2) NOT NULL,
		OBJECT VARCHAR2(4),
		OBJ_ID VARCHAR2(36),
		VER_NBR NUMBER(8 , 0),
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL
	);

CREATE TABLE END_TKLR_KEMID_T (
		TKLR_NBR VARCHAR2(5) NOT NULL,
		TKLR_KEMID VARCHAR2(10) NOT NULL,
		ROW_ACTV_IND VARCHAR2(1) DEFAULT 'Y'  NOT NULL,
		OBJ_ID VARCHAR2(36) NOT NULL,
		VER_NBR NUMBER(8 , 0) DEFAULT 1   NOT NULL
	);

ALTER TABLE END_USE_CRIT_T ADD CONSTRAINT END_USE_CRIT_PK PRIMARY KEY (USE_CRIT_CD);

ALTER TABLE END_POOL_FND_VAL_T ADD CONSTRAINT END_POOL_FND_VAL_PK PRIMARY KEY (POOL_SEC_ID, VAL_EFF_DT);

ALTER TABLE END_KEMID_USE_CRIT_T ADD CONSTRAINT END_KEMID_USE_CRIT_PK PRIMARY KEY (KEMID, USE_CRIT_SEQ, USE_CRIT_CD);

ALTER TABLE END_CLS_CD_T ADD CONSTRAINT END_CLS_CD_PK PRIMARY KEY (SEC_CLS_CD);

ALTER TABLE END_FEE_TYP_CD_T ADD CONSTRAINT END_FEE_TYP_CD_PK PRIMARY KEY (FEE_TYP_CD);

ALTER TABLE END_FEE_RT_DEF_CD_T ADD CONSTRAINT END_FEE_RT_DEF_CD_PK PRIMARY KEY (FEE_RT_DEF_CD);

ALTER TABLE END_AUTO_CSH_INVEST_MDL_T ADD CONSTRAINT END_AUTO_CSH_INVEST_MDL_PK PRIMARY KEY (ACI_MDL_ID);

ALTER TABLE END_SEC_VLTN_MTHD_T ADD CONSTRAINT END_SEC_VLTN_MTHD_PK PRIMARY KEY (VLTN_MTHD);

ALTER TABLE END_DONR_T ADD CONSTRAINT END_DONR_PK PRIMARY KEY (DONR_ID);

ALTER TABLE END_KEMID_SPCL_INSTRC_T ADD CONSTRAINT END_KEMID_SPCL_INSTRC_PK PRIMARY KEY (KEMID, INSTRC_SEQ, AGRMNT_SPCL_INSTRC_CD);

ALTER TABLE END_FEE_ETRAN_CD_T ADD CONSTRAINT END_FEE_ETRAN_CD_PK PRIMARY KEY (FEE_MTHD, ETRAN_CD);

ALTER TABLE END_TKLR_KEMID_T ADD CONSTRAINT END_TKLR_KEMID_PK PRIMARY KEY (TKLR_NBR, TKLR_KEMID);

ALTER TABLE END_KEMID_FEE_T ADD CONSTRAINT END_KEMID_FEE_PK PRIMARY KEY (KEMID, FEE_MTHD, FEE_MTHD_SEQ);

ALTER TABLE END_TYP_RESTR_CD_T ADD CONSTRAINT END_TYP_RESTR_CD_PK PRIMARY KEY (TYP_RESTR_CD);

ALTER TABLE END_KEMID_FND_SRC_T ADD CONSTRAINT END_KEMID_FND_SRC_PK PRIMARY KEY (KEMID, KEMID_FND_SRC_SEQ, FND_SRC_CD);

ALTER TABLE END_DONR_STMT_CD_T ADD CONSTRAINT END_DONR_STMT_CD_PK PRIMARY KEY (DONR_STMT_CD);

ALTER TABLE END_CRNT_TAX_LOT_BAL_T ADD CONSTRAINT END_CRNT_TAX_LOT_BAL_PK PRIMARY KEY (KEMID, SEC_ID, REGIS_CD, HLDG_LOT_NBR, HLDG_IP_IND);

ALTER TABLE END_SEC_T ADD CONSTRAINT END_SEC_PK PRIMARY KEY (SEC_ID);

ALTER TABLE END_KEMID_BENE_ORG_T ADD CONSTRAINT END_KEMID_BENE_ORG_PK PRIMARY KEY (KEMID, BENE_ORG_SEQ, BENE_ORG_CD, BENE_CHRT_CD);

ALTER TABLE END_AVAIL_CSH_T ADD CONSTRAINT END_AVAIL_CSH_PK PRIMARY KEY (KEMID);

ALTER TABLE END_ETRAN_TYP_CD_T ADD CONSTRAINT END_ETRAN_TYP_CD_PK PRIMARY KEY (ETRAN_TYP_CD);

ALTER TABLE END_DONR_LBL_SEL_T ADD CONSTRAINT END_DONR_LBL_SEL_PK PRIMARY KEY (DONR_LBL_SEL);

ALTER TABLE END_CAE_CD_T ADD CONSTRAINT END_CAE_CD_PK PRIMARY KEY (CAE_CD);

ALTER TABLE END_TKLR_SEC_T ADD CONSTRAINT END_TKLR_SEC_PK PRIMARY KEY (TKLR_NBR, TKLR_SEC_ID);

ALTER TABLE END_FND_SRC_CD_T ADD CONSTRAINT END_FND_SRC_CD_PK PRIMARY KEY (FND_SRC_CD);

ALTER TABLE END_HIST_CSH_T ADD CONSTRAINT END_HIST_CSH_PK PRIMARY KEY (KEMID, ME_DT_ID);

ALTER TABLE END_FEE_MTHD_T ADD CONSTRAINT END_FEE_MTHD_PK PRIMARY KEY (FEE_MTHD);

ALTER TABLE END_ME_DT_T ADD CONSTRAINT END_ME_DT_PK PRIMARY KEY (ME_DT_ID);

ALTER TABLE END_FEE_CLS_CD_T ADD CONSTRAINT END_FEE_CLS_CD_PK PRIMARY KEY (FEE_MTHD, SEC_CLS_CD);

ALTER TABLE END_AGRMNT_SPCL_INSTRC_CD_T ADD CONSTRAINT END_AGRMNT_SPCL_INSTRC_CD_PK PRIMARY KEY (AGRMNT_SPCL_INSTRC_CD);

ALTER TABLE END_KEMID_PAY_INC_T ADD CONSTRAINT END_KEMID_PAY_INC_PK PRIMARY KEY (KEMID, PAY_INC_SEQ, PAY_INC_TO_KEMID);

ALTER TABLE END_IP_IND_T ADD CONSTRAINT END_IP_IND_PK PRIMARY KEY (IP_IND_CD);

ALTER TABLE END_AGRMNT_STAT_CD_T ADD CONSTRAINT END_AGRMNT_STAT_CD_PK PRIMARY KEY (AGRMNT_STAT_CD);

ALTER TABLE END_CLOSE_CD_T ADD CONSTRAINT END_CLOSE_CD_PK PRIMARY KEY (CLOSE_CD);

ALTER TABLE END_TKLR_TYP_CD_T ADD CONSTRAINT END_TKLR_TYP_CD_PK PRIMARY KEY (TKLR_TYP_CD);

ALTER TABLE END_TRAN_RESTR_CD_T ADD CONSTRAINT END_TRAN_RESTR_CD_PK PRIMARY KEY (TRAN_RESTR_CD);

ALTER TABLE END_FREQ_CD_T ADD CONSTRAINT END_FREQ_CD_PK PRIMARY KEY (FREQ_CD);

ALTER TABLE END_AGRMNT_TYP_CD_T ADD CONSTRAINT END_AGRMNT_TYP_CD_PK PRIMARY KEY (AGRMNT_TYP_CD);

ALTER TABLE END_TRAN_TYP_CD_T ADD CONSTRAINT END_TRAN_TYP_CD_PK PRIMARY KEY (TRAN_TYP_CD);

ALTER TABLE END_FEE_BAL_TYP_CD_T ADD CONSTRAINT END_FEE_BAL_TYP_CD_PK PRIMARY KEY (FEE_BAL_TYP_CD);

ALTER TABLE END_KEMID_CMB_GRP_T ADD CONSTRAINT END_KEMID_CMB_GRP_PK PRIMARY KEY (KEMID, CMB_SEQ, CMB_GRP_ID);

ALTER TABLE END_FEE_SEC_T ADD CONSTRAINT END_FEE_SEC_PK PRIMARY KEY (FEE_MTHD, SEC_ID);

ALTER TABLE END_POOL_FND_CTRL_T ADD CONSTRAINT END_POOL_FND_CTRL_PK PRIMARY KEY (POOL_SEC_ID);

ALTER TABLE END_ENDOW_CORPUS_T ADD CONSTRAINT END_ENDOW_CORPUS_PK PRIMARY KEY (KEMID, CORPUS_VAL_HIST_DT);

ALTER TABLE END_ACRL_MTHD_T ADD CONSTRAINT END_ACRL_MTHD_PK PRIMARY KEY (SEC_ACRL_MTHD);

ALTER TABLE END_TKLR_T ADD CONSTRAINT END_TKLR_PK PRIMARY KEY (TKLR_NBR);

ALTER TABLE END_REGIS_CD_T ADD CONSTRAINT END_REGIS_CD_PK PRIMARY KEY (REGIS_CD);

ALTER TABLE END_KEMID_T ADD CONSTRAINT END_KEMID_PK PRIMARY KEY (KEMID);

ALTER TABLE END_ETRAN_CD_T ADD CONSTRAINT END_ETRAN_CD_PK PRIMARY KEY (ETRAN_CD);

ALTER TABLE END_CRNT_CSH_T ADD CONSTRAINT END_CRNT_CSH_PK PRIMARY KEY (KEMID);

ALTER TABLE END_FEE_BASE_CD_T ADD CONSTRAINT END_FEE_BASE_CD_PK PRIMARY KEY (FEE_BASE_CD);

ALTER TABLE END_KEMID_AGRMNT_T ADD CONSTRAINT END_KEMID_AGRMNT_PK PRIMARY KEY (KEMID, AGRMNT_ID);

ALTER TABLE END_PRPS_CD_T ADD CONSTRAINT END_PRPS_CD_PK PRIMARY KEY (PRPS_CD);

ALTER TABLE END_CLS_CD_TYP_T ADD CONSTRAINT END_CLS_CD_TYP_PK PRIMARY KEY (CLS_CD_TYP);

ALTER TABLE END_TYP_FEE_MTHD_T ADD CONSTRAINT END_TYP_FEE_MTHD_PK PRIMARY KEY (TYP_CD, FEE_MTHD);

ALTER TABLE END_PMT_TYP_CD_T ADD CONSTRAINT END_PMT_TYP_CD_PK PRIMARY KEY (PMT_TYP_CD);

ALTER TABLE END_KEMID_GL_LNK_T ADD CONSTRAINT END_KEMID_GL_LNK_PK PRIMARY KEY (KEMID, IP_IND_CD);

ALTER TABLE END_RESP_ADMIN_CD_T ADD CONSTRAINT END_RESP_ADMIN_CD_PK PRIMARY KEY (RESP_ADMIN_CD);

ALTER TABLE END_KEMID_DONR_T ADD CONSTRAINT END_KEMID_DONR_PK PRIMARY KEY (KEMID, DONR_SEQ, DONR_ID);

ALTER TABLE END_SUBCLS_CD_T ADD CONSTRAINT END_SUBCLS_CD_PK PRIMARY KEY (SEC_SUBCLS_CD);

ALTER TABLE END_CSH_SWEEP_MDL_T ADD CONSTRAINT END_CSH_SWEEP_MDL_PK PRIMARY KEY (CSH_SWEEP_MDL_ID);

ALTER TABLE END_CMB_GRP_T ADD CONSTRAINT END_CMB_GRP_PK PRIMARY KEY (CMB_GRP_ID);

ALTER TABLE END_FEE_PMT_TYP_T ADD CONSTRAINT END_FEE_PMT_TYP_PK PRIMARY KEY (FEE_MTHD);

ALTER TABLE END_CURR_ENDOW_CORPUS_T ADD CONSTRAINT END_CURR_ENDOW_CORPUS_PK PRIMARY KEY (KEMID);

ALTER TABLE END_SEC_RPT_GRP_T ADD CONSTRAINT END_SEC_RPT_GRP_PK PRIMARY KEY (SEC_RPT_GRP);

ALTER TABLE END_ROLE_CD_T ADD CONSTRAINT END_ROLE_CD_PK PRIMARY KEY (ROLE_CD);

ALTER TABLE END_ETRAN_GL_LNK_T ADD CONSTRAINT END_ETRAN_GL_LNK_PK PRIMARY KEY (ETRAN_CD, CHART_CD);

ALTER TABLE END_KEMID_CORPUS_VAL_T ADD CONSTRAINT END_KEMID_CORPUS_VAL_PK PRIMARY KEY (KEMID);

ALTER TABLE END_TKLR_RECP_GRP_T ADD CONSTRAINT END_TKLR_RECP_GRP_PK PRIMARY KEY (TKLR_NBR, TKLR_RECP_GRP_ID);

ALTER TABLE END_TKLR_RECP_PRNCPL_T ADD CONSTRAINT END_TKLR_RECP_PRNCPL_PK PRIMARY KEY (TKLR_NBR, TKLR_RECP_PRNCPL_ID);

ALTER TABLE END_KEMID_DONR_CMB_T ADD CONSTRAINT END_KEMID_DONR_CMB_PK PRIMARY KEY (KEMID, CMB_SEQ);

ALTER TABLE END_HLDG_TAX_LOT_T ADD CONSTRAINT END_HLDG_TAX_LOT_PK PRIMARY KEY (KEMID, SEC_ID, REGIS_CD, HLDG_LOT_NBR, HLDG_IP_IND);

ALTER TABLE END_HLDG_HIST_T ADD CONSTRAINT END_HLDG_HIST_PK PRIMARY KEY (KEMID, ME_DT_ID, SEC_ID, REGIS_CD, HLDG_LOT_NBR, HLDG_IP_IND);

ALTER TABLE END_TYP_T ADD CONSTRAINT END_TYP_PK PRIMARY KEY (TYP_CD);

ALTER TABLE END_FEE_TRAN_TYP_T ADD CONSTRAINT END_FEE_TRAN_TYP_PK PRIMARY KEY (FEE_MTHD, TRAN_TYP_CD);

ALTER TABLE END_HLDG_TAX_LOT_T ADD CONSTRAINT END_HLDG_TAX_LOT_TR3 FOREIGN KEY (SEC_ID)
	REFERENCES END_SEC_T (SEC_ID);

ALTER TABLE END_TYP_FEE_MTHD_T ADD CONSTRAINT END_TYP_FEE_MTHD_TR2 FOREIGN KEY (TYP_CD)
	REFERENCES END_TYP_T (TYP_CD);

ALTER TABLE END_CSH_SWEEP_MDL_T ADD CONSTRAINT END_CSH_SWEEP_MDL_TR4 FOREIGN KEY (PRIN_SWEEP_REGIS_CD)
	REFERENCES END_REGIS_CD_T (REGIS_CD);

ALTER TABLE END_KEMID_FEE_T ADD CONSTRAINT END_KEMID_FEE_TR2 FOREIGN KEY (CHRG_FEE_TO_KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_KEMID_PAY_INC_T ADD CONSTRAINT END_KEMID_PAY_INC_TR1 FOREIGN KEY (PAY_INC_TO_KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_CURR_ENDOW_CORPUS_T ADD CONSTRAINT END_CURR_ENDOW_CORPUS_TR1 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_KEMID_T ADD CONSTRAINT END_KEMID_TR1 FOREIGN KEY (INC_ACI_MDL_ID)
	REFERENCES END_AUTO_CSH_INVEST_MDL_T (ACI_MDL_ID);

ALTER TABLE END_FEE_TRAN_TYP_T ADD CONSTRAINT END_FEE_TRAN_TYP_TR1 FOREIGN KEY (FEE_MTHD)
	REFERENCES END_FEE_MTHD_T (FEE_MTHD);

ALTER TABLE END_AGRMNT_STAT_CD_T ADD CONSTRAINT END_AGRMNT_STAT_CD_TR1 FOREIGN KEY (AGRMNT_DFLT_TRAN_RESTR)
	REFERENCES END_TRAN_RESTR_CD_T (TRAN_RESTR_CD);

ALTER TABLE END_TKLR_KEMID_T ADD CONSTRAINT END_TKLR_KEMID_TR2 FOREIGN KEY (TKLR_NBR)
	REFERENCES END_TKLR_T (TKLR_NBR);

ALTER TABLE END_CSH_SWEEP_MDL_T ADD CONSTRAINT END_CSH_SWEEP_MDL_TR1 FOREIGN KEY (INC_SWEEP_SEC_ID)
	REFERENCES END_POOL_FND_CTRL_T (POOL_SEC_ID);

ALTER TABLE END_CRNT_CSH_T ADD CONSTRAINT END_CRNT_CSH_TR1 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_FEE_PMT_TYP_T ADD CONSTRAINT END_FEE_PMT_TYP_TR2 FOREIGN KEY (PMT_TYP_CD)
	REFERENCES END_PMT_TYP_CD_T (PMT_TYP_CD);

ALTER TABLE END_HIST_CSH_T ADD CONSTRAINT ME_DATE_ID FOREIGN KEY (ME_DT_ID)
	REFERENCES END_ME_DT_T (ME_DT_ID);

ALTER TABLE END_KEMID_T ADD CONSTRAINT END_KEMID_TR8 FOREIGN KEY (RESP_ADMIN_CD)
	REFERENCES END_RESP_ADMIN_CD_T (RESP_ADMIN_CD);

ALTER TABLE END_KEMID_CORPUS_VAL_T ADD CONSTRAINT END_KEMID_CORPUS_VAL_TR1 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_AVAIL_CSH_T ADD CONSTRAINT END_AVAIL_CSH_TR1 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_CLS_CD_T ADD CONSTRAINT END_CLS_CD_TR6 FOREIGN KEY (VLTN_MTHD)
	REFERENCES END_SEC_VLTN_MTHD_T (VLTN_MTHD);

ALTER TABLE END_FEE_MTHD_T ADD CONSTRAINT END_FEE_MTHD_TR4 FOREIGN KEY (FEE_RT_DEF_CD)
	REFERENCES END_FEE_RT_DEF_CD_T (FEE_RT_DEF_CD);

ALTER TABLE END_AUTO_CSH_INVEST_MDL_T ADD CONSTRAINT END_AUTO_CSH_INVEST_MDL_TR6 FOREIGN KEY (ACI_POOL1_REGIS_CD)
	REFERENCES END_REGIS_CD_T (REGIS_CD);

ALTER TABLE END_TYP_T ADD CONSTRAINT END_TYP_TR2 FOREIGN KEY (TYP_PRIN_ACI_MDL_ID)
	REFERENCES END_AUTO_CSH_INVEST_MDL_T (ACI_MDL_ID);

ALTER TABLE END_POOL_FND_CTRL_T ADD CONSTRAINT END_POOL_FND_CTRL_TR6 FOREIGN KEY (POOL_SEC_ID)
	REFERENCES END_SEC_T (SEC_ID);

ALTER TABLE END_TKLR_T ADD CONSTRAINT END_TKLR_TR2 FOREIGN KEY (TKLR_TYP_CD)
	REFERENCES END_TKLR_TYP_CD_T (TKLR_TYP_CD);

ALTER TABLE END_KEMID_FEE_T ADD CONSTRAINT END_KEMID_FEE_TR1 FOREIGN KEY (FEE_MTHD)
	REFERENCES END_FEE_MTHD_T (FEE_MTHD);

ALTER TABLE END_FEE_TRAN_TYP_T ADD CONSTRAINT END_FEE_TRAN_TYP_TR2 FOREIGN KEY (TRAN_TYP_CD)
	REFERENCES END_TRAN_TYP_CD_T (TRAN_TYP_CD);

ALTER TABLE END_KEMID_AGRMNT_T ADD CONSTRAINT END_KEMID_AGRMNT_TR2 FOREIGN KEY (AGRMNT_TYP_CD)
	REFERENCES END_AGRMNT_TYP_CD_T (AGRMNT_TYP_CD);

ALTER TABLE END_FEE_MTHD_T ADD CONSTRAINT END_FEE_MTHD_TR6 FOREIGN KEY (FEE_FREQ_CD)
	REFERENCES END_FREQ_CD_T (FREQ_CD);

ALTER TABLE END_CLS_CD_T ADD CONSTRAINT END_CLS_CD_TR3 FOREIGN KEY (SEC_ETRAN_CD)
	REFERENCES END_ETRAN_CD_T (ETRAN_CD);

ALTER TABLE END_KEMID_DONR_T ADD CONSTRAINT END_KEMID_DONR_TR1 FOREIGN KEY (DONR_LBL_SEL)
	REFERENCES END_DONR_LBL_SEL_T (DONR_LBL_SEL);

ALTER TABLE END_KEMID_PAY_INC_T ADD CONSTRAINT END_KEMID_PAY_INC_TR2 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_CLS_CD_T ADD CONSTRAINT END_CLS_CD_TR4 FOREIGN KEY (SEC_INC_ETRAN_POST_CD)
	REFERENCES END_ETRAN_CD_T (ETRAN_CD);

ALTER TABLE END_TYP_T ADD CONSTRAINT END_TYP_TR3 FOREIGN KEY (TYP_CSH_SWEEP_MDL_ID)
	REFERENCES END_CSH_SWEEP_MDL_T (CSH_SWEEP_MDL_ID);

ALTER TABLE END_CLS_CD_T ADD CONSTRAINT END_CLS_CD_TR5 FOREIGN KEY (SEC_RPT_GRP)
	REFERENCES END_SEC_RPT_GRP_T (SEC_RPT_GRP);

ALTER TABLE END_HLDG_TAX_LOT_T ADD CONSTRAINT END_HLDG_TAX_LOT_TR2 FOREIGN KEY (REGIS_CD)
	REFERENCES END_REGIS_CD_T (REGIS_CD);

ALTER TABLE END_KEMID_FND_SRC_T ADD CONSTRAINT END_KEMID_FND_SRC_TR2 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_POOL_FND_VAL_T ADD CONSTRAINT END_POOL_FND_VAL_TR1 FOREIGN KEY (POOL_SEC_ID)
	REFERENCES END_POOL_FND_CTRL_T (POOL_SEC_ID);

ALTER TABLE END_CRNT_TAX_LOT_BAL_T ADD CONSTRAINT END_CRNT_TAX_LOT_BAL_TR1 FOREIGN KEY (HLDG_IP_IND)
	REFERENCES END_IP_IND_T (IP_IND_CD);

ALTER TABLE END_HLDG_TAX_LOT_T ADD CONSTRAINT END_HLDG_TAX_LOT_TR1 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_KEMID_GL_LNK_T ADD CONSTRAINT END_KEMID_GL_LNK_TR1 FOREIGN KEY (IP_IND_CD)
	REFERENCES END_IP_IND_T (IP_IND_CD);

ALTER TABLE END_POOL_FND_CTRL_T ADD CONSTRAINT END_POOL_FND_CTRL_TR2 FOREIGN KEY (AST_SALE_OFST_CD)
	REFERENCES END_ETRAN_CD_T (ETRAN_CD);

ALTER TABLE END_CSH_SWEEP_MDL_T ADD CONSTRAINT END_CSH_SWEEP_MDL_TR3 FOREIGN KEY (INC_SWEEP_REGIS_CD)
	REFERENCES END_REGIS_CD_T (REGIS_CD);

ALTER TABLE END_AUTO_CSH_INVEST_MDL_T ADD CONSTRAINT END_AUTO_CSH_INVEST_MDL_TR8 FOREIGN KEY (ACI_POOL3_REGIS_CD)
	REFERENCES END_REGIS_CD_T (REGIS_CD);

ALTER TABLE END_TYP_T ADD CONSTRAINT END_TYP_TR1 FOREIGN KEY (TYP_INC_ACI_MDL_ID)
	REFERENCES END_AUTO_CSH_INVEST_MDL_T (ACI_MDL_ID);

ALTER TABLE END_HLDG_HIST_T ADD CONSTRAINT END_HLDG_HIST_TR3 FOREIGN KEY (REGIS_CD)
	REFERENCES END_REGIS_CD_T (REGIS_CD);

ALTER TABLE END_KEMID_USE_CRIT_T ADD CONSTRAINT END_KEMID_USE_CRIT_TR1 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_AUTO_CSH_INVEST_MDL_T ADD CONSTRAINT END_AUTO_CSH_INVEST_MDL_TR9 FOREIGN KEY (ACI_POOL4_REGIS_CD)
	REFERENCES END_REGIS_CD_T (REGIS_CD);

ALTER TABLE END_KEMID_DONR_CMB_T ADD CONSTRAINT END_KEMID_DONR_CMB_TR1 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_POOL_FND_CTRL_T ADD CONSTRAINT END_POOL_FND_CTRL_TR3 FOREIGN KEY (SALE_GAIN_LOSS_CD)
	REFERENCES END_ETRAN_CD_T (ETRAN_CD);

ALTER TABLE END_AUTO_CSH_INVEST_MDL_T ADD CONSTRAINT END_AUTO_CSH_INVEST_MDL_TR2 FOREIGN KEY (ACI_POOL1_SEC_ID)
	REFERENCES END_POOL_FND_CTRL_T (POOL_SEC_ID);

ALTER TABLE END_TYP_T ADD CONSTRAINT END_TYP_TR4 FOREIGN KEY (TYP_INC_RESTR_CD)
	REFERENCES END_TYP_RESTR_CD_T (TYP_RESTR_CD);

ALTER TABLE END_FEE_ETRAN_CD_T ADD CONSTRAINT END_FEE_ETRAN_CD_TR1 FOREIGN KEY (FEE_MTHD)
	REFERENCES END_FEE_MTHD_T (FEE_MTHD);

ALTER TABLE END_TKLR_SEC_T ADD CONSTRAINT END_TKLR_SEC_TR1 FOREIGN KEY (TKLR_SEC_ID)
	REFERENCES END_SEC_T (SEC_ID);

ALTER TABLE END_TKLR_RECP_GRP_T ADD CONSTRAINT END_TKLR_RECP_GRP_TR1 FOREIGN KEY (TKLR_NBR)
	REFERENCES END_TKLR_T (TKLR_NBR);

ALTER TABLE END_AUTO_CSH_INVEST_MDL_T ADD CONSTRAINT END_AUTO_CSH_INVEST_MDL_TR4 FOREIGN KEY (ACI_POOL4_SEC_ID)
	REFERENCES END_POOL_FND_CTRL_T (POOL_SEC_ID);

ALTER TABLE END_FEE_MTHD_T ADD CONSTRAINT END_FEE_MTHD_TR5 FOREIGN KEY (FEE_TYP_CD)
	REFERENCES END_FEE_TYP_CD_T (FEE_TYP_CD);

ALTER TABLE END_KEMID_BENE_ORG_T ADD CONSTRAINT END_KEMID_BENE_ORG_TR1 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_SEC_T ADD CONSTRAINT END_SEC_TR1 FOREIGN KEY (SEC_CLS_CD)
	REFERENCES END_CLS_CD_T (SEC_CLS_CD);

ALTER TABLE END_TKLR_RECP_PRNCPL_T ADD CONSTRAINT END_TKLR_RECP_PRNCPL_TR1 FOREIGN KEY (TKLR_NBR)
	REFERENCES END_TKLR_T (TKLR_NBR);

ALTER TABLE END_ENDOW_CORPUS_T ADD CONSTRAINT END_ENDOW_CORPUS_TR1 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_KEMID_USE_CRIT_T ADD CONSTRAINT END_KEMID_USE_CRIT_TR2 FOREIGN KEY (USE_CRIT_CD)
	REFERENCES END_USE_CRIT_T (USE_CRIT_CD);

ALTER TABLE END_POOL_FND_CTRL_T ADD CONSTRAINT END_POOL_FND_CTRL_TR1 FOREIGN KEY (AST_PURCH_OFST_CD)
	REFERENCES END_ETRAN_CD_T (ETRAN_CD);

ALTER TABLE END_CSH_SWEEP_MDL_T ADD CONSTRAINT END_CSH_SWEEP_MDL_TR2 FOREIGN KEY (PRIN_SWEEP_SEC_ID)
	REFERENCES END_POOL_FND_CTRL_T (POOL_SEC_ID);

ALTER TABLE END_TKLR_KEMID_T ADD CONSTRAINT END_TKLR_KEMID_TR1 FOREIGN KEY (TKLR_KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_CRNT_TAX_LOT_BAL_T ADD CONSTRAINT END_CRNT_TAX_LOT_BAL_TR3 FOREIGN KEY (REGIS_CD)
	REFERENCES END_REGIS_CD_T (REGIS_CD);

ALTER TABLE END_FEE_SEC_T ADD CONSTRAINT END_FEE_SEC_TR2 FOREIGN KEY (SEC_ID)
	REFERENCES END_SEC_T (SEC_ID);

ALTER TABLE END_KEMID_FND_SRC_T ADD CONSTRAINT END_KEMID_FND_SRC_TR1 FOREIGN KEY (FND_SRC_CD)
	REFERENCES END_FND_SRC_CD_T (FND_SRC_CD);

ALTER TABLE END_TYP_T ADD CONSTRAINT END_TYP_TR5 FOREIGN KEY (TYP_PRIN_RESTR_CD)
	REFERENCES END_TYP_RESTR_CD_T (TYP_RESTR_CD);

ALTER TABLE END_KEMID_T ADD CONSTRAINT END_KEMID_TR6 FOREIGN KEY (CSH_SWEEP_MDL_ID)
	REFERENCES END_CSH_SWEEP_MDL_T (CSH_SWEEP_MDL_ID);

ALTER TABLE END_KEMID_T ADD CONSTRAINT END_KEMID_TR5 FOREIGN KEY (CLOSE_CD)
	REFERENCES END_CLOSE_CD_T (CLOSE_CD);

ALTER TABLE END_KEMID_DONR_T ADD CONSTRAINT END_KEMID_DONR_TR3 FOREIGN KEY (DONR_ID)
	REFERENCES END_DONR_T (DONR_ID);

ALTER TABLE END_HLDG_HIST_T ADD CONSTRAINT END_HLDG_HIST_TR1 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_KEMID_T ADD CONSTRAINT END_KEMID_TR2 FOREIGN KEY (PRIN_ACI_MDL_ID)
	REFERENCES END_AUTO_CSH_INVEST_MDL_T (ACI_MDL_ID);

ALTER TABLE END_ETRAN_GL_LNK_T ADD CONSTRAINT END_ETRAN_GL_LNK_TR1 FOREIGN KEY (CHART_CD)
	REFERENCES CA_CHART_T (FIN_COA_CD);

ALTER TABLE END_KEMID_T ADD CONSTRAINT END_KEMID_TR7 FOREIGN KEY (PRPS_CD)
	REFERENCES END_PRPS_CD_T (PRPS_CD);

ALTER TABLE END_CRNT_TAX_LOT_BAL_T ADD CONSTRAINT END_CRNT_TAX_LOT_BAL_TR4 FOREIGN KEY (SEC_ID)
	REFERENCES END_SEC_T (SEC_ID);

ALTER TABLE END_AUTO_CSH_INVEST_MDL_T ADD CONSTRAINT END_AUTO_CSH_INVEST_MDL_TR7 FOREIGN KEY (ACI_POOL2_REGIS_CD)
	REFERENCES END_REGIS_CD_T (REGIS_CD);

ALTER TABLE END_KEMID_T ADD CONSTRAINT END_KEMID_TR9 FOREIGN KEY (TRAN_RESTR_CD)
	REFERENCES END_TRAN_RESTR_CD_T (TRAN_RESTR_CD);

ALTER TABLE END_KEMID_CMB_GRP_T ADD CONSTRAINT END_KEMID_CMB_GRP_TR1 FOREIGN KEY (CMB_GRP_ID)
	REFERENCES END_CMB_GRP_T (CMB_GRP_ID);

ALTER TABLE END_HLDG_HIST_T ADD CONSTRAINT END_HLDG_HIST_TR2 FOREIGN KEY (ME_DT_ID)
	REFERENCES END_ME_DT_T (ME_DT_ID);

ALTER TABLE END_FEE_CLS_CD_T ADD CONSTRAINT END_FEE_CLS_CD_TR2 FOREIGN KEY (FEE_MTHD)
	REFERENCES END_FEE_MTHD_T (FEE_MTHD);

ALTER TABLE END_KEMID_SPCL_INSTRC_T ADD CONSTRAINT END_KEMID_SPCL_INSTRC_TR2 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_POOL_FND_CTRL_T ADD CONSTRAINT END_POOL_FND_CTRL_TR4 FOREIGN KEY (CSH_DPST_OFST_CD)
	REFERENCES END_ETRAN_CD_T (ETRAN_CD);

ALTER TABLE END_ETRAN_CD_T ADD CONSTRAINT END_ETRAN_CD_TR1 FOREIGN KEY (ETRAN_TYP_CD)
	REFERENCES END_ETRAN_TYP_CD_T (ETRAN_TYP_CD);

ALTER TABLE END_SEC_T ADD CONSTRAINT END_SEC_TR2 FOREIGN KEY (SEC_SUBCLS_CD)
	REFERENCES END_SUBCLS_CD_T (SEC_SUBCLS_CD);

ALTER TABLE END_FEE_MTHD_T ADD CONSTRAINT END_FEE_MTHD_TR1 FOREIGN KEY (FEE_EXP_ETRAN_CD)
	REFERENCES END_ETRAN_CD_T (ETRAN_CD);

ALTER TABLE END_HIST_CSH_T ADD CONSTRAINT HIST_CSH_KEMID_REF1 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_KEMID_DONR_T ADD CONSTRAINT END_KEMID_DONR_TR4 FOREIGN KEY (CMB_DONR_ID)
	REFERENCES END_DONR_T (DONR_ID);

ALTER TABLE END_POOL_FND_CTRL_T ADD CONSTRAINT END_POOL_FND_CTRL_TR5 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_KEMID_CMB_GRP_T ADD CONSTRAINT END_KEMID_CMB_GRP_TR2 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_TKLR_SEC_T ADD CONSTRAINT END_TKLR_SEC_TR2 FOREIGN KEY (TKLR_NBR)
	REFERENCES END_TKLR_T (TKLR_NBR);

ALTER TABLE END_AUTO_CSH_INVEST_MDL_T ADD CONSTRAINT END_AUTO_CSH_INVEST_MDL_TR5 FOREIGN KEY (ACI_POOL2_SEC_ID)
	REFERENCES END_POOL_FND_CTRL_T (POOL_SEC_ID);

ALTER TABLE END_KEMID_T ADD CONSTRAINT END_KEMID_TR3 FOREIGN KEY (INC_CAE_CD)
	REFERENCES END_CAE_CD_T (CAE_CD);

ALTER TABLE END_AUTO_CSH_INVEST_MDL_T ADD CONSTRAINT END_AUTO_CSH_INVEST_MDL_TR1 FOREIGN KEY (ACI_HLDG_IP_IND)
	REFERENCES END_IP_IND_T (IP_IND_CD);

ALTER TABLE END_CLS_CD_T ADD CONSTRAINT END_CLS_CD_TR2 FOREIGN KEY (CLS_CD_TYP)
	REFERENCES END_CLS_CD_TYP_T (CLS_CD_TYP);

ALTER TABLE END_KEMID_T ADD CONSTRAINT END_KEMID_TR10 FOREIGN KEY (TYP_CD)
	REFERENCES END_TYP_T (TYP_CD);

ALTER TABLE END_FEE_MTHD_T ADD CONSTRAINT END_FEE_MTHD_TR2 FOREIGN KEY (FEE_BAL_TYP_CD)
	REFERENCES END_FEE_BAL_TYP_CD_T (FEE_BAL_TYP_CD);

ALTER TABLE END_ETRAN_GL_LNK_T ADD CONSTRAINT END_ETRAN_GL_LNK_TR2 FOREIGN KEY (ETRAN_CD)
	REFERENCES END_ETRAN_CD_T (ETRAN_CD);

ALTER TABLE END_KEMID_DONR_T ADD CONSTRAINT END_KEMID_DONR_TR2 FOREIGN KEY (DONR_STMT_CD)
	REFERENCES END_DONR_STMT_CD_T (DONR_STMT_CD);

ALTER TABLE END_KEMID_SPCL_INSTRC_T ADD CONSTRAINT END_KEMID_SPCL_INSTRC_TR1 FOREIGN KEY (AGRMNT_SPCL_INSTRC_CD)
	REFERENCES END_AGRMNT_SPCL_INSTRC_CD_T (AGRMNT_SPCL_INSTRC_CD);

ALTER TABLE END_TKLR_T ADD CONSTRAINT END_TKLR_TR1 FOREIGN KEY (TKLR_FREQ)
	REFERENCES END_FREQ_CD_T (FREQ_CD);

ALTER TABLE END_KEMID_AGRMNT_T ADD CONSTRAINT END_KEMID_AGRMNT_TR3 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_KEMID_T ADD CONSTRAINT END_KEMID_TR4 FOREIGN KEY (PRIN_CAE_CD)
	REFERENCES END_CAE_CD_T (CAE_CD);

ALTER TABLE END_AUTO_CSH_INVEST_MDL_T ADD CONSTRAINT END_AUTO_CSH_INVEST_MDL_TR3 FOREIGN KEY (ACI_POOL3_SEC_ID)
	REFERENCES END_POOL_FND_CTRL_T (POOL_SEC_ID);

ALTER TABLE END_KEMID_GL_LNK_T ADD CONSTRAINT END_KEMID_GL_LNK_TR2 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_CLS_CD_T ADD CONSTRAINT END_CLS_CD_TR1 FOREIGN KEY (SEC_ACRL_MTHD)
	REFERENCES END_ACRL_MTHD_T (SEC_ACRL_MTHD);

ALTER TABLE END_FEE_CLS_CD_T ADD CONSTRAINT END_FEE_CLS_CD_TR1 FOREIGN KEY (SEC_CLS_CD)
	REFERENCES END_CLS_CD_T (SEC_CLS_CD);

ALTER TABLE END_CRNT_TAX_LOT_BAL_T ADD CONSTRAINT END_CRNT_TAX_LOT_BAL_TR2 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_TYP_FEE_MTHD_T ADD CONSTRAINT END_TYP_FEE_MTHD_TR1 FOREIGN KEY (FEE_MTHD)
	REFERENCES END_FEE_MTHD_T (FEE_MTHD);

ALTER TABLE END_KEMID_AGRMNT_T ADD CONSTRAINT END_KEMID_AGRMNT_TR1 FOREIGN KEY (AGRMNT_STAT_CD)
	REFERENCES END_AGRMNT_STAT_CD_T (AGRMNT_STAT_CD);

ALTER TABLE END_KEMID_DONR_T ADD CONSTRAINT END_KEMID_DONR_TR5 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_KEMID_FEE_T ADD CONSTRAINT END_KEMID_FEE_TR3 FOREIGN KEY (KEMID)
	REFERENCES END_KEMID_T (KEMID);

ALTER TABLE END_HLDG_HIST_T ADD CONSTRAINT END_HLDG_HIST_TR4 FOREIGN KEY (SEC_ID)
	REFERENCES END_SEC_T (SEC_ID);

ALTER TABLE END_FEE_SEC_T ADD CONSTRAINT END_FEE_SEC_TR1 FOREIGN KEY (FEE_MTHD)
	REFERENCES END_FEE_MTHD_T (FEE_MTHD);

ALTER TABLE END_FEE_MTHD_T ADD CONSTRAINT END_FEE_MTHD_TR3 FOREIGN KEY (FEE_BASE_CD)
	REFERENCES END_FEE_BASE_CD_T (FEE_BASE_CD);

ALTER TABLE END_FEE_PMT_TYP_T ADD CONSTRAINT END_FEE_PMT_TYP_TR1 FOREIGN KEY (FEE_MTHD)
	REFERENCES END_FEE_MTHD_T (FEE_MTHD);

