--1. First add two fields to KEMID table and add foreign key restrictions. 

ALTER TABLE END_KEMID_T ADD TYP_INC_RESTR_CD VARCHAR2(3); 
ALTER TABLE END_KEMID_T ADD TYP_PRIN_RESTR_CD VARCHAR2(3); 
ALTER TABLE END_KEMID_T ADD CONSTRAINT END_KEMID_TR11 FOREIGN KEY (TYP_INC_RESTR_CD) 
      REFERENCES END_TYP_RESTR_CD_T (TYP_RESTR_CD); 
ALTER TABLE END_KEMID_T ADD CONSTRAINT END_KEMID_TR12 FOREIGN KEY (TYP_PRIN_RESTR_CD) 
      REFERENCES END_TYP_RESTR_CD_T (TYP_RESTR_CD); 

--2. Add values to KEMID records based on the I/P restriction codes that are currently associated with the corresponding type code. 

UPDATE END_KEMID_T SET TYP_INC_RESTR_CD='OBS',TYP_PRIN_RESTR_CD='OBS' WHERE KEMID LIKE '099%'; 
UPDATE END_KEMID_T SET TYP_INC_RESTR_CD='OBS',TYP_PRIN_RESTR_CD='OBS' WHERE KEMID LIKE '909%'; 
UPDATE END_KEMID_T SET TYP_INC_RESTR_CD='TRU',TYP_PRIN_RESTR_CD='TRU' WHERE KEMID LIKE '032%'; 
UPDATE END_KEMID_T SET TYP_INC_RESTR_CD='TRU',TYP_PRIN_RESTR_CD='TRU' WHERE KEMID LIKE '038%'; 
UPDATE END_KEMID_T SET TYP_INC_RESTR_CD='TRU',TYP_PRIN_RESTR_CD='TRU' WHERE KEMID LIKE '046%'; 
UPDATE END_KEMID_T SET TYP_INC_RESTR_CD='TRU',TYP_PRIN_RESTR_CD='PRU' WHERE KEMID LIKE '037%'; 

--3. Make those two additional fields in the KEMID table not null. 

ALTER TABLE END_KEMID_T MODIFY TYP_INC_RESTR_CD NOT NULL; 
ALTER TABLE END_KEMID_T MODIFY TYP_PRIN_RESTR_CD NOT NULL; 
