DROP TABLE END_HIST_VAL_ADJ_DOC_T;

-- Create END_HIST_VAL_ADJ_DOC_T table;

CREATE TABLE END_HIST_VAL_ADJ_DOC_T (
FDOC_NBR VARCHAR2(14) NOT NULL,
SEC_ID VARCHAR2(9) NOT NULL,
SEC_CLS_CD VARCHAR2(3),
SEC_VLTN_MTHD VARCHAR2(1),
HLDG_ME_DT_ID NUMBER(3, 0) NOT NULL,
SEC_UNIT_VAL NUMBER(19 , 5) NOT NULL,
SEC_MVAL NUMBER(19 , 2),
TRAN_PSTD VARCHAR2(1) DEFAULT 'N' NOT NULL,
OBJ_ID VARCHAR2(36) NOT NULL,
VER_NBR NUMBER(8, 0) DEFAULT 1 NOT NULL
);

ALTER TABLE END_HIST_VAL_ADJ_DOC_T ADD CONSTRAINT END_HIST_VAL_ADJ_DOC__PK PRIMARY KEY (FDOC_NBR);

ALTER TABLE END_HIST_VAL_ADJ_DOC_T ADD CONSTRAINT END_HIST_VAL_ADJ_DOC_TR1 FOREIGN KEY (FDOC_NBR)
REFERENCES KRNS_DOC_HDR_T (DOC_HDR_ID);

ALTER TABLE END_HIST_VAL_ADJ_DOC_T ADD CONSTRAINT END_HIST_VAL_ADJ_DOC_TR2 FOREIGN KEY (SEC_ID)
REFERENCES END_SEC_T (SEC_ID);

ALTER TABLE END_HIST_VAL_ADJ_DOC_T ADD CONSTRAINT END_HIST_VAL_ADJ_DOC_TR3 FOREIGN KEY (HLDG_ME_DT_ID)
REFERENCES END_ME_DT_T (ME_DT_ID); 