delete from END_TRAN_HLDG_LOT_T;
alter table END_TRAN_HLDG_LOT_T add KEMID varchar2(10) not null;
alter table END_TRAN_HLDG_LOT_T add SEC_ID varchar2(9) not null;
alter table END_TRAN_HLDG_LOT_T add REGIS_CD varchar2(4) not null;
alter table END_TRAN_HLDG_LOT_T add HLDG_IP_IND varchar2(1) not null;

ALTER TABLE END_TRAN_HLDG_LOT_T ADD CONSTRAINT END_TRAN_HLDG_LOT_TR2 FOREIGN KEY (KEMID, SEC_ID, REGIS_CD, HLDG_IP_IND, TRAN_HLDG_LT_NBR)
      REFERENCES END_HLDG_TAX_LOT_T (KEMID, SEC_ID, REGIS_CD, HLDG_IP_IND, HLDG_LOT_NBR); 