update END_POOL_FND_CTRL_T set POOL_REGIS_CD = '0AI' WHERE POOL_SEC_ID='99MMKT013';
update END_POOL_FND_CTRL_T set POOL_REGIS_CD = '0CI' WHERE POOL_SEC_ID='99PLTF013';
update END_POOL_FND_CTRL_T set POOL_REGIS_CD = '0CP' WHERE POOL_SEC_ID='99PLTF021';
update END_POOL_FND_CTRL_T set POOL_REGIS_CD = '0CP' WHERE POOL_SEC_ID='99PLTF997';
update END_POOL_FND_CTRL_T set POOL_REGIS_CD = '0AI' WHERE POOL_SEC_ID='99PSTF018';
update END_POOL_FND_CTRL_T set POOL_REGIS_CD = '0AP' WHERE POOL_SEC_ID='99PSTF034'; 
