ALTER TABLE END_KEMID_CORPUS_VAL_T RENAME COLUMN CURR_CORPUS_VAL TO CRNT_CORPUS_VAL;
ALTER TABLE END_KEMID_CORPUS_VAL_T RENAME COLUMN CURR_PRIN_MVAL TO CRNT_PRIN_MVAL;
ALTER TABLE END_CURR_ENDOW_CORPUS_T RENAME COLUMN CORPUS_VAL TO CRNT_CORPUS_VAL;
ALTER TABLE END_CURR_ENDOW_CORPUS_T ADD( CRNT_PRIN_MVAL NUMBER(19, 2));
ALTER TABLE END_CURR_ENDOW_CORPUS_T RENAME TO END_CRNT_ENDOW_CORPUS_T;