alter table END_AUTO_CSH_INVEST_MDL_T drop constraint END_AUTO_CSH_INVEST_MDL_TR6; 
alter table END_AUTO_CSH_INVEST_MDL_T drop constraint END_AUTO_CSH_INVEST_MDL_TR7; 
alter table END_AUTO_CSH_INVEST_MDL_T drop constraint END_AUTO_CSH_INVEST_MDL_TR8; 
alter table END_AUTO_CSH_INVEST_MDL_T drop constraint END_AUTO_CSH_INVEST_MDL_TR9; 
alter table END_AUTO_CSH_INVEST_MDL_T drop column ACI_POOL1_REGIS_CD; 
alter table END_AUTO_CSH_INVEST_MDL_T drop column ACI_POOL2_REGIS_CD; 
alter table END_AUTO_CSH_INVEST_MDL_T drop column ACI_POOL3_REGIS_CD; 
alter table END_AUTO_CSH_INVEST_MDL_T drop column ACI_POOL4_REGIS_CD; 

alter table END_POOL_FND_CTRL_T add POOL_REGIS_CD VARCHAR2(4); 
alter table END_POOL_FND_CTRL_T ADD CONSTRAINT END_POOL_FND_CTRL_TR7 FOREIGN KEY(POOL_REGIS_CD) REFERENCES END_REGIS_CD_T(REGIS_CD); 
