--
-- Copyright 2010 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

SELECT DISTINCT VNDR_CNTRY_CD AS NON_CONVERTABLE_CODES FROM AP_CRDT_MEMO_T WHERE VNDR_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT INV_RMT_TO_CNTRY_CD AS NON_CONVERTABLE_CODES FROM AP_ELCTRNC_INV_RJT_DOC_T WHERE INV_RMT_TO_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT INV_REF_ITM_CNTRY_CD AS NON_CONVERTABLE_CODES FROM AP_ELCTRNC_INV_RJT_ITM_T WHERE INV_REF_ITM_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT TAX_CNTRY_CD AS NON_CONVERTABLE_CODES FROM AP_PMT_RQST_T WHERE TAX_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT CUST_CNTRY_CD AS NON_CONVERTABLE_CODES FROM AR_CUST_ADDR_T WHERE CUST_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT SHIP_CNTRY_CD AS NON_CONVERTABLE_CODES FROM AR_INV_DOC_T WHERE SHIP_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT ORG_POSTAL_CNTRY_CD AS NON_CONVERTABLE_CODES FROM AR_ORG_OPTION_T WHERE ORG_POSTAL_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT ORG_CNTRY_CD AS NON_CONVERTABLE_CODES FROM CA_ORG_T WHERE ORG_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT ORG_CNTRY_CD AS NON_CONVERTABLE_CODES FROM CA_PRIOR_YR_ORG_T WHERE ORG_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT CGSUBCNR_CNTRY_CD AS NON_CONVERTABLE_CODES FROM CG_SUBCNR_T WHERE CGSUBCNR_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT AST_LOC_CNTRY_CD AS NON_CONVERTABLE_CODES FROM CM_AST_LOC_T WHERE AST_LOC_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT AST_RETIR_CNTRY_CD AS NON_CONVERTABLE_CODES FROM CM_AST_RETIRE_DOC_T WHERE AST_RETIR_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT AST_OFFCMP_CNTRY_CD AS NON_CONVERTABLE_CODES FROM CM_AST_TRNFR_DOC_T WHERE AST_OFFCMP_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT AST_OFFCMP_CNTRY_CD AS NON_CONVERTABLE_CODES FROM CM_CPTLAST_DTL_T WHERE AST_OFFCMP_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT AST_BORWR_CNTRY_CD AS NON_CONVERTABLE_CODES FROM CM_EQPLNRTRN_DOC_T WHERE AST_BORWR_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT DV_TRVL_TO_CNTRY_CD AS NON_CONVERTABLE_CODES FROM FP_DV_NONEM_TRVL_T WHERE DV_TRVL_TO_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT POSTAL_CNTRY_CD AS NON_CONVERTABLE_CODES FROM FP_DV_NRA_TAX_T WHERE POSTAL_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT DV_RMT_CNTRY_CD AS NON_CONVERTABLE_CODES FROM FP_DV_PAYEE_DTL_T WHERE DV_RMT_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT DV_BNK_CNTRY_CD AS NON_CONVERTABLE_CODES FROM FP_DV_WIRE_TRNFR_T WHERE DV_BNK_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT POSTAL_CNTRY_CD AS NON_CONVERTABLE_CODES FROM FS_TAX_COUNTY_T WHERE POSTAL_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT POSTAL_CNTRY_CD AS NON_CONVERTABLE_CODES FROM FS_TAX_POSTAL_CD_T WHERE POSTAL_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT POSTAL_CNTRY_CD AS NON_CONVERTABLE_CODES FROM FS_TAX_STATE_T WHERE POSTAL_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT CUST_CNTRY_CD AS NON_CONVERTABLE_CODES FROM PDP_CUST_PRFL_T WHERE CUST_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT PUR_DEPT_CNTRY_CD AS NON_CONVERTABLE_CODES FROM PUR_AP_CMP_PARM_T WHERE PUR_DEPT_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT BILL_CNTRY_CD AS NON_CONVERTABLE_CODES FROM PUR_BILL_ADDR_T WHERE BILL_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT DLVY_CNTRY_CD AS NON_CONVERTABLE_CODES FROM PUR_BLK_RCVNG_T WHERE DLVY_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT CPTL_AST_CNTRY_CD AS NON_CONVERTABLE_CODES FROM PUR_PO_CPTL_AST_LOC_T WHERE CPTL_AST_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT PUR_RCVNG_CNTRY_CD AS NON_CONVERTABLE_CODES FROM PUR_PO_T WHERE PUR_RCVNG_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT VNDR_CNTRY_CD AS NON_CONVERTABLE_CODES FROM PUR_PO_VNDR_QT_T WHERE VNDR_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT PUR_RCVNG_CNTRY_CD AS NON_CONVERTABLE_CODES FROM PUR_RCVNG_ADDR_T WHERE PUR_RCVNG_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT DLVY_CNTRY_CD AS NON_CONVERTABLE_CODES FROM PUR_RCVNG_LN_T WHERE DLVY_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT CPTL_AST_CNTRY_CD AS NON_CONVERTABLE_CODES FROM PUR_REQS_CPTL_AST_LOC_T WHERE CPTL_AST_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT PUR_RCVNG_CNTRY_CD AS NON_CONVERTABLE_CODES FROM PUR_REQS_T WHERE PUR_RCVNG_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT VNDR_CNTRY_CD AS NON_CONVERTABLE_CODES FROM PUR_VNDR_ADDR_T WHERE VNDR_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT VNDR_CNTRY_CD AS NON_CONVERTABLE_CODES FROM PUR_VNDR_CNTCT_T WHERE VNDR_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 
SELECT DISTINCT BLDG_ADDR_CNTRY_CD AS NON_CONVERTABLE_CODES FROM SH_BUILDING_T WHERE BLDG_ADDR_CNTRY_CD NOT IN
('AA','AC','AF','AG','AJ','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AV',
 'AY','BA','BB','BC','BD','BE','BF','BG','BH','BK','BL','BM','BN','BO','BP',
 'BQ','BR','BS','BT','BU','BV','BX','BY','CA','CB','CD','CE','CF','CG','CH',
 'CI','CJ','CK','CM','CN','CO','CQ','CR','CS','CT','CU','CV','CW','CY','DA',
 'DJ','DO','DR','EC','EG','EI','EK','EN','ER','ES','ET','EU','EZ','FA','FG',
 'FI','FJ','FM','FO','FP','FQ','FR','FS','GA','GB','GE','GG','GH','GI','GJ',
 'GK','GL','GM','GO','GP','GQ','GR','GT','GV','GY','GZ','HA','HK','HM','HO',
 'HQ','HR','HU','IC','ID','IM','IN','IO','IP','IR','IS','IT','IV','IZ','JA',
 'JE','JM','JN','JO','JQ','JU','KE','KG','KN','KQ','KR','KS','KT','KU','KZ',
 'LA','LE','LG','LH','LI','LO','LQ','LS','LT','LU','LY','MA','MB','MC','MD',
 'MF','MG','MH','MI','MK','ML','MN','MO','MP','MQ','MR','MT','MU','MV','MW',
 'MX','MY','MZ','NA','NC','NE','NF','NG','NH','NI','NL','NO','NP','NR','NS',
 'NU','NZ','OC','PA','PC','PE','PK','PL','PM','PO','PP','PS','PU','QA','RE',
 'RM','RO','RP','RQ','RS','RW','SA','SB','SC','SE','SF','SG','SH','SI','SL',
 'SM','SN','SO','SP','SR','ST','SU','SV','SW','SY','SZ','TC','TD','TE','TH',
 'TI','TK','TL','TN','TO','TP','TS','TU','TV','TW','TX','TZ','UG','UK','UP',
 'US','UY','UZ','VC','VE','VI','VM','VQ','VT','WA','WE','WF','WI','WQ','WS',
 'WZ','YM','ZA','ZI');
 